UPDATE search_question set answer = '/industry/{0}?bra_id={1}#wages' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Qual o número de estabelecimentos na Atividade Econômica X, na Localidade Y?';
UPDATE search_question set answer = '/industry/{0}?bra_id={1}' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Qual o salário médio da Atividade Econômica X, na Localidade Y?';
UPDATE search_question set answer = '/occupation/{0}?cnae_id={1}&bra_id={2}' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Qual o salário médio da Ocupação Z, na Atividade Econômica X, na Localidade Y?';
UPDATE search_question set answer = '/product/{0}?bra_id={1}#trade-partner' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais os principais parceiros comerciais de um Produto P na Localidade Y?';
UPDATE search_question set answer = '/industry/{0}#wages' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais localidades concentram o emprego na Atividade Econômica X?';
UPDATE search_question set answer = '/product/{0}#trade-partner' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais as localidades que mais importam o Produto P?';
UPDATE search_question set answer = '/product/{0}#trade-partner' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais as localidades que mais exportam o Produto P?';
UPDATE search_question set answer = '/location/{0}#opportunities' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais os produtos mais próximos da estrutura produtiva da Localidade Y?';
UPDATE search_question set answer = '/location/{0}#education' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais os cursos de nível superior oferecidos na Localidade Y?';
UPDATE search_question set answer = '/location/{0}#education' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Entrepreneurs') AND description_pt = 'Quais os cursos de nível técnico oferecidos na Localidade Y?';

UPDATE search_question SET answer = '/location/{0}#opportunities' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Qual a rede de produtos da Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#opportunities' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Quais os produtos mais próximos da estrutura produtiva da Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#trade-partner' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Quais os produtos de maior complexidade exportados por uma Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#trade-partner' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Quais os produtos de maior complexidade importados por uma Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#opportunities' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Qual a rede de atividades da Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#opportunities' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Quais as atividades mais próximas da estrutura produtiva da Localidade Y?';
UPDATE search_question SET answer = '/industry/{0}#wages' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Development Agents') AND description_pt = 'Quais localidades concentram o emprego na Atividade Econômica X?';

UPDATE search_question SET answer = '/location/{0}#education' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Quais os cursos de nível superior oferecidos na Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#education' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Quais os cursos de nível técnico oferecidos na Localidade Y?';
UPDATE search_question SET answer = '/occupation/{0}?bra_id={1}' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Qual o salário médio da Ocupação Z na Localidade Y?';
UPDATE search_question SET answer = '/occupation/{0}#wages' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Em quais localidades paga-se o maior salário médio da Ocupação Z?';
UPDATE search_question SET answer = '/occupation/{0}#wages' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Em quais localidades cresce o número de empregados da Ocupação Z?';
UPDATE search_question SET answer = '/location/{0}#trade-partner' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Quais os principais produtos exportados pela Localidade Y?';
UPDATE search_question SET answer = '/location/{0}#wages' WHERE profile_id = (SELECT id FROM search_profile where name_en = 'Students and Professionals') AND description_pt = 'Quais as principais atividades econômicas de uma Localidade Y?';
