update attrs_wld set img_author = 'David Stanley', img_link = 'https://flic.kr/p/8t7YjD' where id = 'naabw';
update attrs_wld set img_author = 'Tony Hisgett', img_link = 'https://flic.kr/p/4uzq4U' where id = 'afxxa';
update attrs_wld set img_author = 'Bryan Ledgard', img_link = 'https://flic.kr/p/nYZrmq' where id = 'eulva';
update attrs_wld set img_author = 'Mark Fischer', img_link = 'https://flic.kr/p/o8NgfH' where id = 'aflbr';
update attrs_wld set img_author = 'Jiuguang Wang', img_link = 'https://flic.kr/p/jamnKw' where id = 'eucze';
update attrs_wld set img_author = 'Francisco Anzola', img_link = 'https://flic.kr/p/umd6jw' where id = 'asaze';
update attrs_wld set img_author = 'dhell', img_link = 'https://flic.kr/p/eKqEV8' where id = 'afgnq';
update attrs_wld set img_author = 'Kyle Taylor', img_link = 'https://flic.kr/p/bUJrV2' where id = 'eulie';
update attrs_wld set img_author = 'Valerian Guillot', img_link = 'https://flic.kr/p/DJbkrt' where id = 'afsdn';
update attrs_wld set img_author = 'Leonora (Ellie) Enking', img_link = 'https://flic.kr/p/6epNWt' where id = 'afmdg';
update attrs_wld set img_author = 'SarahTz', img_link = 'https://flic.kr/p/qTUzMv' where id = 'afeth';
update attrs_wld set img_author = 'Fernando Flores', img_link = 'https://flic.kr/p/jttKzj' where id = 'saguy';
update attrs_wld set img_author = 'Moritz Dittmar', img_link = 'https://flic.kr/p/roxsWM' where id = 'eumne';
update attrs_wld set img_author = 'Caroline Granycome', img_link = 'https://flic.kr/p/rmgudi' where id = 'afcpv';
update attrs_wld set img_author = 'Stefan Wisselink', img_link = 'https://flic.kr/p/xwwCpV' where id = 'eusvk';
update attrs_wld set img_author = 'Marco Zanferrari', img_link = 'https://flic.kr/p/kBH52t' where id = 'asarm';
update attrs_wld set img_author = 'Klovovi', img_link = 'https://flic.kr/p/cU5rRs' where id = 'eumkd';
update attrs_wld set img_author = 'peter', img_link = 'https://flic.kr/p/hJrExN' where id = 'aftza';
update attrs_wld set img_author = 'Berit Watkin', img_link = 'https://flic.kr/p/bmvuMd' where id = 'nabrb';
update attrs_wld set img_author = 'kansasphoto', img_link = 'https://flic.kr/p/ePyBMc' where id = 'navgb';
update attrs_wld set img_author = 'Berit Watkin', img_link = 'https://flic.kr/p/gj1LrT' where id = 'eumlt';
update attrs_wld set img_author = 'Francisco Anzola', img_link = 'https://flic.kr/p/Ebkgi4' where id = 'afdji';
update attrs_wld set img_author = 'Mac Qin', img_link = 'https://flic.kr/p/o7JDJh' where id = 'asmdv';
update attrs_wld set img_author = 'Dennis Jarvis', img_link = 'https://flic.kr/p/7o8KgD' where id = 'eublr';
update attrs_wld set img_author = 'Anselmo Lastra', img_link = 'https://flic.kr/p/3mHbv7' where id = 'ocpng';
update attrs_wld set img_author = 'Didier Baertschiger', img_link = 'https://flic.kr/p/7rpMSk' where id = 'navct';
update attrs_wld set img_author = 'SarahTz', img_link = 'https://flic.kr/p/nbqiW7' where id = 'nakna';
update attrs_wld set img_author = 'Miwok', img_link = 'https://flic.kr/p/nFMnz2' where id = 'afreu';
update attrs_wld set img_author = 'Thomas Depenbusch', img_link = 'https://flic.kr/p/bYZZvy' where id = 'askgz';
update attrs_wld set img_author = 'Barbane Freixo', img_link = 'https://flic.kr/p/vMtoaB' where id = 'afgnb';
update attrs_wld set img_author = 'Dave Proffer', img_link = 'https://flic.kr/p/5M22Gm' where id = 'astkm';
update attrs_wld set img_author = 'Oleg Brovko', img_link = 'https://flic.kr/p/fu2PnN' where id = 'astjk';
update attrs_wld set img_author = 'Matthias Rip', img_link = 'https://flic.kr/p/pdzTmR' where id = 'nadma';
update attrs_wld set img_author = '(stephan)', img_link = 'https://flic.kr/p/2yQvUN' where id = 'asprk';
update attrs_wld set img_author = 'Leszek Kozlowski', img_link = 'https://flic.kr/p/5zUAco' where id = 'eumda';
update attrs_wld set img_author = 'kansasphoto', img_link = 'https://flic.kr/p/6MGHx2' where id = 'nabmu';
update attrs_wld set img_author = 'hdptcar', img_link = 'https://flic.kr/p/4kTrgB' where id = 'afcaf';
update attrs_wld set img_author = 'Bernard Spragg. NZ', img_link = 'https://flic.kr/p/nX6gWT' where id = 'asbrn';
update attrs_wld set img_author = 'David Mark', img_link = 'https://pixabay.com/photo-194478/' where id = 'aferi';
update attrs_wld set img_author = 'Photo RNW.org', img_link = 'https://flic.kr/p/5wcrhm' where id = 'asmng';
update attrs_wld set img_author = 'Ben Allen', img_link = 'https://flic.kr/p/66kcnL' where id = 'aftcd';
update attrs_wld set img_author = 'David Davies', img_link = 'https://flic.kr/p/oY1kmY' where id = 'afmwi';
update attrs_wld set img_author = 'Rachel Hartley', img_link = 'https://flic.kr/p/oXaRzc' where id = 'ocfji';
update attrs_wld set img_author = 'Roger Uceda', img_link = 'https://flic.kr/p/bqHt6G' where id = 'ocpyf';
update attrs_wld set img_author = 'Poxviridae', img_link = 'https://flic.kr/p/ea8Qjw' where id = 'eubih';
update attrs_wld set img_author = 'Nathalie Darras', img_link = 'https://flic.kr/p/bVo5GL' where id = 'afbfa';
update attrs_wld set img_author = 'João Fanara', img_link = 'https://flic.kr/p/oxQxzR' where id = 'afstp';
update attrs_wld set img_author = 'Daryl Wallace', img_link = 'https://flic.kr/p/6YAwgx' where id = 'afcom';
update attrs_wld set img_author = 'Sarah Kelemen Garber', img_link = 'https://flic.kr/p/69ehk7' where id = 'octon';
update attrs_wld set img_author = '::Lenz', img_link = 'https://flic.kr/p/DbVhXW' where id = 'asnpl';
update attrs_wld set img_author = 'Roland', img_link = 'https://flic.kr/p/awmhCh' where id = 'afner';