update attrs_hs set img_author = 'Jim Swinson', img_link = 'https://flic.kr/p/pprN8v' where id = '19';
update attrs_hs set img_author = 'Susanne Nilsson', img_link = 'https://flic.kr/p/fJCdmB' where id = '021001';
update attrs_hs set img_author = 'cookbookman17', img_link = 'https://flic.kr/p/ajVVcf' where id = '021006';
update attrs_hs set img_author = 'Peter Craven', img_link = 'https://flic.kr/p/aCYviJ' where id = '157204';
update attrs_hs set img_author = 'Manuel', img_link = 'https://flic.kr/p/fKEFZY' where id = '168479';
update attrs_hs set img_author = 'hottholler', img_link = 'https://flic.kr/p/7CYfHq' where id = '094411';
update attrs_hs set img_author = 'Nicolas Raymond', img_link = 'https://flic.kr/p/dbvTz6' where id = '147103';
update attrs_hs set img_author = 'Hannah Rosen', img_link = 'https://flic.kr/p/5Tdke5' where id = '063305';
update attrs_hs set img_author = 'Veganbaking.net', img_link = 'https://flic.kr/p/qdwxWC' where id = '041804';
update attrs_hs set img_author = 'Andrew Nash', img_link = 'https://flic.kr/p/a5AbEq' where id = '168474';
update attrs_hs set img_author = 'Alexander Boden', img_link = 'https://flic.kr/p/fir4fS' where id = '189032';
update attrs_hs set img_author = 'Dāvis Mosāns', img_link = 'https://flic.kr/p/fn8Wy8' where id = '157213';
update attrs_hs set img_author = 'Dennis van Zuijlekom', img_link = 'https://flic.kr/p/cahfZU' where id = '063402';
update attrs_hs set img_author = 'Dennis van Zuijlekom', img_link = 'https://flic.kr/p/cahfZU' where id = '063006';
update attrs_hs set img_author = '6SN7', img_link = 'https://flic.kr/p/n9Zgjv' where id = '168537';
update attrs_hs set img_author = 'Dennis Jarvis', img_link = 'https://flic.kr/p/jgUYTK' where id = '126406';
update attrs_hs set img_author = 'Andrew Magill', img_link = 'https://flic.kr/p/5YNYqc' where id = '168424';
update attrs_hs set img_author = 'Timothy Allen', img_link = 'https://flic.kr/p/yQWAr' where id = '168418';
update attrs_hs set img_author = 'Phalinn Ooi', img_link = 'https://flic.kr/p/dnc6VE' where id = '189021';
update attrs_hs set img_author = 'Beyond Coal & Gas Image Library', img_link = 'https://flic.kr/p/fbbaLa' where id = '052602';
update attrs_hs set img_author = 'Paulo Valdivieso', img_link = 'https://flic.kr/p/67Cjb3' where id = '074016';
update attrs_hs set img_author = 'Phalinn Ooi', img_link = 'https://flic.kr/p/dnc6VE' where id = '189018';
update attrs_hs set img_author = 'Dāvis Mosāns', img_link = 'https://flic.kr/p/fn8Wy8' where id = '157209';
update attrs_hs set img_author = 'glaubercavalcante', img_link = 'https://flic.kr/p/5xqBfz' where id = '020801';
update attrs_hs set img_author = 'Mark Hunter', img_link = 'https://flic.kr/p/7A8KrB' where id = '168502';
update attrs_hs set img_author = 'Jukka', img_link = 'https://flic.kr/p/cMqfmQ' where id = '094401';
update attrs_hs set img_author = 'Christian Frausto Bernal', img_link = 'https://flic.kr/p/cxH5g' where id = '168432';
update attrs_hs set img_author = 'Eliana Buchaul', img_link = 'https://flic.kr/p/7DKg2Q' where id = '115603';
update attrs_hs set img_author = 'David Precious', img_link = 'https://flic.kr/p/6T9vJd' where id = '168511';
update attrs_hs set img_author = 'Mgoncalles', img_link = 'https://flic.kr/p/94PiUA' where id = '178711';
update attrs_hs set img_author = 'QIAGEN', img_link = 'https://flic.kr/p/cNZYXL' where id = '062933';
update attrs_hs set img_author = 'Industrial Traffic', img_link = 'https://flic.kr/p/o4JKKY' where id = '157228';
update attrs_hs set img_author = 'zeevveez', img_link = 'https://flic.kr/p/uaeo1D' where id = '157307';
update attrs_hs set img_author = 'Lisa Risager', img_link = 'https://flic.kr/p/6rDfx6' where id = '041704';
update attrs_hs set img_author = 'Garry Knight', img_link = 'https://flic.kr/p/b8uFY2' where id = '168482';
update attrs_hs set img_author = 'Sandia Labs', img_link = 'https://flic.kr/p/dLDxa1' where id = '063824';
update attrs_hs set img_author = 'royalty free', img_link = 'https://flic.kr/p/fnoErz' where id = '168467';
update attrs_hs set img_author = 'Beyond Coal & Gas Image Library', img_link = 'https://flic.kr/p/fbbaLa' where id = '052604';
update attrs_hs set img_author = 'James St. John', img_link = 'https://flic.kr/p/os4pAy' where id = '147112';
update attrs_hs set img_author = 'Toshiyuki IMAI', img_link = 'https://flic.kr/p/7hqFjp' where id = '168419';
update attrs_hs set img_author = 'Industrial Traffic', img_link = 'https://flic.kr/p/o4JKKY' where id = '158001';
update attrs_hs set img_author = 'WEG EQUIPAMENTOS ELÉTRICOS S.A.', img_link = 'https://flic.kr/p/9gQKYa' where id = '168439';
update attrs_hs set img_author = 'Bill Bumgarner', img_link = 'https://flic.kr/p/EzGBw' where id = '168532';
update attrs_hs set img_author = 'royalty free', img_link = 'https://flic.kr/p/fnoErz' where id = '158207';
update attrs_hs set img_author = 'Smabs Sputzer', img_link = 'https://flic.kr/p/iB6Tkn' where id = '031521';
update attrs_hs set img_author = 'Bill Bumgarner', img_link = 'https://flic.kr/p/EzGBw' where id = '168507';
update attrs_hs set img_author = 'Adriano Barros', img_link = 'https://flic.kr/p/o9BPns' where id = '073926';
update attrs_hs set img_author = 'Igor Mota', img_link = 'https://flic.kr/p/fjrGKF' where id = '021202';
update attrs_hs set img_author = 'vitor cheregati', img_link = 'https://flic.kr/p/qrXGHW' where id = '209401';
update attrs_hs set img_author = 'Jim Swinson', img_link = 'https://flic.kr/p/pprN8v' where id = '199303';
update attrs_hs set img_author = 'Mikbilly', img_link = 'https://flic.kr/p/9CdXSg' where id = '063806';
update attrs_hs set img_author = 'Rob Friesel', img_link = 'https://flic.kr/p/37xHq' where id = '136813';
update attrs_hs set img_author = 'Gabrielle Idealli', img_link = 'https://flic.kr/p/fijuxn' where id = '21';
update attrs_hs set img_author = 'Edsel Little', img_link = 'https://flic.kr/p/D84Tpm' where id = '010206';
update attrs_hs set img_author = 'Javier Mendia García', img_link = 'https://flic.kr/p/kmEpM5' where id = '062901';
update attrs_hs set img_author = 'Secretaria de Agricultura e Abastecimento', img_link = 'https://flic.kr/p/91rPMj' where id = '020904';
update attrs_hs set img_author = 'Randen Pederson', img_link = 'https://flic.kr/p/5UaL9k' where id = '168503';
update attrs_hs set img_author = 'Città Di Modena', img_link = 'https://flic.kr/p/9kemkL' where id = '010504';
update attrs_hs set img_author = 'aniara.', img_link = 'https://flic.kr/p/76xhPu' where id = '062902';
update attrs_hs set img_author = 'Osamu Iwasaki', img_link = 'https://flic.kr/p/78rj3J' where id = '168544';
update attrs_hs set img_author = 'elsexoylaguerra', img_link = 'https://flic.kr/p/91z1nG' where id = '168504';
update attrs_hs set img_author = 'Horia Varlan', img_link = 'https://flic.kr/p/7vFcRJ' where id = '062922';
update attrs_hs set img_author = 'HoRoCue', img_link = 'https://flic.kr/p/rTSD9s' where id = '136908';
update attrs_hs set img_author = 'Cícero R. C. Omena', img_link = 'https://flic.kr/p/qiBuKK' where id = '168433';
update attrs_hs set img_author = 'Creativity103', img_link = 'https://flic.kr/p/ops5R9' where id = '104804';
update attrs_hs set img_author = 'Chris Campbell', img_link = 'https://flic.kr/p/sXpX' where id = '168517';
update attrs_hs set img_author = 'QIAGEN', img_link = 'https://flic.kr/p/cNZYXL' where id = '062909';
update attrs_hs set img_author = 'SimonQ錫濛譙', img_link = 'https://flic.kr/p/djcxwW' where id = '010402';
update attrs_hs set img_author = 'Secretaria de Agricultura e Abastecimento', img_link = 'https://flic.kr/p/y5esXJ' where id = '063808';
update attrs_hs set img_author = 'Valdiney Pimenta', img_link = 'https://flic.kr/p/7e5a2r' where id = '094418';
update attrs_hs set img_author = 'gaelx', img_link = 'https://flic.kr/p/54t3VE' where id = '063503';
update attrs_hs set img_author = 'El Coleccionista de Instantes Fotografía & Video', img_link = 'https://flic.kr/p/8DFLNf' where id = '178707';
update attrs_hs set img_author = 'Guillermo Robles Martínez', img_link = 'https://flic.kr/p/7Zmdk9' where id = '052606';
update attrs_hs set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/aQPMHk' where id = '062804';
update attrs_hs set img_author = 'Secretaria de Agricultura e Abastecimento', img_link = 'https://flic.kr/p/cyHfsy' where id = '063301';
update attrs_hs set img_author = 'taymtaym', img_link = 'https://flic.kr/p/ozgCcd' where id = '157214';
update attrs_hs set img_author = 'MunicipioPinas', img_link = 'https://flic.kr/p/7wULzo' where id = '063105';
update attrs_hs set img_author = 'John Perivolaris', img_link = 'https://flic.kr/p/oe9HM9' where id = '104702';
update attrs_hs set img_author = 'Galeria del Ministerio de Defensa del Perú', img_link = 'https://flic.kr/p/xVE86u' where id = '199306';
update attrs_hs set img_author = 'Jônatas Cunha', img_link = 'https://flic.kr/p/7w56w2' where id = '157326';
update attrs_hs set img_author = 'Mauro Victor Barboza', img_link = 'https://flic.kr/p/kwBSyi' where id = '157408';
update attrs_hs set img_author = 'Jason Mrachina', img_link = 'https://flic.kr/p/dFgK3C' where id = '157219';
update attrs_hs set img_author = 'Prefeitura de Olinda', img_link = 'https://flic.kr/p/7Zj4dz' where id = '178702';
update attrs_hs set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/8az2FK' where id = '104811';
update attrs_hs set img_author = 'pglomba', img_link = 'https://flic.kr/p/aQeyT8' where id = '168536';
update attrs_hs set img_author = 'Victoria Rachitzky Hoch', img_link = 'https://flic.kr/p/pTYCf' where id = '020807';
update attrs_hs set img_author = 'SENTEY', img_link = 'https://flic.kr/p/8FeYx2' where id = '157606';
update attrs_hs set img_author = 'Defesa Agropecuaria de São Paulo', img_link = 'https://flic.kr/p/qdk9C1' where id = '010102';
update attrs_hs set img_author = 'Luiz Alexandre', img_link = 'https://flic.kr/p/4uHwHV' where id = '042309';
update attrs_hs set img_author = 'gato-gato-gato', img_link = 'https://flic.kr/p/4NrbjT' where id = '052713';
update attrs_hs set img_author = 'Panchonto', img_link = 'https://flic.kr/p/4uHwHV' where id = '020804';
update attrs_hs set img_author = 'Code09FIM', img_link = 'https://flic.kr/p/9q9SWr' where id = '073907';
update attrs_hs set img_author = 'Stella Dauer', img_link = 'https://flic.kr/p/64KNkx' where id = '074002';
update attrs_hs set img_author = 'MUSA Texturas', img_link = 'https://flic.kr/p/tgYc3f' where id = '052507';
update attrs_hs set img_author = 'XTRAICE Synthetic Ice Rinks', img_link = 'https://flic.kr/p/9ficHX' where id = '073920';
update attrs_hs set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/7kuPrm' where id = '157502';
update attrs_hs set img_author = 'Jean-Etienne Minh-Duy Poirrier', img_link = 'https://flic.kr/p/29cVdL' where id = '157225';
update attrs_hs set img_author = 'Christian Córdova', img_link = 'https://flic.kr/p/6LXqF8' where id = '052516';
update attrs_hs set img_author = 'scribbletaylor', img_link = 'https://flic.kr/p/9cirzL' where id = '073923';
update attrs_hs set img_author = 'ATOMIC Hot Links', img_link = 'https://flic.kr/p/5CBys6' where id = '168408';
update attrs_hs set img_author = 'Maria Hennies', img_link = 'https://flic.kr/p/pKbGAP' where id = '02';
update attrs_hs set img_author = 'Jarzyn', img_link = 'https://flic.kr/p/4u2jXq' where id = '05';
update attrs_hs set img_author = 'Tea Bo', img_link = 'https://flic.kr/p/gcSUNf' where id = '04';
update attrs_hs set img_author = 'Nicole Maki', img_link = 'https://flic.kr/p/7RoBj6' where id = '021201';
update attrs_hs set img_author = 'Antonio Díaz Cueto', img_link = 'https://flic.kr/p/ef1Q9U' where id = '17';
update attrs_hs set img_author = 'Mechel OAO', img_link = 'https://flic.kr/p/fEY3Dh' where id = '15';
update attrs_hs set img_author = 'Birgit O.', img_link = 'https://flic.kr/p/nbidDs' where id = '16';
update attrs_hs set img_author = 'Nicolas Mac Mahon', img_link = 'https://flic.kr/p/ePMrPS' where id = '01';
update attrs_hs set img_author = 'Daniel Kelpe', img_link = 'https://flic.kr/p/4zUELf' where id = '052601';
update attrs_hs set img_author = 'The Red-Pill Photo Gallery', img_link = 'https://flic.kr/p/cfBB3s' where id = '052709';
update attrs_hs set img_author = 'Bo Buran', img_link = 'https://flic.kr/p/dTuFp3' where id = '06';
update attrs_hs set img_author = 'ainsley and steph', img_link = 'https://flic.kr/p/9uqTHn' where id = '10';
update attrs_hs set img_author = 'Amelia Monteiro', img_link = 'https://flic.kr/p/fD5A8x' where id = '041701';
update attrs_hs set img_author = 'abbie', img_link = 'https://flic.kr/p/4VzhHv' where id = '010207';
update attrs_hs set img_author = 'United Soybean Board', img_link = 'https://flic.kr/p/gjT5qj' where id = '042304';
update attrs_hs set img_author = 'yo_aguilar', img_link = 'https://flic.kr/p/o6zsWA' where id = '020901';
update attrs_hs set img_author = 'coldclimatehousing', img_link = 'https://flic.kr/p/aS8QxK' where id = '104703';
update attrs_hs set img_author = 'kay ef', img_link = 'https://flic.kr/p/5Cc6Xt' where id = '07';
update attrs_hs set img_author = 'liz west', img_link = 'https://flic.kr/p/cwpVtA' where id = '021005';
update attrs_hs set img_author = 'Vlad Busuioc', img_link = 'https://flic.kr/p/oNxbnK' where id = '178802';
update attrs_hs set img_author = 'Senado Federal', img_link = 'https://flic.kr/p/ph5Y6y' where id = '010202';
update attrs_hs set img_author = 'itzkirb', img_link = 'https://flic.kr/p/nSzdF8' where id = '178703';
update attrs_hs set img_author = 'Mario Fabbri', img_link = 'https://flic.kr/p/kbQRMv' where id = '14';
update attrs_hs set img_author = 'Talmax Produtos Prótese Odontológica', img_link = 'https://flic.kr/p/nMWnwj' where id = '062818';
update attrs_hs set img_author = 'Mzximvs VdB', img_link = 'https://flic.kr/p/pouCmk' where id = '08';
update attrs_hs set img_author = 'Colaptes', img_link = 'https://flic.kr/p/cvhAb' where id = '11';
update attrs_hs set img_author = 'Fulvio', img_link = 'https://flic.kr/p/5psjuJ' where id = '157207';
update attrs_hs set img_author = 'Alessandro Casagrande', img_link = 'https://flic.kr/p/4QeTyn' where id = '147108';
update attrs_hs set img_author = 'ATOMIC Hot Links', img_link = 'https://flic.kr/p/ryNtCP' where id = '178708';
update attrs_hs set img_author = 'ish orb', img_link = 'https://flic.kr/p/5bBA3r' where id = '09';
update attrs_hs set img_author = 'Mechel OAO', img_link = 'https://flic.kr/p/fEY3Dh' where id = '157202';
update attrs_hs set img_author = 'vitor cheregati', img_link = 'https://flic.kr/p/rpT2fk' where id = '042401';
update attrs_hs set img_author = 'Roberto Guglielmo', img_link = 'https://flic.kr/p/6PqX4c' where id = '042009';
update attrs_hs set img_author = 'Judy Reiss', img_link = 'https://flic.kr/p/7hzDqT' where id = '052603';
update attrs_hs set img_author = 'Ennio Vanzan', img_link = 'https://flic.kr/p/9rDZam' where id = '168411';
update attrs_hs set img_author = 'Rctk caRIOca', img_link = 'https://flic.kr/p/kXkFTv' where id = '178905';
update attrs_hs set img_author = 'noelia ayala', img_link = 'https://flic.kr/p/7X9k3h' where id = '13';
update attrs_hs set img_author = 'PROAl Disley Images', img_link = 'https://flic.kr/p/sjSJHm' where id = '052710';
update attrs_hs set img_author = 'U.S. Department of Agriculture', img_link = 'https://flic.kr/p/d1piGL' where id = '03';
update attrs_hs set img_author = 'TruckPR', img_link = 'https://flic.kr/p/fkk3WA' where id = '178704';
update attrs_hs set img_author = 'hj_west', img_link = 'https://flic.kr/p/ebCheH' where id = '168409';
update attrs_hs set img_author = 'OakleyOriginals', img_link = 'https://flic.kr/p/fCnUQn' where id = '084107';
update attrs_hs set img_author = 'Terry Feuerborn', img_link = 'https://flic.kr/p/fEQsWz' where id = '115201';
update attrs_hs set img_author = 'buttha', img_link = 'https://flic.kr/p/6JsXWF' where id = '168429';
update attrs_hs set img_author = 'velkr0', img_link = 'https://flic.kr/p/DT78m' where id = '073901';
update attrs_hs set img_author = 'Le Mai', img_link = 'https://flic.kr/p/4k17G' where id = '041602';
update attrs_hs set img_author = 'Adrian Rowbotham', img_link = 'https://flic.kr/p/49URR' where id = '158307';
update attrs_hs set img_author = 'Mike', img_link = 'https://flic.kr/p/nTxu3s' where id = '010203';
update attrs_hs set img_author = 'United Soybean Board', img_link = 'https://flic.kr/p/gjWL1c' where id = '031507';
update attrs_hs set img_author = 'katefmcd', img_link = 'https://flic.kr/p/dAybxF' where id = '12';
update attrs_hs set img_author = 'Heather', img_link = 'https://flic.kr/p/7hx2BD' where id = '074011';
update attrs_hs set img_author = 'IrisAriel', img_link = 'https://flic.kr/p/9sYEDB' where id = '063004';
update attrs_hs set img_author = 'U.S. Department of Agriculture', img_link = 'https://flic.kr/p/pgMdQH' where id = '178701';
update attrs_hs set img_author = 'the Craftmen', img_link = 'https://flic.kr/p/fh7UgD' where id = '084104';
update attrs_hs set img_author = 'mykle hoban', img_link = 'https://flic.kr/p/HzQk2' where id = '136802';
update attrs_hs set img_author = 'Rachel Andrew', img_link = 'https://flic.kr/p/rAXgZ' where id = '157208';
update attrs_hs set img_author = 'ImAGingerMonkey', img_link = 'https://flic.kr/p/bmrphX' where id = '20';
update attrs_hs set img_author = 'Daniel70mi Falciola', img_link = 'https://flic.kr/p/m5wpLZ' where id = '042207';
update attrs_hs set img_author = 'FEMA SRL', img_link = 'https://flic.kr/p/nXmBf8' where id = '18';
update attrs_hs set img_author = 'John Perivolaris', img_link = 'https://flic.kr/p/oe9HM9' where id = '104802';
update attrs_hs set img_author = 'Paul Henegan', img_link = 'https://flic.kr/p/nbQwSG' where id = '157201';
update attrs_hs set img_author = 'Lord Cogsby', img_link = 'https://flic.kr/p/zrk7QW' where id = '168414';
update attrs_hs set img_author = 'Mr.TinDC', img_link = 'https://flic.kr/p/7xqFex' where id = '168481';
update attrs_hs set img_author = 'Tarek Alrosan', img_link = 'https://flic.kr/p/ogprMe' where id = '157304';
update attrs_hs set img_author = 'Christyam de Lima', img_link = 'https://flic.kr/p/s181JD' where id = '010201';
update attrs_hs set img_author = 'Seboo Corporationn', img_link = 'https://flic.kr/p/gz4cbM' where id = '168501';
update attrs_hs set img_author = 'Industrial Traffic', img_link = 'https://flic.kr/p/o4JKKY' where id = '157224';
update attrs_hs set img_author = 'vcheregati', img_link = 'https://flic.kr/p/rpL6ni' where id = '042403';
update attrs_hs set img_author = 'Rodrigo Denúbila', img_link = 'https://flic.kr/p/5YjVar' where id = '158309';
update attrs_hs set img_author = 'PeterBoc', img_link = 'https://flic.kr/p/b1Eajg' where id = '020806';
update attrs_hs set img_author = 'Jeff Luyten', img_link = 'https://flic.kr/p/83cFMj' where id = '063304';
update attrs_hs set img_author = 'Josep', img_link = 'https://flic.kr/p/4T5hR1' where id = '052524';
update attrs_hs set img_author = 'Kai Schreiber', img_link = 'https://flic.kr/p/Pdqee' where id = '010303';
update attrs_hs set img_author = 'Sebastián Betancourt', img_link = 'https://flic.kr/p/aDVHPS' where id = '178607';
update attrs_hs set img_author = 'André Solnik', img_link = 'https://flic.kr/p/73Biv6' where id = '021302';
update attrs_hs set img_author = 'Núcleo Editorial', img_link = 'https://flic.kr/p/s6zA7w' where id = '042308';
update attrs_hs set img_author = 'Jo Naylor', img_link = 'https://flic.kr/p/9vcsT4' where id = '137019';
update attrs_hs set img_author = 'Antonio da Silva Martins', img_link = 'https://flic.kr/p/y8CyZa' where id = '219701';
update attrs_hs set img_author = 'ASCOM', img_link = 'https://flic.kr/p/88QEP5' where id = '063002';
update attrs_hs set img_author = 'UnB Agência', img_link = 'https://flic.kr/p/oy9Lke' where id = '062917';
update attrs_hs set img_author = 'Roland DG Mid Europe Italia', img_link = 'https://flic.kr/p/9mGKVn' where id = '073909';
update attrs_hs set img_author = 'Orgânicos do PIVAS', img_link = 'https://flic.kr/p/e68YTj' where id = '021209';
update attrs_hs set img_author = 'Sandy Kirchlechner', img_link = 'https://flic.kr/p/98UvKm' where id = '042008';
update attrs_hs set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/b8Agqr' where id = '041805';
update attrs_hs set img_author = 'Dennis van Zuijlekom', img_link = 'https://flic.kr/p/pYt3NX' where id = '189026';
update attrs_hs set img_author = 'Paul Hudson', img_link = 'https://flic.kr/p/DBXKzQ' where id = '062910';
update attrs_hs set img_author = 'Mike', img_link = 'https://flic.kr/p/4hTGTv' where id = '062916';
update attrs_hs set img_author = 'Luiz Alexandre', img_link = 'https://flic.kr/p/4uHwHV' where id = '042301';
update attrs_hs set img_author = 'Tomas Barrios', img_link = 'https://flic.kr/p/7N1Nes' where id = '063302';
update attrs_hs set img_author = 'Elexandre Reis', img_link = 'https://flic.kr/p/5hnd4H' where id = '157306';
update attrs_hs set img_author = 'Alan Dubner', img_link = 'https://flic.kr/p/9gy5tm' where id = '136902';
update attrs_hs set img_author = 'UnB Agência', img_link = 'https://flic.kr/p/cAs77y' where id = '209406';
update attrs_hs set img_author = 'Leandro Martinez', img_link = 'https://flic.kr/p/ddF16T' where id = '010105';
update attrs_hs set img_author = 'IES MANUEL GARCÍA BARROS ', img_link = 'https://flic.kr/p/o6ymB4' where id = '062915';
update attrs_hs set img_author = 'Fabricio Zuardi', img_link = 'https://flic.kr/p/5PmED7' where id = '073903';
update attrs_hs set img_author = 'Ultra-lab', img_link = 'https://flic.kr/p/eZzwUe' where id = '115402';
update attrs_hs set img_author = 'Dean Hochman', img_link = 'https://flic.kr/p/EV4ic8' where id = '157607';
update attrs_hs set img_author = 'Wojciech Kulicki', img_link = 'https://flic.kr/p/agCmvT' where id = '157612';
update attrs_hs set img_author = 'Paul Keller', img_link = 'https://flic.kr/p/8MXFVr' where id = '168529';
update attrs_hs set img_author = 'PAULO LINS', img_link = 'https://flic.kr/p/5ToF4r' where id = '115607';
update attrs_hs set img_author = 'Bullion Vault', img_link = 'https://flic.kr/p/6toyNZ' where id = '062843';
update attrs_hs set img_author = 'João Paulo Corrêa de Carvalho', img_link = 'https://flic.kr/p/6fzwCR' where id = '157320';
update attrs_hs set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/7poWgK' where id = '168438';
update attrs_hs set img_author = 'Jane Dickson', img_link = 'https://flic.kr/p/5Lpj5M' where id = '157505';
update attrs_hs set img_author = 'Terran21', img_link = 'https://flic.kr/p/oq6Sk4' where id = '168455';
update attrs_hs set img_author = 'Umair Mohsin', img_link = 'https://flic.kr/p/5LaomR' where id = '115305';
update attrs_hs set img_author = 'Agência Brasília', img_link = 'https://flic.kr/p/yZL4Na' where id = '189031';
update attrs_hs set img_author = 'Enzymlogic', img_link = 'https://flic.kr/p/mQiJBL' where id = '063507';
update attrs_hs set img_author = 'ABUS Security Tech Germany', img_link = 'https://flic.kr/p/8D7p5d' where id = '168473';
update attrs_hs set img_author = 'Marlon J. Manrique', img_link = 'https://flic.kr/p/5tX27n' where id = '168412';
update attrs_hs set img_author = 'Eli Duke', img_link = 'https://flic.kr/p/9AwH7E' where id = '189029';
update attrs_hs set img_author = 'Barta IV', img_link = 'https://flic.kr/p/yqd2P1' where id = '157217';
update attrs_hs set img_author = 'Chris Yunker', img_link = 'https://flic.kr/p/6FKjBt' where id = '157309';
update attrs_hs set img_author = 'David Martín :: Suki_ ::', img_link = 'https://flic.kr/p/cpYBnW' where id = '168477';
update attrs_hs set img_author = 'Alexandr Trubetskoy', img_link = 'https://flic.kr/p/auYhTK' where id = '157227';
update attrs_hs set img_author = 'Sandy Poore', img_link = 'https://flic.kr/p/4iRFCg' where id = '031520';