CREATE TABLE help_subject(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    name_en varchar (50) NULL,
    name_pt varchar (50) NULL,
    PRIMARY KEY (id)
);
​
CREATE TABLE help_subject_question(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    description_en varchar (400) NULL,
    description_pt varchar (400) NULL,
    answer_en longtext NULL,
    answer_pt longtext NULL,
    subject_id int UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (subject_id) REFERENCES help_subject(id)
);


insert into help_subject(name_pt) values ('Primeiros Passos');
insert into help_subject(name_pt) values ('Dúvidas Frequentes');
insert into help_subject(name_pt) values ('Fontes de Dados');
insert into help_subject(name_pt) values ('Classificações por Categoria');
insert into help_subject(name_pt) values ('Tipos de Visualização');
insert into help_subject(name_pt) values ('Glossário');

insert into help_subject_question(subject_id, description_pt, answer_pt) values ((select  id from help_subject where name_pt = 'Fontes de Dados'), 'RAIS', '<p><span style="color: rgb(103, 106, 108);">Relação Anual de Informações Sociais</span><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Ministério do Trabalho e Emprego – MTE</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">A RAIS é um registro administrativo com periodicidade anual criado com a finalidade de suprir as necessidades de controle, estatística e informação às entidades governamentais da área social. Constitui um instrumento imprescindível para o cumprimento das normas legais e para o acompanhamento e a caracterização do mercado de trabalho formal.</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">O cenário profissional do país é retratado a partir de informações declaradas pelas próprias empresas sobre sua situação em 31 de dezembro do ano anterior, informando dados sobre seus empregados, atividade econômica desenvolvida, entre outras características. Atualmente, segundo o IBGE, a RAIS cobre aproximadamente 97% do universo do mercado formal brasileiro.</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">A partir dos dados da RAIS, o DataViva apresenta informações sobre o número de empregos, salários e número de estabelecimentos. O nível de agregação, em termos geográficos, pode ser feito por unidades da federação, mesorregiões, microrregiões e municípios; em termos de setores, seçāo, divisão e classes, de acordo com a CNAE; e, em termos de ocupações, grupo principal e famílias, de acordo com a CBO 2002.</span><br></p>');
insert into help_subject_question(subject_id, description_pt, answer_pt) values ((select  id from help_subject where name_pt = 'Fontes de Dados'), 'SECEX/MDIC', '<p><span style="color: rgb(103, 106, 108);">Banco de Dados da Secretaria de Comércio Exterior</span><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Ministério do Desenvolvimento, Indústria e Comércio Exterior – MDIC</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">O Banco de Dados da SECEX/MDIC possibilita a análise histórica do comportamento do intercâmbio comercial brasileiro, um dos mais importantes indicadores de desempenho da economia. Retrata e avalia o movimento comercial do país com as demais nações do mundo, englobando as vendas e compras efetuadas externamente.</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Constitui um instrumento básico para tomada de decisão e determinação de diretrizes econômicas por parte do Governo e permite aos agentes envolvidos na atividade o melhor planejamento das suas ações pela análise dos dados concretos das exportações e importações, aumentando as oportunidades de desenvolvimento do comércio externo.</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">A partir dos dados do SECEX/MDIC, o DataViva apresenta informações mensais de exportações e importações brasileiras, de 2000 em diante. As principais variáveis são: valor das exportações e das importações por munícipio, unidade da federação produtora, municípios exportadores e país de destino ou origem. Os dados são divulgados para os seguintes recortes geográficos: Brasil, unidades da federação, mesorregiões, microrregiões e municípios. Por produto de acordo com o Harmonyzed System (HS Code), agregados em: seção, capítulo e posição.</span><br></p>');
insert into help_subject_question(subject_id, description_pt, answer_pt) values ((select  id from help_subject where name_pt = 'Fontes de Dados'), 'Censo Escolar', '<p><span style="color: rgb(103, 106, 108);">Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira – INEP</span><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Ministério da Educação – MEC</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">O Censo Escolar é um levantamento de dados estatístico-educacionais de âmbito nacional realizado todos os anos e coordenado pelo INEP. Ele é feito com a colaboração das secretarias estaduais e municipais de Educação e com a participação de todas as escolas públicas e privadas do país.&nbsp;</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Trata-se do principal instrumento de coleta de informações da educação básica, que abrange as suas diferentes etapas e modalidades: ensino regular (educação Infantil e ensinos fundamental e médio), educação especial e educação de jovens e adultos (EJA). O Censo Escolar coleta dados sobre estabelecimentos, matrículas, funções docentes, movimento e rendimento escolar.&nbsp;</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">A partir do Censo Escolar, no DataViva são apresentadas informações sobre o número de matrículas em cada ano/série do ensino básico, agregados por município, microrregião, mesorregião ou unidade da federação. Dados sobre cursos profissionalizantes também pode ser visualizados, neste caso especificando o curso nos mesmos níveis geográficos da educação básica. As escolas também estão divididas por tipo de dependência administrativa e os cursos podem ser filtrados por turno.&nbsp;</span><br></p>');
insert into help_subject_question(subject_id, description_pt, answer_pt) values ((select  id from help_subject where name_pt = 'Fontes de Dados'), 'Censo do Ensino Superior', '<p><span style="color: rgb(103, 106, 108);">Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira – INEP</span><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Ministério da Educação – MEC</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Anualmente, o Inep também realiza a coleta de dados sobre a educação superior com o objetivo de oferecer à comunidade acadêmica e à sociedade em geral informações detalhadas sobre a situação e as grandes tendências do setor.&nbsp;</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">O Censo da Educação Superior reúne informações sobre as instituições de ensino superior, seus cursos de graduação presencial ou à distância, cursos sequenciais, vagas oferecidas, inscrições, matrículas, ingressantes e concluintes, além de informações sobre docentes, nas diferentes formas de organização acadêmica e categoria administrativa.</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">A partir dos dados do Censo do Ensino Superior, o DataViva apresenta informações sobre estudantes (ingressantes, matrículas e concluintes) para todos os cursos de nível superior, organizadas por localidades ou por universidades. Os níveis de agregação para as localidades são município, microrregião, mesorregião e unidade da federação. As universidades (e demais organizações acadêmicas) também estão divididas por tipo de dependência administrativa.</span><br></p>');
insert into help_subject_question(subject_id, description_pt, answer_pt) values ((select  id from help_subject where name_pt = 'Fontes de Dados'), 'UN Comtrade', '<p><span style="color: rgb(103, 106, 108);">Banco de Dados Estatísticos de Comércio de Produtos das Nações Unidas</span><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">Divisão de Estatísticas das Nações Unidas</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">O Banco de Dados Estatísticos de Comércio de Commodities das Nações Unidas (UN Comtrade) contém estatísticas detalhadas sobre importações e exportações relatadas pelas autoridades estatísticas de cerca de 200 países ou áreas. O UN Comtrade é considerado o banco de dados mais abrangente disponível de comércio internacional, com mais de 1 bilhão de registros. O banco de dados é constantemente atualizado: sempre que os dados de comércio são recebidos de autoridades nacionais, são padronizados pela Divisão de Estatísticas das Nações Unidas e então adicionados ao UN Comtrade.&nbsp;</span><br style="color: rgb(103, 106, 108);"><br style="color: rgb(103, 106, 108);"><span style="color: rgb(103, 106, 108);">No DataViva, as informações do UM Comtrade utilizadas para a realização de comparações internacionais são: origem e destino das exportações e valor exportado detalhado por produto. É importante ressaltar que os dados não estão disponíveis para visualização, eles são utilizados somente para o cálculo de alguns indicadores no DataViva.</span><br></p>');