update attrs_wld set img_author = 'mehmet canli', img_link = 'https://flic.kr/p/r9du3x' where id = 'as';
update attrs_wld set img_author = 'David Sanz', img_link = 'https://flic.kr/p/dmWsSN' where id = 'eu';
update attrs_wld set img_author = 'Esther Lee', img_link = 'https://flic.kr/p/8ESZ7K' where id = 'aschn';
update attrs_wld set img_author = 'Eric Fischer', img_link = 'https://flic.kr/p/a1swhv' where id = 'na';
update attrs_wld set img_author = 'Rennett Stowe', img_link = 'https://flic.kr/p/BwqiRK' where id = 'sa';
update attrs_wld set img_author = 'Nicolas Raymond', img_link = 'https://flic.kr/p/qiHWHM' where id = 'nausa';
update attrs_wld set img_author = 'alq666', img_link = 'https://flic.kr/p/44MKzk' where id = 'saarg';
update attrs_wld set img_author = 'Elyktra', img_link = 'https://flic.kr/p/cbst71' where id = 'eunld';
update attrs_wld set img_author = 'Peter Pham', img_link = 'https://flic.kr/p/CU4uq7' where id = 'af';
update attrs_wld set img_author = 'Cesar I. Martins', img_link = 'https://flic.kr/p/ejME5v' where id = 'eudeu';
update attrs_wld set img_author = 'Moyan Brenn', img_link = 'https://flic.kr/p/qgrydB' where id = 'asjpn';
update attrs_wld set img_author = 'Douglas Scortegagna', img_link = 'https://flic.kr/p/yc1zva' where id = 'sachl';
update attrs_wld set img_author = 'Man Bartlett', img_link = 'https://flic.kr/p/6FSd2s' where id = 'asind';
update attrs_wld set img_author = 'Antony Stanley', img_link = 'https://flic.kr/p/4d4vva' where id = 'namex';
update attrs_wld set img_author = 'Javier Vieras', img_link = 'https://flic.kr/p/e6uh1X' where id = 'euita';
update attrs_wld set img_author = 'Republic of Korea', img_link = 'https://flic.kr/p/dgAPYa' where id = 'askor';
update attrs_wld set img_author = 'Dr Les (Leszek - Leslie) Sachs', img_link = 'https://flic.kr/p/7a1PTJ' where id = 'eubel';
update attrs_wld set img_author = 'Andreas Lehner', img_link = 'https://flic.kr/p/iKRuka' where id = 'saven';
update attrs_wld set img_author = 'Malcolm Browne', img_link = 'https://flic.kr/p/nDDbL7' where id = 'euesp';
update attrs_wld set img_author = 'j.e.mcgowan', img_link = 'https://flic.kr/p/ekMivF' where id = 'eugbr';
update attrs_wld set img_author = 'Mohamod Fasil', img_link = 'https://flic.kr/p/DeVB8V' where id = 'assau';
update attrs_wld set img_author = 'Raphael Labaca Castro', img_link = 'https://flic.kr/p/acYvWV' where id = 'saury';
update attrs_wld set img_author = 'Cesar I. Martins', img_link = 'https://flic.kr/p/ss7zoD' where id = 'asare';
update attrs_wld set img_author = 'Leandro Neumann Ciuffo', img_link = 'https://flic.kr/p/dfsKt4' where id = 'sapry';
update attrs_wld set img_author = 'greg westfall', img_link = 'https://flic.kr/p/cNivey' where id = 'asrus';
update attrs_wld set img_author = 'Rick Ligthelm', img_link = 'https://flic.kr/p/tXdbLC' where id = 'nacan';
update attrs_wld set img_author = 'Gilad Rom', img_link = 'https://flic.kr/p/naGbcx' where id = 'eufra';
update attrs_wld set img_author = 'undeklinable', img_link = 'https://flic.kr/p/px3GEz' where id = 'asidn';
update attrs_wld set img_author = 'Christine McIntosh', img_link = 'https://flic.kr/p/rnYqWz' where id = 'asvnm';
update attrs_wld set img_author = 'Joe Ross', img_link = 'https://flic.kr/p/DkPxX3' where id = 'sacol';
update attrs_wld set img_author = 'Daxis', img_link = 'https://flic.kr/p/Bgygv5' where id = 'ashkg';
update attrs_wld set img_author = 'Ana Paula Hirama', img_link = 'https://flic.kr/p/8PLB9P' where id = 'afegy';
update attrs_wld set img_author = 'Joan Campderrós-i-Canas', img_link = 'https://flic.kr/p/ntvEUr' where id = 'assgp';
update attrs_wld set img_author = 'Kosala Bandara', img_link = 'https://flic.kr/p/hvVmF4' where id = 'euche';
update attrs_wld set img_author = 'Jorge Cancela', img_link = 'https://flic.kr/p/dhRjwv' where id = 'asmys';
update attrs_wld set img_author = 'Sue Cantan', img_link = 'https://flic.kr/p/7EtE7U' where id = 'saper';
update attrs_wld set img_author = 'Guillén Pérez', img_link = 'https://flic.kr/p/qDgRBb' where id = 'astha';
update attrs_wld set img_author = 'dynamosquito', img_link = 'https://flic.kr/p/aieMED' where id = 'asirn';
update attrs_wld set img_author = 'bryan...', img_link = 'https://flic.kr/p/m5PPxT' where id = 'astwn';
update attrs_wld set img_author = 'Jen Morgan', img_link = 'https://flic.kr/p/9LqDww' where id = 'sabol';
update attrs_wld set img_author = 'Ryan Kilpatrick', img_link = 'https://flic.kr/p/bCX3P9' where id = 'afzaf';
update attrs_wld set img_author = 'Andrey', img_link = 'https://flic.kr/p/vaCM6M' where id = 'astur';
update attrs_wld set img_author = 'Omar Faruk.bd', img_link = 'https://flic.kr/p/vBTvvp' where id = 'asbgd';
update attrs_wld set img_author = 'Henry_Marion', img_link = 'https://flic.kr/p/oXYzEA' where id = 'afdza';
update attrs_wld set img_author = 'PortoBay Hotels & Resorts', img_link = 'https://flic.kr/p/dnrXz3' where id = 'euprt';
update attrs_wld set img_author = 'Marc Gerard Del Rosario', img_link = 'https://flic.kr/p/hbNr52' where id = 'asphl';
update attrs_wld set img_author = 'Jeff Attaway', img_link = 'https://flic.kr/p/657rV6' where id = 'afnga';
update attrs_wld set img_author = 'charley1965', img_link = 'https://flic.kr/p/4pVHQQ' where id = 'eunor';
update attrs_wld set img_author = 'MyVacationPages', img_link = 'https://flic.kr/p/dYQs44' where id = 'nalca';
update attrs_wld set img_author = 'Héctor López', img_link = 'https://flic.kr/p/a7pZMd' where id = 'saecu';
update attrs_wld set img_author = 'David Stanley', img_link = 'https://flic.kr/p/wjp1tE' where id = 'afago';
update attrs_wld set img_author = 'Ricardo''s Photography', img_link = 'https://flic.kr/p/aTXHzk' where id = 'nabhs';
update attrs_wld set img_author = 'Andrew Moore', img_link = 'https://flic.kr/p/smGrLQ' where id = 'asomn';
update attrs_wld set img_author = 'Masahiro TAKAGI', img_link = 'https://flic.kr/p/z1kQXJ' where id = 'naant';
update attrs_wld set img_author = 'Genosonic', img_link = 'https://flic.kr/p/38fYjs' where id = 'nadom';
update attrs_wld set img_author = 'Nick Kenrick', img_link = 'https://flic.kr/p/mk7Rxf' where id = 'nacub';
update attrs_wld set img_author = 'Román Emin', img_link = 'https://flic.kr/p/h7uXA4' where id = 'euswe';
update attrs_wld set img_author = 'Lokesh Dhakar', img_link = 'https://flic.kr/p/9aKkwV' where id = 'oc';
update attrs_wld set img_author = 'Michela Simoncini', img_link = 'https://flic.kr/p/qLuakc' where id = 'eupol';
update attrs_wld set img_author = 'SuperCar-RoadTrip.fr', img_link = 'https://flic.kr/p/eUrTG3' where id = 'afmar';
update attrs_wld set img_author = 'Nicolò Bonazzi', img_link = 'https://flic.kr/p/7ioLrZ' where id = 'ocaus';
update attrs_wld set img_author = 'Bob Familiar', img_link = 'https://flic.kr/p/dG8RZw' where id = 'euirl';
update attrs_wld set img_author = 'Bastian Gross', img_link = 'https://flic.kr/p/81mWQT' where id = 'eusvn';
update attrs_wld set img_author = 'David King', img_link = 'https://flic.kr/p/2T3DBh' where id = 'asisr';
update attrs_wld set img_author = 'Jimmy Baikovicius', img_link = 'https://flic.kr/p/dfzuDm' where id = 'asqat';
update attrs_wld set img_author = 'Nelson L.', img_link = 'https://flic.kr/p/o7Bs2j' where id = 'eudnk';
update attrs_wld set img_author = 'Rory', img_link = 'https://flic.kr/p/pCBVXf' where id = 'asbhr';
update attrs_wld set img_author = 'Arian Zwegers', img_link = 'https://flic.kr/p/aGe9AF' where id = 'asirq';
update attrs_wld set img_author = 'LWYang', img_link = 'https://flic.kr/p/h36ioR' where id = 'napan';
update attrs_wld set img_author = 'Dennis Jarvis', img_link = 'https://flic.kr/p/cXfRBw' where id = 'aftun';
update attrs_wld set img_author = 'Wasif Malik', img_link = 'https://flic.kr/p/BzjdDq' where id = 'aspak';
update attrs_wld set img_author = 'Andrés Nieto Porras', img_link = 'https://flic.kr/p/jmFT3q' where id = 'euisl';
update attrs_wld set img_author = 'paolo mutti', img_link = 'https://flic.kr/p/8KKuE5' where id = 'aslbn';
update attrs_wld set img_author = 'Urko Dorronsoro', img_link = 'https://flic.kr/p/keXuh5' where id = 'eufin';
update attrs_wld set img_author = 'Andy Rusch', img_link = 'https://flic.kr/p/9cfNzH' where id = 'nacri';
update attrs_wld set img_author = 'Katina Rogers', img_link = 'https://flic.kr/p/dz5CZF' where id = 'natto';
update attrs_wld set img_author = 'George M. Groutas', img_link = 'https://flic.kr/p/7DE3aK' where id = 'eurou';
update attrs_wld set img_author = 'SuperCar-RoadTrip.fr', img_link = 'https://flic.kr/p/cEqWfq' where id = 'asjor';
update attrs_wld set img_author = 'eutrophication&hypoxia', img_link = 'https://flic.kr/p/7Q4mPv' where id = 'askwt';
update attrs_wld set img_author = 'Daniel Edwins', img_link = 'https://flic.kr/p/8K6FSR' where id = 'euhun';
update attrs_wld set img_author = 'Rodrigo Campos', img_link = 'https://flic.kr/p/9BHdKY' where id = 'nagtm';
update attrs_wld set img_author = 'Gerry & Bonni', img_link = 'https://flic.kr/p/aLgTVv' where id = 'asyem';
update attrs_wld set img_author = 'Georgia National Guard', img_link = 'https://flic.kr/p/eUDPSY' where id = 'asgeo';
update attrs_wld set img_author = 'Francisco Anzola', img_link = 'https://flic.kr/p/6sYHgt' where id = 'afgha';
update attrs_wld set img_author = 'Missuale', img_link = 'https://flic.kr/p/q2EGnF' where id = 'aflby';
update attrs_wld set img_author = 'Hugues', img_link = 'https://flic.kr/p/4kerDz' where id = 'afmrt';
update attrs_wld set img_author = 'দেবর্ষি রায়', img_link = 'https://flic.kr/p/dxUZsD' where id = 'euaut';
update attrs_wld set img_author = 'Harvey Barrison', img_link = 'https://flic.kr/p/jMEFYn' where id = 'napri';
update attrs_wld set img_author = 'Jeff Attaway', img_link = 'https://flic.kr/p/7CkAPP' where id = 'afsen';
update attrs_wld set img_author = 'Erwan Martin', img_link = 'https://flic.kr/p/oScGGZ' where id = 'eubgr';
update attrs_wld set img_author = 'Loris Silvio Zecchinato', img_link = 'https://flic.kr/p/d9kQtS' where id = 'eugrc';
update attrs_wld set img_author = 'Marco Zanferrari', img_link = 'https://flic.kr/p/8q1ECZ' where id = 'aslka';
update attrs_wld set img_author = 'Panoramas', img_link = 'https://flic.kr/p/hN9FEK' where id = 'afben';
update attrs_wld set img_author = 'Diego Brito', img_link = 'https://flic.kr/p/bndgS6' where id = 'naslv';
update attrs_wld set img_author = 'Dennis Jarvis', img_link = 'https://flic.kr/p/4nFktm' where id = 'nahnd';
update attrs_wld set img_author = 'nickelstar', img_link = 'https://flic.kr/p/i1o35p' where id = 'nanic';
update attrs_wld set img_author = 'Sergey Galyonkin', img_link = 'https://flic.kr/p/pUixD4' where id = 'euukr';
update attrs_wld set img_author = 'Forbes Johnston', img_link = 'https://flic.kr/p/b8ia8H' where id = 'afgmb';
update attrs_wld set img_author = 'Peter Mellow', img_link = 'https://pixabay.com/photo-1064876/' where id = 'ocmhl';
update attrs_wld set img_author = 'Ana Raquel S. Hernandes', img_link = 'https://flic.kr/p/dJxWb2' where id = 'afzwe';
update attrs_wld set img_author = 'LoggaWiggler', img_link = 'https://pixabay.com/photo-198685/' where id = 'asuzb';
update attrs_wld set img_author = 'Graeme Churchard', img_link = 'https://flic.kr/p/5sEEcd' where id = 'ascyp';
update attrs_wld set img_author = 'miko_sport', img_link = 'https://pixabay.com/photo-1107931/' where id = 'ocglp';
update attrs_wld set img_author = 'Guimo', img_link = 'https://flic.kr/p/6Js7k3' where id = 'euimn';
update attrs_wld set img_author = 'Русский', img_link = 'https://pixabay.com/photo-741663/' where id = 'askaz';
update attrs_wld set img_author = 'POTIER Jean-Louis', img_link = 'https://flic.kr/p/acm4HA' where id = 'afmli';
update attrs_wld set img_author = 'fabrizio ventrice', img_link = 'https://flic.kr/p/2W3gRa' where id = 'afsyc';
update attrs_wld set img_author = 'Brett Hodnett', img_link = 'https://flic.kr/p/EPmThX' where id = 'nagrd';
update attrs_wld set img_author = 'f. ermert', img_link = 'https://flic.kr/p/xNPVVc' where id = 'nablz';
update attrs_wld set img_author = 'Antonio Fucito', img_link = 'https://flic.kr/p/dPAsSz' where id = 'namtq';
update attrs_wld set img_author = 'Eric Bauer', img_link = 'https://flic.kr/p/q8YtBL' where id = 'afnam';
update attrs_wld set img_author = 'Amber Clay', img_link = 'https://pixabay.com/photo-60808/' where id = 'asafg';
update attrs_wld set img_author = 'Michael Baragwanath', img_link = 'https://pixabay.com/photo-592790/' where id = 'ocncl';
update attrs_wld set img_author = 'yeowatzup', img_link = 'https://flic.kr/p/tCqNC' where id = 'astls';
update attrs_wld set img_author = 'Roberto Faccenda', img_link = 'https://flic.kr/p/buPmFQ' where id = 'naatg';
update attrs_wld set img_author = 'Jake Stimpson', img_link = 'https://flic.kr/p/tX5k3w' where id = 'afuga';
update attrs_wld set img_author = 'Chico Barros', img_link = 'https://pixabay.com/photo-670821/' where id = 'saguf';
update attrs_wld set img_author = 'David Mark', img_link = 'https://pixabay.com/photo-82448/' where id = 'afzmb';
update attrs_wld set img_author = 'Mario Micklisch', img_link = 'https://flic.kr/p/pwexpW' where id = 'afbwa';
update attrs_wld set img_author = 'Wagner T. Cassimiro "Aranha"', img_link = 'https://flic.kr/p/8j93FR' where id = 'askhm';
update attrs_wld set img_author = 'acin355', img_link = 'https://flic.kr/p/dLmdx5' where id = 'natca';
update attrs_wld set img_author = 'James', img_link = 'https://flic.kr/p/bmnVNy' where id = 'euhrv';
update attrs_wld set img_author = 'Ed Brambley', img_link = 'https://flic.kr/p/6uud5Y' where id = 'assyr';
update attrs_wld set img_author = 'Rosino', img_link = 'https://flic.kr/p/6YErnn' where id = 'afmoz';
update attrs_wld set img_author = 'Panoramas', img_link = 'https://flic.kr/p/nqrNMd' where id = 'aftgo';
update attrs_wld set img_author = 'Mark Fischer', img_link = 'https://flic.kr/p/hLZgKr' where id = 'afcmr';
update attrs_wld set img_author = 'MONUSCO Photos', img_link = 'https://flic.kr/p/qQTR8Q' where id = 'afcog';
update attrs_wld set img_author = 'Joan Campderrós-i-Canas', img_link = 'https://flic.kr/p/9gsCsn' where id = 'ocnzl';
update attrs_wld set img_author = 'Ninara', img_link = 'https://flic.kr/p/ttFXLz' where id = 'afken';
update attrs_wld set img_author = 'leigh_householder', img_link = 'https://flic.kr/p/9xpCiJ' where id = 'najam';
update attrs_wld set img_author = 'Adam Gerritsma', img_link = 'https://flic.kr/p/chNWTN' where id = 'nacym';
update attrs_wld set img_author = 'Jurgen', img_link = 'https://flic.kr/p/4BeGyz' where id = 'afgin';
update attrs_wld set img_author = 'harmishhk', img_link = 'https://flic.kr/p/C9DSu2' where id = 'eultu';
update attrs_wld set img_author = 'Maxence', img_link = 'https://flic.kr/p/wu4jcY' where id = 'afciv';
update attrs_wld set img_author = 'Edward Akerboom', img_link = 'https://flic.kr/p/bmrsTX' where id = 'afsle';
update attrs_wld set img_author = 'Julien Harneis', img_link = 'https://flic.kr/p/3RzvPG' where id = 'afcod';
update attrs_wld set img_author = 'Guillén Pérez', img_link = 'https://flic.kr/p/s1fdcC' where id = 'asmmr';
update attrs_wld set img_author = 'Andy R', img_link = 'https://flic.kr/p/566Mzt' where id = 'afmus';
update attrs_wld set img_author = 'David Evers', img_link = 'https://flic.kr/p/7otMe1' where id = 'sasur';
update attrs_wld set img_author = 'Ricardo''s Photography', img_link = 'https://flic.kr/p/bx44im' where id = 'nahti';
update attrs_wld set img_author = 'AMISOM Public Information', img_link = 'https://flic.kr/p/cMaH8S' where id = 'afsom';
update attrs_wld set img_author = 'Rob Hogeslag', img_link = 'https://flic.kr/p/77FKPN' where id = 'eualb';
update attrs_wld set img_author = 'Axel Rouvin', img_link = 'https://flic.kr/p/mfPFx' where id = 'afgab';
update attrs_wld set img_author = 'Ruben Holthuijsen', img_link = 'https://flic.kr/p/gkpdMh' where id = 'eulux';
update attrs_wld set img_author = 'Srdjan Stojiljkovic', img_link = 'https://flic.kr/p/sSeXij' where id = 'eusrb';
update attrs_wld set img_author = 'TausP.', img_link = 'https://flic.kr/p/cZRW4m' where id = 'euest';