update attrs_cbo set img_author = 'Primeiro Ano Jornalismo UEPG', img_link = 'https://flic.kr/p/8XSqZ1' where id = '9144';
update attrs_cbo set img_author = 'Alex Proimos', img_link = 'https://flic.kr/p/bt29wL' where id = '2251';
update attrs_cbo set img_author = 'Glúten Free Alimentos', img_link = 'https://flic.kr/p/dirD1E' where id = '4142';
update attrs_cbo set img_author = 'Antonio E. Da Silva Campos', img_link = 'https://flic.kr/p/5Jg2wE' where id = '1414';
update attrs_cbo set img_author = 'World Bank Photo Collection', img_link = 'https://flic.kr/p/97aGY8' where id = '2313';
update attrs_cbo set img_author = 'Projeto Antenados', img_link = 'https://flic.kr/p/fv3f7W' where id = '7243';
update attrs_cbo set img_author = 'Franklin Dias', img_link = 'https://flic.kr/p/cbwu4j' where id = '6220';
update attrs_cbo set img_author = 'DIRETORIA DE COMUNICAÇÃO', img_link = 'https://flic.kr/p/Bsdoxg' where id = '9922';
update attrs_cbo set img_author = 'wan mohd', img_link = 'https://flic.kr/p/8vUnSh' where id = '5135';
update attrs_cbo set img_author = 'Ingeniørforeningen IDA', img_link = 'https://flic.kr/p/iQizwg' where id = '9113';
update attrs_cbo set img_author = 'Michele Mastroserio', img_link = 'https://flic.kr/p/oPSCq6' where id = '8483';
update attrs_cbo set img_author = 'Stuart Montgomery', img_link = 'https://flic.kr/p/ah7gmA' where id = '5112';
update attrs_cbo set img_author = 'iconicphotoservices', img_link = 'https://flic.kr/p/kCP3kc' where id = '2521';
update attrs_cbo set img_author = 'Alexis Toutain', img_link = 'https://flic.kr/p/aBVfPW' where id = '6410';
update attrs_cbo set img_author = 'Daz Bergman', img_link = 'https://flic.kr/p/8BHGz7' where id = '8621';
update attrs_cbo set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/784LNm' where id = '4122';
update attrs_cbo set img_author = 'Asian Development Bank', img_link = 'https://flic.kr/p/dQTFu1' where id = '3912';
update attrs_cbo set img_author = 'PuzzleMonkey!', img_link = 'https://flic.kr/p/pYaQK3' where id = '7155';
update attrs_cbo set img_author = 'Foto Piratini', img_link = 'https://flic.kr/p/dENJ13' where id = '6221';
update attrs_cbo set img_author = 'UnB Agência', img_link = 'https://flic.kr/p/rty8vf' where id = '2345';
update attrs_cbo set img_author = 'klimkin', img_link = 'https://pixabay.com/photo-995187/' where id = '2394';
update attrs_cbo set img_author = 'Ahmed AB', img_link = 'https://flic.kr/p/7QJfv4' where id = '3514';
update attrs_cbo set img_author = 'Rede Coleguium de Ensino', img_link = 'https://flic.kr/p/amY3Nc' where id = '3341';
update attrs_cbo set img_author = 'robbie paul', img_link = 'https://flic.kr/p/9gtDCf' where id = '7151';
update attrs_cbo set img_author = 'RichardWesner', img_link = 'https://flic.kr/p/F5YqKr' where id = '2523';
update attrs_cbo set img_author = 'PDPics', img_link = 'https://pixabay.com/photo-390319/' where id = '2522';
update attrs_cbo set img_author = 'UnB Agência', img_link = 'https://flic.kr/p/oy9Lke' where id = '3911';
update attrs_cbo set img_author = 'Adriano Nishimura', img_link = 'https://flic.kr/p/3G3fah' where id = '7311';
update attrs_cbo set img_author = 'jarmoluk', img_link = 'https://pixabay.com/photo-1080554/' where id = '7156';
update attrs_cbo set img_author = 'WEG EQUIPAMENTOS ELÉTRICOS S.A.', img_link = 'https://flic.kr/p/6GYqap' where id = '3132';
update attrs_cbo set img_author = 'Tomoir III', img_link = 'https://flic.kr/p/bSSZ9R' where id = '4222';
update attrs_cbo set img_author = 'iKumpunen', img_link = 'https://pixabay.com/photo-748152/' where id = '7822';
update attrs_cbo set img_author = 'CNI Confederação Nacional da Indústria', img_link = 'https://flic.kr/p/oNwwLz' where id = '7244';
update attrs_cbo set img_author = 'Life-Of-Pix', img_link = 'https://pixabay.com/photo-569126/' where id = '7102';
update attrs_cbo set img_author = 'embausurfacomodacoes', img_link = 'https://flic.kr/p/8DvgNA' where id = '3522';
update attrs_cbo set img_author = 'Lente Quente', img_link = 'https://flic.kr/p/EEVUd9' where id = '5191';
update attrs_cbo set img_author = 'Lara Borges', img_link = 'https://flic.kr/p/8FitEi' where id = '5199';
update attrs_cbo set img_author = 'Rede Coleguium de Ensino', img_link = 'https://flic.kr/p/an1hzU' where id = '2311';
update attrs_cbo set img_author = 'SEBRAE-SP', img_link = 'https://flic.kr/p/qx1et9' where id = '5201';
update attrs_cbo set img_author = 'Aloisio Mauricio/T70! Fotografia Digital A imagem que preza a sua imagem.', img_link = 'https://flic.kr/p/6p4qED' where id = '5172';
update attrs_cbo set img_author = 'Colégio Raízes', img_link = 'https://flic.kr/p/hKsie7' where id = '3331';
update attrs_cbo set img_author = 'Tatiana Fortes', img_link = 'https://flic.kr/p/oBS46L' where id = '6231';
update attrs_cbo set img_author = 'Potira Souto', img_link = 'https://flic.kr/p/ekrHQE' where id = '9511';
update attrs_cbo set img_author = 'Jorge', img_link = 'https://flic.kr/p/5L1Yi9' where id = '2234';
update attrs_cbo set img_author = 'Diogo Abreu', img_link = 'https://flic.kr/p/ao5Rq4' where id = '7241';
update attrs_cbo set img_author = 'Mario Riorda', img_link = 'https://flic.kr/p/moGWBZ' where id = '4213';
update attrs_cbo set img_author = 'Nilani Goettems', img_link = 'https://flic.kr/p/6q8CWu' where id = '7631';
update attrs_cbo set img_author = 'Tribunal Regional do Trabalho da 19ª Região TRT/AL', img_link = 'https://flic.kr/p/xNF5b1' where id = '7321';
update attrs_cbo set img_author = 'Portal de Jornalismo ESPM - SP', img_link = 'https://flic.kr/p/oU8WFf' where id = '3131';
update attrs_cbo set img_author = 'Lenovski', img_link = 'https://flic.kr/p/vDTkgk' where id = '5133';
update attrs_cbo set img_author = 'Petit Miracle', img_link = 'https://flic.kr/p/q51NTF' where id = '4201';
update attrs_cbo set img_author = 'Serluz', img_link = 'https://flic.kr/p/9Nr4o1' where id = '7242';
update attrs_cbo set img_author = 'Alexandra Proença', img_link = 'https://flic.kr/p/fZj6ZP' where id = '7711';
update attrs_cbo set img_author = 'CNI Confederação Nacional da Indústria', img_link = 'https://flic.kr/p/oMnoRx' where id = '3516';
update attrs_cbo set img_author = 'Lente Quente', img_link = 'https://flic.kr/p/a3set3' where id = '5163';
update attrs_cbo set img_author = 'Força Aérea Brasileira (Brazilian Air Force)', img_link = 'https://flic.kr/p/qx1kX1' where id = '5152';
update attrs_cbo set img_author = 'Nicola Iannuzzi', img_link = 'https://flic.kr/p/dWAwPG' where id = '7166';
update attrs_cbo set img_author = 'pashminu', img_link = 'https://pixabay.com/photo-852921/' where id = '8117';
update attrs_cbo set img_author = 'Glênio Freitas Júnior', img_link = 'https://flic.kr/p/9cjkbp' where id = '7233';
update attrs_cbo set img_author = 'CNI Confederação Nacional da Indústria', img_link = 'https://flic.kr/p/dtupin' where id = '7640';
update attrs_cbo set img_author = 'Dirceu S. Oliveira', img_link = 'https://flic.kr/p/h6JbmV' where id = '4152';
update attrs_cbo set img_author = 'Argeu Bernardo de Andrade Montador de Móveis em Recife', img_link = 'https://flic.kr/p/cxAQiL' where id = '7741';
update attrs_cbo set img_author = 'Prefeitura de Balneário Piçarras', img_link = 'https://flic.kr/p/nZ9F1M' where id = '3172';
update attrs_cbo set img_author = 'Teleperformance Group', img_link = 'https://flic.kr/p/dj1jMM' where id = '4102';
update attrs_cbo set img_author = 'Del Rodrigues', img_link = 'https://flic.kr/p/bdg95F' where id = '3224';
update attrs_cbo set img_author = 'Science Without Borders UoW', img_link = 'https://flic.kr/p/q8PE7S' where id = '2142';
update attrs_cbo set img_author = 'Jeso Carneiro', img_link = 'https://flic.kr/p/xLMXRE' where id = '2410';
update attrs_cbo set img_author = 'Italberto Figueira Dantas', img_link = 'https://flic.kr/p/qBmGTM' where id = '3515';
update attrs_cbo set img_author = 'AEMTG', img_link = 'https://flic.kr/p/8dRxpX' where id = '3542';
update attrs_cbo set img_author = 'Christyam de Lima', img_link = 'https://flic.kr/p/9YBKPJ' where id = '7153';
update attrs_cbo set img_author = 'Selma Kroehne', img_link = 'https://flic.kr/p/afdEL9' where id = '8414';
update attrs_cbo set img_author = 'jakza - Jaque Zattera', img_link = 'https://flic.kr/p/oxFM9y' where id = '6225';
update attrs_cbo set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593333/' where id = '2524';
update attrs_cbo set img_author = 'MarkoLovric', img_link = 'https://pixabay.com/photo-1000618/' where id = '1412';
update attrs_cbo set img_author = 'HotelPontaVerde', img_link = 'https://flic.kr/p/bVh8hw' where id = '3513';
update attrs_cbo set img_author = 'Agência Brasília', img_link = 'https://flic.kr/p/Bvpk3H' where id = '3141';
update attrs_cbo set img_author = 'ian gardiner', img_link = 'https://flic.kr/p/9GvsUT' where id = '2532';
update attrs_cbo set img_author = 'UnB Agência', img_link = 'https://flic.kr/p/oy7W9o' where id = '8131';
update attrs_cbo set img_author = 'UnB Agência', img_link = 'https://flic.kr/p/FMZBcx' where id = '2332';
update attrs_cbo set img_author = 'Ministério do Desenvolvimento Social e Combate à Fome', img_link = 'https://flic.kr/p/pQn6LD' where id = '2516';
update attrs_cbo set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593372/' where id = '3171';
update attrs_cbo set img_author = 'germán garibaldi', img_link = 'https://flic.kr/p/4TzEnP' where id = '1415';
update attrs_cbo set img_author = 'Fábio H. Mendes', img_link = 'https://flic.kr/p/CVjuXC' where id = '5161';
update attrs_cbo set img_author = 'MZ', img_link = 'https://flic.kr/p/jJ1xAd' where id = '1231';
update attrs_cbo set img_author = 'MZ', img_link = 'https://flic.kr/p/jHZdqR' where id = '2525';
update attrs_cbo set img_author = 'Arian Giacomet', img_link = 'https://flic.kr/p/7ZUMXZ' where id = '7630';
update attrs_cbo set img_author = 'ricardo zaragoza', img_link = 'https://flic.kr/p/64WHcD' where id = '2232';
update attrs_cbo set img_author = 'Ingeniørforeningen IDA', img_link = 'https://flic.kr/p/iK7AbA' where id = '3421';
update attrs_cbo set img_author = 'spallafisioterapia', img_link = 'https://flic.kr/p/825mE6' where id = '3241';
update attrs_cbo set img_author = 'CNI Confederação Nacional da Indústria', img_link = 'https://flic.kr/p/m2MQ6D' where id = '7641';
update attrs_cbo set img_author = 'JonKline', img_link = 'https://pixabay.com/photo-673559/' where id = '8214';
update attrs_cbo set img_author = 'Carol Chmi', img_link = 'https://flic.kr/p/aZGXtX' where id = '7662';
update attrs_cbo set img_author = 'POLÍCIA CIVIL MT', img_link = 'https://flic.kr/p/oKrzGz' where id = '6321';
update attrs_cbo set img_author = 'Universidad CEU Cardenal Herrera', img_link = 'https://flic.kr/p/bzNGCM' where id = '6233';
update attrs_cbo set img_author = 'Uniformes Premier', img_link = 'https://flic.kr/p/7UMau4' where id = '7633';
update attrs_cbo set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593312/' where id = '4121';
update attrs_cbo set img_author = 'Portal PBH', img_link = 'https://flic.kr/p/a1Lzua' where id = '5162';
update attrs_cbo set img_author = 'Agencia ID', img_link = 'https://flic.kr/p/p7CrPg' where id = '2515';
update attrs_cbo set img_author = 'blogespmmais', img_link = 'https://flic.kr/p/dvnQRm' where id = '2346';
update attrs_cbo set img_author = 'pashminu', img_link = 'https://pixabay.com/photo-827301/' where id = '3121';
update attrs_cbo set img_author = 'andrea lima de menezes', img_link = 'https://flic.kr/p/8ReRFr' where id = '3133';
update attrs_cbo set img_author = 'Sistema FIEB', img_link = 'https://flic.kr/p/kwNmof' where id = '7245';
update attrs_cbo set img_author = 'Prefeitura de Sete Lagoas', img_link = 'https://flic.kr/p/8WfRzz' where id = '3714';
update attrs_cbo set img_author = 'Paulo Pampolin', img_link = 'https://flic.kr/p/hDNMZj' where id = '1422';
update attrs_cbo set img_author = 'Wesley Soalheiro de souza', img_link = 'https://flic.kr/p/cWV88G' where id = '3518';
update attrs_cbo set img_author = 'Talento Profissional', img_link = 'https://flic.kr/p/5CNFFm' where id = '1313';
update attrs_cbo set img_author = 'Colégio Raízes', img_link = 'https://flic.kr/p/rvrp2d' where id = '2241';
update attrs_cbo set img_author = 'Mario Cesar Bucci', img_link = 'https://flic.kr/p/ruyknr' where id = '8281';
update attrs_cbo set img_author = 'Mills Baker', img_link = 'https://flic.kr/p/6vivZy' where id = '5';
update attrs_cbo set img_author = 'dentaprime', img_link = 'https://flic.kr/p/r4zuhn' where id = '3';
update attrs_cbo set img_author = 'skeeze', img_link = 'https://pixabay.com/photo-857128/' where id = '9';
update attrs_cbo set img_author = 'Alper Çuğun', img_link = 'https://flic.kr/p/7pmryX' where id = '4';
update attrs_cbo set img_author = 'skeeze', img_link = 'https://pixabay.com/photo-659884/' where id = '7';
update attrs_cbo set img_author = 'Irekia', img_link = 'https://flic.kr/p/83iBHF' where id = '2';
update attrs_cbo set img_author = 'Bonner Springs Library', img_link = 'https://flic.kr/p/6GG7ke' where id = '4110';
update attrs_cbo set img_author = 'UliSchu', img_link = 'https://pixabay.com/photo-1205055/' where id = '5211';
update attrs_cbo set img_author = 'epp group', img_link = 'https://flic.kr/p/da6qkx' where id = '1';
update attrs_cbo set img_author = 'bogitw', img_link = 'https://pixabay.com/photo-817732/' where id = '5143';
update attrs_cbo set img_author = 'chaingam990', img_link = 'https://pixabay.com/photo-722863/' where id = '8';
update attrs_cbo set img_author = 'hpgruesen', img_link = 'https://pixabay.com/photo-1359862/' where id = '6';
update attrs_cbo set img_author = 'janeb13', img_link = 'https://pixabay.com/photo-1181063/' where id = '7825';
update attrs_cbo set img_author = 'falco', img_link = 'https://pixabay.com/photo-1137993/' where id = '7842';
update attrs_cbo set img_author = 'Nick Harris', img_link = 'https://flic.kr/p/mPWKg2' where id = '5174';
update attrs_cbo set img_author = 'Igor Schutz', img_link = 'https://flic.kr/p/ej94rB' where id = '5174';
update attrs_cbo set img_author = 'Lars Plougmann', img_link = 'https://flic.kr/p/rkfJsK' where id = '5142';
update attrs_cbo set img_author = 'skeeze', img_link = 'https://pixabay.com/photo-857128/' where id = '7170';
update attrs_cbo set img_author = 'Irekia', img_link = 'https://flic.kr/p/83iBHF' where id = '3222';
update attrs_cbo set img_author = 'airunique', img_link = 'https://pixabay.com/photo-401519/' where id = '2312';
update attrs_cbo set img_author = 'La Citta Vita', img_link = 'https://flic.kr/p/9XWsaX' where id = '5134';
update attrs_cbo set img_author = 'followtheseinstructions', img_link = 'https://flic.kr/p/9gGswk' where id = '5173';
update attrs_cbo set img_author = 'epp group', img_link = 'https://flic.kr/p/da6qkx' where id = '1114';
update attrs_cbo set img_author = 'US Department of Education', img_link = 'https://flic.kr/p/fCAUxh' where id = '3312';
update attrs_cbo set img_author = 'Daniel Lobo', img_link = 'https://flic.kr/p/2inDCi' where id = '4221';
update attrs_cbo set img_author = 'Assembleia Legislativa do Paraná', img_link = 'https://flic.kr/p/a88u55' where id = '4141';
update attrs_cbo set img_author = 'Unsplash', img_link = 'https://pixabay.com/photo-1209161/' where id = '5132';
update attrs_cbo set img_author = 'Sunset Removals', img_link = 'https://flic.kr/p/pJLFhq' where id = '7832';
update attrs_cbo set img_author = 'Marcelo Braga', img_link = 'https://flic.kr/p/81eE95' where id = '7823';
update attrs_cbo set img_author = 'Rachel Docherty', img_link = 'https://flic.kr/p/b8vEYT' where id = '7152';
update attrs_cbo set img_author = 'News Oresund', img_link = 'https://flic.kr/p/e5D5jr' where id = '4223';
update attrs_cbo set img_author = 'Sebastian Alvarez', img_link = 'https://flic.kr/p/bGpo3R' where id = '2124';
update attrs_cbo set img_author = 'Assembleia Legislativa do Paraná', img_link = 'https://flic.kr/p/a88u55' where id = '7841';
update attrs_cbo set img_author = 'Irekia', img_link = 'https://flic.kr/p/83iBHF' where id = '2235';
update attrs_cbo set img_author = 'skeeze', img_link = 'https://pixabay.com/photo-659884/' where id = '7212';
update attrs_cbo set img_author = 'Bonner Springs Library', img_link = 'https://flic.kr/p/6GG7ke' where id = '4131';
update attrs_cbo set img_author = 'US Department of Education', img_link = 'https://flic.kr/p/fCAUxh' where id = '2321';
update attrs_cbo set img_author = 'Vodafone Medien', img_link = 'https://flic.kr/p/vbcj7A' where id = '4101';
update attrs_cbo set img_author = 'Vodafone Medien', img_link = 'https://flic.kr/p/vbcj7A' where id = '1421';
update attrs_cbo set img_author = 'Vodafone Medien', img_link = 'https://flic.kr/p/vbcj7A' where id = '1423';
update attrs_cbo set img_author = 'Vodafone Medien', img_link = 'https://flic.kr/p/vbcj7A' where id = '3541';
update attrs_cbo set img_author = 'Danilo Arenas Ireijo', img_link = 'https://flic.kr/p/9QeFAZ' where id = '8485';
update attrs_cbo set img_author = 'Vodafone Medien', img_link = 'https://flic.kr/p/vbcj7A' where id = '4132';
update attrs_cbo set img_author = '422737', img_link = 'https://pixabay.com/photo-1174294/' where id = '7824';
update attrs_cbo set img_author = 'hpgruesen', img_link = 'https://pixabay.com/photo-1359862/' where id = '6210';
update attrs_cbo set img_author = 'Gregoire Fossemalle', img_link = 'https://flic.kr/p/8kgTv7' where id = '5141';
update attrs_cbo set img_author = 'Agencia CNT de Noticias', img_link = 'https://flic.kr/p/8VU62e' where id = '5151';
update attrs_cbo set img_author = 'João Paulo Corrêa de Carvalho', img_link = 'https://flic.kr/p/6jjSQ8' where id = '7632';
update attrs_cbo set img_author = 'Prefeitura de Sete Lagoas', img_link = 'https://flic.kr/p/8gBPZP' where id = '3311';