UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Tree Map is a descriptive visualization which allows visualizing participation, in percentage terms, of the different variables available in DataViva. For example, this visualization allows analyzing the importance of a product in the exports of a location. Tree Maps are built with blocks that are proportional to the participation of selected categories in total, and grouped by colors representing the major groups for each variable (or another color coding selected by the color filter).</p>
<p>The logic of the Tree Map is the same used in a pie chart or other visual representation of distribution. The use of squares grouped by major groups in order of importance allows a quick view of items with greater participation in the respective large group, in which it is contained, enabling a fast and simple analysis of the percentage of participation.</p>
<p>One of the visualizations, for instance, shows the participation of each of the products in Minas Gerais export basket, revealing quickly and easily the significant participation of the product Iron Ore in the exports of the state. Several other views are possible, using the variables available in the platform such as economic activities, occupations, localities and intersections between these variables.</p>
<p><a href="/en/build_graph/secex/4mg/all/all?view=Imports/Exports&graph=tree_map" target="_blank" class="btn btn-success" title="Tree Map"><i class="dv-graph-tree_map m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>Tree Map &eacute; um aplicativo descritivo que permite visualizar a participa&ccedil;&atilde;o, em termos percentuais, das diversas vari&aacute;veis dispon&iacute;veis no DataViva. Esta visualiza&ccedil;&atilde;o possibilita analisar a import&acirc;ncia de um produto na pauta de exporta&ccedil;&otilde;es de uma localidade, por exemplo. O gr&aacute;fico do Tree Map &eacute; constru&iacute;do com blocos proporcionais &agrave; participa&ccedil;&atilde;o das categorias selecionadas no total, agrupadas ainda por cores que representam os grandes grupos para cada vari&aacute;vel.</p>
<p>A l&oacute;gica do Tree Map &eacute; a mesma utilizada em um gr&aacute;fico de pizza ou outra forma de representa&ccedil;&atilde;o visual de distribui&ccedil;&atilde;o da participa&ccedil;&atilde;o de itens no somat&oacute;rio total. A utiliza&ccedil;&atilde;o de blocos agrupados por grandes grupos e em ordem de import&acirc;ncia permite uma visualiza&ccedil;&atilde;o r&aacute;pida dos itens com maior participa&ccedil;&atilde;o e em qual grande grupo ele est&aacute; contido, possibilitando uma an&aacute;lise simples e r&aacute;pida dos percentuais de participa&ccedil;&atilde;o.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, mostra a participa&ccedil;&atilde;o de cada um dos produtos nas exporta&ccedil;&otilde;es de Minas Gerais, revelando com clareza a participa&ccedil;&atilde;o significativa do produto Min&eacute;rio de Ferro nas exporta&ccedil;&otilde;es do estado. V&aacute;rias outras perspectivas s&atilde;o poss&iacute;veis por meio dessa visualiza&ccedil;&atilde;o, utilizando as vari&aacute;veis &#8203;&#8203;dispon&iacute;veis na plataforma como atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es, localidades, al&eacute;m da interse&ccedil;&atilde;o entre essas vari&aacute;veis.</p>
<p><a href="/pt/build_graph/secex/4mg/all/all?view=Imports/Exports&graph=tree_map" target="_blank" class="btn btn-success" title="Tree Map"><i class="dv-graph-tree_map m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Tree Map'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Stacked visualization allows analyzing the growth of a variable over time. Built as an area chart in which the height of each line represents its share in total or gross, this view follows the same color pattern of the other visualizations, facilitating the identification of large groups to which each item belongs. Therefore, this visualization facilitates an understanding of the growth patterns and trends of any of the variables available in DataViva.</p>
<p>The purpose of this visualization is to allow the visualization of the data in a time series, revealing product, economic activities, occupations or localities with greater participation over time and its history of growth or decrease, either in gross or percentage.</p>
<p>One of the visualizations, for instance, is for economic activities of Minas Gerais, revealing the overall growth of the state economy and which sectors had the greatest contribution to this growth since 2002. Like the other visualizations, you can modify the data displayed for any of the basic variables available in DataViva (products, activities, occupations) and their intersections with localities all over Brazil at different levels (regions, states, mesoregions, microregions and municipalities).</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=stacked" target="_blank" class="btn btn-success" title="Stacked"><i class="dv-graph-stacked m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o Evolu&ccedil;&atilde;o permite analisar o crescimento da participa&ccedil;&atilde;o de uma vari&aacute;vel ao longo do tempo. Constru&iacute;da como um gr&aacute;fico de &aacute;rea, no qual a altura de cada linha representa sua participa&ccedil;&atilde;o no total ou seu valor bruto, esta visualiza&ccedil;&atilde;o segue o mesmo padr&atilde;o de cores dos outros aplicativos, facilitando a identifica&ccedil;&atilde;o dos grandes grupos aos quais cada item pertence. Desta forma, este aplicativo facilita a compreens&atilde;o dos padr&otilde;es e tend&ecirc;ncias de crescimento de qualquer uma das vari&aacute;veis dispon&iacute;veis no DataViva.</p>
<p>O objetivo do aplicativo Evolu&ccedil;&atilde;o &eacute; permitir a visualiza&ccedil;&atilde;o dos dados em uma s&eacute;rie hist&oacute;rica, revelando produtos, atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es ou localidades com maior participa&ccedil;&atilde;o ao longo do tempo e seu hist&oacute;rico de crescimento ou redu&ccedil;&atilde;o, seja em valores brutos ou percentuais.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, permite avaliar permite avaliar o crescimento total do mercado de trabalho no estado de Minas Gerais e quais os grupos de ocupa&ccedil;&atilde;o tiveram maior contribui&ccedil;&atilde;o neste crescimento, desde 2002. Assim como outras visualiza&ccedil;&otilde;es, &eacute; poss&iacute;vel modificar os dados exibidos para qualquer uma das vari&aacute;veis &#8203;&#8203;b&aacute;sicas dispon&iacute;veis no DataViva (produtos, atividades, ocupa&ccedil;&otilde;es) e seus cruzamentos com as localidades de todo o Brasil em diferentes n&iacute;veis de agrega&ccedil;&atilde;o (regi&atilde;oes, estados, mesorregi&otilde;es, microrregi&otilde;es e munic&iacute;pios).</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=stacked" target="_blank" class="btn btn-success" title="Stacked"><i class="dv-graph-stacked m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Stacked'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Geo Map is a descriptive geographical visualization that enables an analysis of the spatial distribution of the variables available in DataViva. Using a heat scale, it shows the municipalities with the largest (in red) and lowest (blue) values, and allows navigation both to zoom in and out, as to see more information about a selected municipality. This visualization aims to reveal the geographic distribution of the data.</p>
<p>One of the visualizations, for example, shows the economic activities in Minas Gerais by municipality, showing its concentration in the Metropolitan Region of Belo Horizonte. As in other visualizations, you can change the visualization to the desired variable with the filters.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=geo_map" target="_blank" class="btn btn-success" title="Geo Map"><i class="dv-graph-geo_map m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O Mapa &eacute; uma visualiza&ccedil;&atilde;o descritiva geogr&aacute;fica que possibilita uma an&aacute;lise da distribui&ccedil;&atilde;o espacial das vari&aacute;veis dispon&iacute;veis no DataViva. A partir de uma escala de calor, s&atilde;o mostrados os munic&iacute;pios com maiores valores (em vermelho) e menores valores (em azul), permite a navega&ccedil;&atilde;o de aproxima&ccedil;&atilde;o (zoom in) e afastamento (zoom out) para exibição de maiores informa&ccedil;&otilde;es sobre o munic&iacute;pio selecionado. Este aplicativo tem como objetivo revelar a distribui&ccedil;&atilde;o geogr&aacute;fica dos dados.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, exibe as atividades econ&ocirc;micas em Minas Gerais por munic&iacute;pio, evidenciando sua concentra&ccedil;&atilde;o na Regi&atilde;o Metropolitana de Belo Horizonte. Assim como nas outras visualizações, &eacute; poss&iacute;vel alterar a perspectiva de acordo com a vari&aacute;vel desejada.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=geo_map" target="_blank" class="btn btn-success" title="Geo Map"><i class="dv-graph-geo_map m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Geo Map'




