INSERT INTO attrs_university (id,name_en,desc_en,keywords_en,name_pt,desc_pt,keywords_pt,gender_pt,plural_pt,article_pt,color,id_old,school_type_id,school_type_pt,school_type_en) VALUES
('12136','Faculdade De Tecnologia Do Rio De Janeiro',NULL,NULL,'Faculdade De Tecnologia Do Rio De Janeiro',NULL,NULL,NULL,1,0,'#9edae5',12136,'T','Privada sem fins lucrativos','Non-profit Private'),
('12791','Faculdade Anhanguera De Pindamonhangaba',NULL,NULL,'Faculdade Anhanguera De Pindamonhangaba',NULL,NULL,NULL,1,0,'#2f2f6d',12791,'S','Privada com fins lucrativos','For-profit Private'),
('13784','Faculdade Do Planalto Central',NULL,NULL,'Faculdade Do Planalto Central',NULL,NULL,NULL,1,0,'#2f2f6d',13784,'S','Privada com fins lucrativos','For-profit Private'),
('13792','Instituição De Ensino Superior De Cacoal',NULL,NULL,'Instituição De Ensino Superior De Cacoal',NULL,NULL,NULL,1,0,'#2f2f6d',13792,'S','Privada com fins lucrativos','For-profit Private'),
('14878','Trevisan Escola Superior De Negócios',NULL,NULL,'Trevisan Escola Superior De Negócios',NULL,NULL,NULL,1,0,'#2f2f6d',14878,'S','Privada com fins lucrativos','For-profit Private'),
('14927','Faculdade São Gabriel Da Palha',NULL,NULL,'Faculdade São Gabriel Da Palha',NULL,NULL,NULL,1,0,'#2f2f6d',14927,'S','Privada com fins lucrativos','For-profit Private'),
('14961','Faculdade De Tecnologia Em Saúde - Iahcs',NULL,NULL,'Faculdade De Tecnologia Em Saúde - Iahcs',NULL,NULL,NULL,1,0,'#9edae5',14961,'T','Privada sem fins lucrativos','Non-profit Private'),
('14969','Faculdade De Tecnologia Em Saúde',NULL,NULL,'Faculdade De Tecnologia Em Saúde',NULL,NULL,NULL,1,0,'#2f2f6d',14969,'S','Privada com fins lucrativos','For-profit Private'),
('15133','Faculdade Jardins',NULL,NULL,'Faculdade Jardins',NULL,NULL,NULL,1,0,'#2f2f6d',15133,'S','Privada com fins lucrativos','For-profit Private'),
('15173','Faculdade De Jaraguá',NULL,NULL,'Faculdade De Jaraguá',NULL,NULL,NULL,1,0,'#2f2f6d',15173,'S','Privada com fins lucrativos','For-profit Private'),
('15272','Faculdade De Tecnologia, Educação Superior E Profissional',NULL,NULL,'Faculdade De Tecnologia, Educação Superior E Profissional',NULL,NULL,NULL,1,0,'#2f2f6d',15272,'S','Privada com fins lucrativos','For-profit Private'),
('15501','Faculdade De Tecnologia Senai Roberto Simonsen',NULL,NULL,'Faculdade De Tecnologia Senai Roberto Simonsen',NULL,NULL,NULL,1,0,'#9edae5',15501,'T','Privada sem fins lucrativos','Non-profit Private'),
('15504','Faculdade Irecê',NULL,NULL,'Faculdade Irecê',NULL,NULL,NULL,1,0,'#2f2f6d',15504,'S','Privada com fins lucrativos','For-profit Private'),
('15518','Facudade De Morrinhos',NULL,NULL,'Facudade De Morrinhos',NULL,NULL,NULL,1,0,'#2f2f6d',15518,'S','Privada com fins lucrativos','For-profit Private'),
('15521','Faculdade Católica De São José Dos Campos',NULL,NULL,'Faculdade Católica De São José Dos Campos',NULL,NULL,NULL,1,0,'#9edae5',15521,'T','Privada sem fins lucrativos','Non-profit Private'),
('15777','Faculdade Sudoeste Paulista-Itapetininga',NULL,NULL,'Faculdade Sudoeste Paulista-Itapetininga',NULL,NULL,NULL,1,0,'#2f2f6d',15777,'S','Privada com fins lucrativos','For-profit Private'),
('15833','Faculdade 2001',NULL,NULL,'Faculdade 2001',NULL,NULL,NULL,1,0,'#2f2f6d',15833,'S','Privada com fins lucrativos','For-profit Private'),
('15839','Faculdade Motiva',NULL,NULL,'Faculdade Motiva',NULL,NULL,NULL,1,0,'#2f2f6d',15839,'S','Privada com fins lucrativos','For-profit Private'),
('15859','Faculdade Católica Paulista',NULL,NULL,'Faculdade Católica Paulista',NULL,NULL,NULL,1,0,'#9edae5',15859,'T','Privada sem fins lucrativos','Non-profit Private'),
('15873','Faculdade Itaquá',NULL,NULL,'Faculdade Itaquá',NULL,NULL,NULL,1,0,'#2f2f6d',15873,'S','Privada com fins lucrativos','For-profit Private'),
('16037','Instituto Superior De Ciencias Policiais',NULL,NULL,'Instituto Superior De Ciencias Policiais',NULL,NULL,NULL,1,0,'#009b3a',16037,'Q','Pública Estadual','Public State'),
('16194','Faculdade Gran Tietê',NULL,NULL,'Faculdade Gran Tietê',NULL,NULL,NULL,1,0,'#2f2f6d',16194,'S','Privada com fins lucrativos','For-profit Private'),
('16525','Faculdade Duarte Coelho',NULL,NULL,'Faculdade Duarte Coelho',NULL,NULL,NULL,1,0,'#2f2f6d',16525,'S','Privada com fins lucrativos','For-profit Private'),
('16864','Faculdade Cultura Inglesa',NULL,NULL,'Faculdade Cultura Inglesa',NULL,NULL,NULL,1,0,'#9edae5',16864,'T','Privada sem fins lucrativos','Non-profit Private'),
('16898','Faculdade De Educação E Tecnologia Da Amazônia',NULL,NULL,'Faculdade De Educação E Tecnologia Da Amazônia',NULL,NULL,NULL,1,0,'#2f2f6d',16898,'S','Privada com fins lucrativos','For-profit Private'),
('16943','Faculdade Talles De Mileto',NULL,NULL,'Faculdade Talles De Mileto',NULL,NULL,NULL,1,0,'#2f2f6d',16943,'S','Privada com fins lucrativos','For-profit Private'),
('16967','Faculdade Senai Rio',NULL,NULL,'Faculdade Senai Rio',NULL,NULL,NULL,1,0,'#9edae5',16967,'T','Privada sem fins lucrativos','Non-profit Private'),
('17200','Faculdade Brasileira De Tributação',NULL,NULL,'Faculdade Brasileira De Tributação',NULL,NULL,NULL,1,0,'#2f2f6d',17200,'S','Privada com fins lucrativos','For-profit Private'),
('17288','Faculdade Teológica Betânia',NULL,NULL,'Faculdade Teológica Betânia',NULL,NULL,NULL,1,0,'#9edae5',17288,'T','Privada sem fins lucrativos','Non-profit Private'),
('17401','Faculdade De Tecnologia Cna',NULL,NULL,'Faculdade De Tecnologia Cna',NULL,NULL,NULL,1,0,'#9edae5',17401,'T','Privada sem fins lucrativos','Non-profit Private'),
('18492','Universidade Estadual Do Paraná',NULL,NULL,'Universidade Estadual Do Paraná',NULL,NULL,NULL,1,0,'#009b3a',18492,'Q','Pública Estadual','Public State'),
('18812','Universidade Federal Do Sul Da Bahia',NULL,NULL,'Universidade Federal Do Sul Da Bahia',NULL,NULL,NULL,1,0,'#105b10',18812,'P','Pública Federal','Public Federal'),
('19337','Faculdade Para O Desenvolvimento Sustentável Do Nordeste',NULL,NULL,'Faculdade Para O Desenvolvimento Sustentável Do Nordeste',NULL,NULL,NULL,1,0,'#2f2f6d',19337,'S','Privada com fins lucrativos','For-profit Private'),
('19500','Faculdade De Tecnologia De São Carlos',NULL,NULL,'Faculdade De Tecnologia De São Carlos',NULL,NULL,NULL,1,0,'#009b3a',19500,'Q','Pública Estadual','Public State'),
('19501','Faculdade De Tecnologia Sebrae',NULL,NULL,'Faculdade De Tecnologia Sebrae',NULL,NULL,NULL,1,0,'#009b3a',19501,'Q','Pública Estadual','Public State'),
('19512','Instituto Master De Ensino Presidente Antônio Carlos',NULL,NULL,'Instituto Master De Ensino Presidente Antônio Carlos',NULL,NULL,NULL,1,0,'#2f2f6d',19512,'S','Privada com fins lucrativos','For-profit Private'),
('19588','Faculdade De Educação Tecnológica Do Estado Do Rio De Janeiro',NULL,NULL,'Faculdade De Educação Tecnológica Do Estado Do Rio De Janeiro',NULL,NULL,NULL,1,0,'#009b3a',19588,'Q','Pública Estadual','Public State'),
('19739','Faculdade De Tecnologia De Campinas',NULL,NULL,'Faculdade De Tecnologia De Campinas',NULL,NULL,NULL,1,0,'#009b3a',19739,'Q','Pública Estadual','Public State'),
('19862','Faculdade De Tecnologia De Bebedouro',NULL,NULL,'Faculdade De Tecnologia De Bebedouro',NULL,NULL,NULL,1,0,'#009b3a',19862,'Q','Pública Estadual','Public State'),
('19863','Faculdade De Tecnologia De Assis',NULL,NULL,'Faculdade De Tecnologia De Assis',NULL,NULL,NULL,1,0,'#009b3a',19863,'Q','Pública Estadual','Public State');