UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Tree Map is a descriptive visualization which allows visualizing participation, in percentage terms, of the different variables available in DataViva. For example, this visualization allows analyzing the importance of a product in the exports of a location. Tree Maps are built with blocks that are proportional to the participation of selected categories in total, and grouped by colors representing the major groups for each variable (or another color coding selected by the color filter).</p>
<p>The logic of the Tree Map is the same used in a pie chart or other visual representation of distribution. The use of squares grouped by major groups in order of importance allows a quick view of items with greater participation in the respective large group, in which it is contained, enabling a fast and simple analysis of the percentage of participation.</p>
<p>One of the visualizations, for instance, shows the participation of each of the products in Minas Gerais export basket, revealing quickly and easily the significant participation of the product Iron Ore in the exports of the state. Several other views are possible, using the variables available in the platform such as economic activities, occupations, localities and intersections between these variables.</p>
<p><a href="/en/build_graph/secex/4mg/all/all?view=Imports/Exports&graph=tree_map" target="_blank" class="btn btn-success" title="Tree Map"><i class="dv-graph-tree_map m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>Tree Map &eacute; um aplicativo descritivo que permite visualizar a participa&ccedil;&atilde;o, em termos percentuais, das diversas vari&aacute;veis dispon&iacute;veis no DataViva. Esta visualiza&ccedil;&atilde;o possibilita analisar a import&acirc;ncia de um produto na pauta de exporta&ccedil;&otilde;es de uma localidade, por exemplo. O gr&aacute;fico do Tree Map &eacute; constru&iacute;do com blocos proporcionais &agrave; participa&ccedil;&atilde;o das categorias selecionadas no total, agrupadas ainda por cores que representam os grandes grupos para cada vari&aacute;vel.</p>
<p>A l&oacute;gica do Tree Map &eacute; a mesma utilizada em um gr&aacute;fico de pizza ou outra forma de representa&ccedil;&atilde;o visual de distribui&ccedil;&atilde;o da participa&ccedil;&atilde;o de itens no somat&oacute;rio total. A utiliza&ccedil;&atilde;o de blocos agrupados por grandes grupos e em ordem de import&acirc;ncia permite uma visualiza&ccedil;&atilde;o r&aacute;pida dos itens com maior participa&ccedil;&atilde;o e em qual grande grupo ele est&aacute; contido, possibilitando uma an&aacute;lise simples e r&aacute;pida dos percentuais de participa&ccedil;&atilde;o.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, mostra a participa&ccedil;&atilde;o de cada um dos produtos nas exporta&ccedil;&otilde;es de Minas Gerais, revelando com clareza a participa&ccedil;&atilde;o significativa do produto Min&eacute;rio de Ferro nas exporta&ccedil;&otilde;es do estado. V&aacute;rias outras perspectivas s&atilde;o poss&iacute;veis por meio dessa visualiza&ccedil;&atilde;o, utilizando as vari&aacute;veis &#8203;&#8203;dispon&iacute;veis na plataforma como atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es, localidades, al&eacute;m da interse&ccedil;&atilde;o entre essas vari&aacute;veis.</p>
<p><a href="/pt/build_graph/secex/4mg/all/all?view=Imports/Exports&graph=tree_map" target="_blank" class="btn btn-success" title="Tree Map"><i class="dv-graph-tree_map m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Tree Map'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Stacked visualization allows analyzing the growth of a variable over time. Built as an area chart in which the height of each line represents its share in total or gross, this view follows the same color pattern of the other visualizations, facilitating the identification of large groups to which each item belongs. Therefore, this visualization facilitates an understanding of the growth patterns and trends of any of the variables available in DataViva.</p>
<p>The purpose of this visualization is to allow the visualization of the data in a time series, revealing product, economic activities, occupations or localities with greater participation over time and its history of growth or decrease, either in gross or percentage.</p>
<p>One of the visualizations, for instance, is for economic activities of Minas Gerais, revealing the overall growth of the state economy and which sectors had the greatest contribution to this growth since 2002. Like the other visualizations, you can modify the data displayed for any of the basic variables available in DataViva (products, activities, occupations) and their intersections with localities all over Brazil at different levels (regions, states, mesoregions, microregions and municipalities).</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=stacked" target="_blank" class="btn btn-success" title="Stacked"><i class="dv-graph-stacked m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o Evolu&ccedil;&atilde;o permite analisar o crescimento da participa&ccedil;&atilde;o de uma vari&aacute;vel ao longo do tempo. Constru&iacute;da como um gr&aacute;fico de &aacute;rea, no qual a altura de cada linha representa sua participa&ccedil;&atilde;o no total ou seu valor bruto, esta visualiza&ccedil;&atilde;o segue o mesmo padr&atilde;o de cores dos outros aplicativos, facilitando a identifica&ccedil;&atilde;o dos grandes grupos aos quais cada item pertence. Desta forma, este aplicativo facilita a compreens&atilde;o dos padr&otilde;es e tend&ecirc;ncias de crescimento de qualquer uma das vari&aacute;veis dispon&iacute;veis no DataViva.</p>
<p>O objetivo do aplicativo Evolu&ccedil;&atilde;o &eacute; permitir a visualiza&ccedil;&atilde;o dos dados em uma s&eacute;rie hist&oacute;rica, revelando produtos, atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es ou localidades com maior participa&ccedil;&atilde;o ao longo do tempo e seu hist&oacute;rico de crescimento ou redu&ccedil;&atilde;o, seja em valores brutos ou percentuais.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, permite avaliar o crescimento total do mercado de trabalho no estado de Minas Gerais e quais os grupos de ocupa&ccedil;&atilde;o tiveram maior contribui&ccedil;&atilde;o neste crescimento, desde 2002. Assim como outras visualiza&ccedil;&otilde;es, &eacute; poss&iacute;vel modificar os dados exibidos para qualquer uma das vari&aacute;veis &#8203;&#8203;b&aacute;sicas dispon&iacute;veis no DataViva (produtos, atividades, ocupa&ccedil;&otilde;es) e seus cruzamentos com as localidades de todo o Brasil em diferentes n&iacute;veis de agrega&ccedil;&atilde;o (regi&atilde;oes, estados, mesorregi&otilde;es, microrregi&otilde;es e munic&iacute;pios).</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=stacked" target="_blank" class="btn btn-success" title="Evolu&ccedil;&atilde;o"><i class="dv-graph-stacked m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Stacked'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Geo Map is a descriptive geographical visualization that enables an analysis of the spatial distribution of the variables available in DataViva. Using a heat scale, it shows the municipalities with the largest (in red) and lowest (blue) values, and allows navigation both to zoom in and out, as to see more information about a selected municipality. This visualization aims to reveal the geographic distribution of the data.</p>
<p>One of the visualizations, for example, shows the economic activities in Minas Gerais by municipality, showing its concentration in the Metropolitan Region of Belo Horizonte. As in other visualizations, you can change the visualization to the desired variable with the filters.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=geo_map" target="_blank" class="btn btn-success" title="Geo Map"><i class="dv-graph-geo_map m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O Mapa &eacute; uma visualiza&ccedil;&atilde;o descritiva geogr&aacute;fica que possibilita uma an&aacute;lise da distribui&ccedil;&atilde;o espacial das vari&aacute;veis dispon&iacute;veis no DataViva. A partir de uma escala de calor, s&atilde;o mostrados os munic&iacute;pios com maiores valores (em vermelho) e menores valores (em azul), permite a navega&ccedil;&atilde;o de aproxima&ccedil;&atilde;o (zoom in) e afastamento (zoom out) para exibição de maiores informa&ccedil;&otilde;es sobre o munic&iacute;pio selecionado. Este aplicativo tem como objetivo revelar a distribui&ccedil;&atilde;o geogr&aacute;fica dos dados.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, exibe as atividades econ&ocirc;micas em Minas Gerais por munic&iacute;pio, evidenciando sua concentra&ccedil;&atilde;o na Regi&atilde;o Metropolitana de Belo Horizonte. Assim como nas outras visualizações, &eacute; poss&iacute;vel alterar a perspectiva de acordo com a vari&aacute;vel desejada.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=geo_map" target="_blank" class="btn btn-success" title="Mapa"><i class="dv-graph-geo_map m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Geo Map'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Network visualization displays the original Product Space, using the same network of products created by professors Hidalgo and Hausmann based on worldwide exports. It represents the connections between products in terms of the probability of co-exportation of these, and is the basis of the theory of economic development proposed by these professors from MIT and Harvard, respectively. In DataViva one can also visualize the &ldquo;Industry Space&rdquo;, a representation of the connections of all Brazilian economic activities based on their shared occupations.</p>
<p>This visualization allows highlighting, in the Product Space or the Industry Space, all products or activities in which a region has Revealed Comparative Advantage (RCA&gt;1). Therefore, one can see where are the products or activities in which a region has comparative advantage, if these products or activities are in the central region of the network (are more complex) and what are their connections.</p>
<p>This is a prescriptive visualization that reveals interesting ways for the economic development of a region based on the Product Space theory. According to this theory, a region must move (gain comparative advantage) to products or activities located in the center of the network, starting from those products or activities in which it already has comparative advantage.</p>
<p>One visualization, for instance, on DataViva, is the Industry Space of Minas Gerais, allowing to quickly learn in what activities the state has comparative advantage and in which categories they are (from the same color pattern used on all visualizations).</p>
<p>For a better understanding and interpretation of this visualization, it is recommended to check the terms and basic concepts of the Product Space theory.</p>
<p><a href="/en/build_graph/secex/4mg/all/all?view=Product%20Space&graph=network" target="_blank" class="btn btn-success" title="Network"><i class="dv-graph-network m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O aplicativo de Rede disponibiliza a visualiza&ccedil;&atilde;o original do <i>Product Space</i>, criada pelos professores Hidalgo and Hausmann, baseada nas exportações mundiais. A visualiza&ccedil;&atilde;o representa as conex&otilde;es entre os produtos em termos de suas probabilidades de co-exporta&ccedil;&atilde;o destes. No DataViva tamb&eacute;m &eacute; poss&iacute;vel visualizar o &ldquo;espa&ccedil;o de atividades&rdquo;, uma representa&ccedil;&atilde;o da rede de conex&otilde;es das atividades econ&ocirc;micas brasileiras a partir de suas ocupa&ccedil;&otilde;es comuns.</p>
<p>A visualiza&ccedil;&atilde;o permite sobrepor os produtos ou as atividades nos quais uma regi&atilde;o possui a chamada vantagem comparativa revelada (RCA&gt;1). Deste modo, pode-se perceber onde est&atilde;o localizados os produtos ou as atividades nos quais a regi&atilde;o possui vantagem comparativa, se estes produtos ou atividades est&atilde;o na regi&atilde;o central da rede (mais complexos) e quais s&atilde;o suas conex&otilde;es.</p>
<p>Este &eacute; um aplicativo prescritivo que revela caminhos mais interessantes para o desenvolvimento econ&ocirc;mico de uma regi&atilde;o com base na teoria do <i>Product Space</i>. De acordo com esta teoria, uma regi&atilde;o deve mover (conquistar vantagem comparativa) para produtos ou atividades localizados no centro da rede a partir daqueles produtos ou atividades nos quais j&aacute; possui vantagem comparativa.</p>
<p>Uma das visualiza&ccedil;&otilde;es presentes no DataViva, por exemplo, é o Espa&ccedil;o de Produtos para Minas Gerais. A visualiza&ccedil;&atilde;o de Rede mostra, de forma simplificada, em quais produtos o estado possui vantagem comparativa e de quais categorias eles pertencem.</p>
<p>Para melhor entendimento e interpreta&ccedil;&atilde;o dessa visualiza&ccedil;&atilde;o &eacute; recomendado consultar os conceitos b&aacute;sicos da teoria do <i>Product Space</i>.</p>
<p><a href="/pt/build_graph/secex/4mg/all/all?view=Product%20Space&graph=network" target="_blank" class="btn btn-success" title="Rede"><i class="dv-graph-network m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Network'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Rings is a prescriptive visualization that allows viewing a product, industry or occupation in isolation, making it easier to navigate round its primary and secondary connections, which can be a bit difficult in the Network visualization. It also shows those products, activities or occupations in which the selected location has revealed comparative advantage (RCA&gt; 1).</p>
<p>This is important because, according to the Product Space theory, having comparative advantage in a product means that the region has the expertise to produce it and the knowledge that is shared in the production of connected products. Thus, one can visualize, quickly and easily, if the product has many connections and if these are with products that the region already has comparative advantage, which would facilitate its development, because it means that much of the productive knowledge needed is already present.</p>
<p>Similar to other visualizations, Rings uses a standard color pattern that lets one see of which big group a product, industry or occupation belongs, as well as other groups with which it is connected. Correctly understanding the concepts of the Product Space theory is fundamental to interpret this prescriptive visualization.</p>
<p>One of the visualizations, for instance, shows the connections for biologists in Minas Gerais, therefore we can analyze the occupations connected to biologists directly or not.</p>
<p><a href="/en/build_graph/rais/4mg/all/2211?view=Similar%20Occupations&graph=rings" target="_blank" class="btn btn-success" title="Rings"><i class="dv-graph-rings m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o de An&eacute;is &eacute; prescritiva e permite analisar um produto, atividade econ&ocirc;mica ou ocupa&ccedil;&atilde;o de forma isolada, facilitando a navega&ccedil;&atilde;o por suas conex&otilde;es de primeiro e segundo grau, o que pode ser um pouco complicada na visualiza&ccedil;&atilde;o de Rede. A visualiza&ccedil;&atilde;o de An&eacute;is disponibiliza produtos, atividades ou ocupa&ccedil;&otilde;es nas quais a localidade selecionada possui vantagem comparativa revelada (RCA&gt;1).</pr>
<p>Isto &eacute; importante porque, de acordo com a teoria do <i>Product Space</i>, possuir vantagem comparativa em um produto, por exemplo, significa que a regi&atilde;o possui os conhecimentos necess&aacute;rios para produzi-lo, conhecimentos que s&atilde;o compartilhados na produ&ccedil;&atilde;o de produtos conectados. Deste modo, visualiza-se de forma r&aacute;pida e f&aacute;cil se o produto analisado possui muitas conex&otilde;es e se estas s&atilde;o com produtos que a regi&atilde;o j&aacute; possui vantagem comparativa, o que facilitaria seu desenvolvimento.<p/>
<p>Semelhante a outros aplicativos, a visualiza&ccedil;&atilde;o de An&eacute;is utiliza um conjunto de cores padr&atilde;o que permite verificar qual grupo um produto, ind&uacute;stria ou atividade econ&ocirc;mica pertence, bem como outros grupos com os quais ele est&aacute; conectado. &Eacute; interessante compreender corretamente os conceitos da teoria do <i>Product Space</i> para interpretar essa visualiza&ccedil;&atilde;o prescritiva.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, mostra as conex&otilde;es para os bi&oacute;logos em Minas Gerais, sendo poss&iacute;vel analisar as ocupa&ccedil;&otilde;es conectadas aos bi&oacute;logos de forma direta ou em segundo grau.</p>
<p><a href="/pt/build_graph/rais/4mg/all/2211?view=Similar%20Occupations&graph=rings" target="_blank" class="btn btn-success" title="An&eacute;is"><i class="dv-graph-rings m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Rings'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Scatter visualization is another prescriptive visualization which allows comparing the distribution of economic activities and exports of a location based on the relationship between two variables (one on the X axis and another one on the Y axis). This graph facilitates the analysis and definition of the more interesting activities and products for the economic development of a region by putting together two indicators of the Product Space theory.</p>
<p>For example, to determine which product would be more interesting for the development of a location, one can use the Scatter visualization to analyze simultaneously the indicators of complexity and distance of a product from the current production structure of this location. Products with higher complexity and lower distance will be located in the same quadrant of the graph and those would be, in principle, the ones with the greatest potential for the location.</p>
<p>One visualization, for example, shows the economic activities of Minas Gerais and its plot distribution considering the distance (x-axis) and the unique occupations (y-axis). Note that Construction is the group of activities with the highest number of unique occupations and one of the smallest distances to the state, while Financial Services &amp; Insurance is the group with the smallest number of unique occupations and greater distance. Hence, the visualization allows easy analysis of the activities and products of a region from the intersection of two of the indicators calculated based on the Product Space theory.</p>
<p>As in other prescriptive visualizations, it is recommended to know the terms and concepts of the Product Space theory to make a correct interpretation of the visualization.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Industries&graph=scatter" target="_blank" class="btn btn-success" title="Scatter"><i class="dv-graph-scatter m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o de Dispers&atilde;o &eacute; mais uma aplica&ccedil;&atilde;o prescritiva e permite visualizar de forma comparativa a distribui&ccedil;&atilde;o das atividades econ&ocirc;micas e exporta&ccedil;&otilde;es de uma localidade a partir da rela&ccedil;&atilde;o entre duas vari&aacute;veis (uma no eixo x e outra no eixo y). Esse gr&aacute;fico facilita a an&aacute;lise e defini&ccedil;&atilde;o das atividades e produtos mais interessantes para o desenvolvimento econ&ocirc;mico de uma regi&atilde;o ao colocar juntos dois indicadores da teoria do <i>Product Space</i>.</p>
<p>Por exemplo, para determinar qual produto seria mais interessante para o desenvolvimento de uma localidade, pode-se usar a visualiza&ccedil;&atilde;o de dispers&atilde;o para analisar ao mesmo tempo o &iacute;ndice de complexidade do produto e sua dist&acirc;ncia em rela&ccedil;&atilde;o &agrave; estrutura produtiva atual dessa localidade. Os produtos com maior complexidade e menor dist&acirc;ncia estar&atilde;o localizados no mesmo quadrante do gr&aacute;fico e seriam aqueles, a princ&iacute;pio, com maior potencial para a localidade analisada. </p>
<p>Uma visualiza&ccedil;&atilde;o, por exemplo, que mostra as atividades econ&ocirc;micas de Minas Gerais e o seu plano de distribui&ccedil;&atilde;o considerando a dist&acirc;ncia (eixo x) e as ocupa&ccedil;&otilde;es &uacute;nicas (eixo y). Note que Constru&ccedil;&atilde;o &eacute; um dos grupos de atividade com o maior n&uacute;mero de ocupa&ccedil;&otilde;es &uacute;nicas e uma das menores dist&acirc;ncias para o estado, enquanto que Atividades Financeiras &eacute; um grupo com um n&uacute;mero menor de ocupa&ccedil;&otilde;es &uacute;nicas e uma dist&acirc;ncia maior. Consequentemente, a visualiza&ccedil;&atilde;o permite uma f&aacute;cil an&aacute;lise das atividades e produtos de uma regi&atilde;o dado a interse&ccedil;&atilde;o de dois indicadores calculados baseando na teoria do <i>Product Space</i>.</p>
<p>Assim como em outras visualiza&ccedil;&otilde;es prescritivas, &eacute; recomendado conhecer os termos e os conceitos da teoria do <i>Product Space</i> para fazer uma interpreta&ccedil;&atilde;o correta da visualiza&ccedil;&atilde;o.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Industries&graph=scatter" target="_blank" class="btn btn-success" title="Dispers&atilde;o"><i class="dv-graph-scatter m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Scatter'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The eighth DataViva visualization aims to facilitate comparison between two different localities and works the same way as a scatter plot. Each locality compared occupies one of the axes of the graph and the values of selected variables are distributed in the same scale, creating a diagonal line where the values are equal. We can thus compare the values of the variables available between two localities (municipalities, regions and states) in a simple and visual way.</p>
<p>One of the visualizations is a comparison of exports from Minas Gerais and Rio de Janeiro, revealing that Mineral Products is a leading category for both states, with very similar values, since they are located near the diagonal line of the graph. Some other products like Arts and Antiques are exported significantly more by Rio de Janeiro state, while products such as Precious Metals are exported mostly by Minas Gerais.</p>
<p>These comparisons can help with finding other reference localities or determining the most interesting localities for a particular investment or economic activities which are more concentrated in certain regions. Compare creates visualizations with the main variables available in DataViva (products, activities, occupations) and reveal or confirm hypotheses about differences or similarities in the variables selected between two Brazilian localities.</p>
<p><a href="/en/build_graph/secex/4mg/all/all?view=513MAm/6HA&graph=compare&compare=4rj020212" target="_blank" class="btn btn-success" title="Compare"><i class="dv-graph-compare m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o Compare tem como objetivo facilitar a compara&ccedil;&atilde;o entre duas localidades diferentes e funciona da mesma forma que um gr&aacute;fico de dispers&atilde;o. Cada localidade comparada ocupa um dos eixos do gr&aacute;fico e os valores das vari&aacute;veis selecionadas s&atilde;o distribu&iacute;dos numa mesma escala, criando uma linha diagonal na qual os valores s&atilde;o iguais. Pode-se assim comparar os valores das vari&aacute;veis dispon&iacute;veis entre duas localidades (munic&iacute;pios, mesorregi&otilde;es, estados) de forma simples e visual.</p>
<p>Uma poss&iacute;vel visualiza&ccedil;&atilde;o, &eacute; a compara&ccedil;&atilde;o de exporta&ccedil;&atilde;o de Minas Gerais e Rio de Janeiro, revelando que a categoria Produtos Minerais est&aacute; liderando em ambos os estados, com um valor similar, dado que ela est&aacute; pr&oacute;xima &agrave; linha diagonal do gr&aacute;fico. Outros produtos, como Artes e Antiguidades, s&atilde;o mais exportados pelo estado do Rio de Janeiro, enquanto que os produtos da categoria de Metais Preciosos s&atilde;o mais exportados por Minas Gerais.</p>
<p>Essa compara&ccedil;&atilde;o pode ajudar encontrando outras localidades de refer&ecirc;ncia ou determinando as localidades mais interessante para um investimentos em particular ou atividades econ&ocirc;micas que est&atilde;o mais concentradas em certas regi&otilde;es . Compare cria visualiza&ccedil;&otilde;es com os principais dados dispon&iacute;veis no DataViva (produtos, atividades, ocupa&ccedil;&otilde;es) e revela ou confirma hip&oacute;teses sobre a diferen&ccedil;a ou similaridade entre as vari&aacute;veis de duas localidade brasileiras.</p>
<p><a href="/pt/build_graph/secex/4mg/all/all?view=513MAm/6HA&graph=compare&compare=4rj020212" target="_blank" class="btn btn-success" title="Compare"><i class="dv-graph-compare m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Compare'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Occugrid deals specifically with RAIS data regarding occupations in Brazil. The goal is to show graphically which are the main occupations employed in various economic activities, their importance to each industry and the number of employees who work in these activities. Prescriptive in nature, this visualization compares the location in question with a reference calculated from the definition of other similar localities in terms of economic structure. Consequently, it enables, in a single visualization, the ability to know what are the main occupations of an industry, how many professionals work in comparable localities, how many professionals work in the region, and how many of them work specifically in that region and industry.</p>
<p>This type of visualization allows an analysis of the labor market of a region, the professions needed to develop an industry, and, in conjunction with other visualizations about economic activities and occupations, links occupations and economic activities (which may also be related to the products they manufacture). It is also an initial step towards an analysis of human capital training needs in a locality, revealing shortcomings of qualified personnel and its importance for the economic activities analyzed.</p>
<p>Unlike the other visualizations, the Occugrid allows only one type of output, because it was created especially for the analysis of occupations (and related economic activities). However, the output can use different parameters and types of grouping. One of the possible visualizations shows the average number of jobs per establishment for Restaurants in Minas Gerais.</p>
<p><a href="/en/build_graph/rais/4mg/i56112/all?view=b99qCp0Tc7&graph=occugrid" target="_blank" class="btn btn-success" title="Occugrid"><i class="dv-graph-occugrid m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o de Ocupa&ccedil;&atilde;o trata especificamente dos dados da RAIS sobre ocupa&ccedil;&atilde;o no Brasil. Seu objetivo &eacute; mostrar de forma gr&aacute;fica quais as principais ocupa&ccedil;&otilde;es empregadas nas diversas atividades econ&ocirc;micas, sua import&acirc;ncia para cada atividade e o n&uacute;mero de empregados que atuam nelas. De natureza prescritiva, essa visualiza&ccedil;&atilde;o compara a localidade em an&aacute;lise com uma refer&ecirc;ncia calculada a partir da defini&ccedil;&atilde;o de outras localidades similares em termos de estrutura econ&ocirc;mica. Deste modo, ela permite, numa &uacute;nica visualiza&ccedil;&atilde;o, conhecer quais s&atilde;o as principais ocupa&ccedil;&otilde;es de uma atividade, quantos profissionais atuam nas localidades compar&aacute;veis, quantos profissionais atuam na regi&atilde;o e quantos deles atuam especificamente naquela regi&atilde;o e atividade.</p>
<p>Este tipo de visualiza&ccedil;&atilde;o permite uma an&aacute;lise do mercado de trabalho de uma regi&atilde;o, das profiss&otilde;es necess&aacute;rias para desenvolver uma atividade econ&ocirc;mica, e, em conjunto com outras visualiza&ccedil;&otilde;es relacionadas &agrave; atividades econ&ocirc;micas e ocupa&ccedil;&otilde;es, permite ligar ocupa&ccedil;&otilde;es e atividades econ&ocirc;micas (que podem ainda ser relacionadas com os produtos que fabricam). &Eacute;, ainda, um passo inicial para uma an&aacute;lise das necessidades de forma&ccedil;&atilde;o de capital humano de uma localidade, revelando defici&ecirc;ncias de profissionais qualificados e sua import&acirc;ncia para as atividades econ&ocirc;micas analisadas. </p>
<p>Diferentemente dos demais aplicativos, Ocupa&ccedil;&otilde;es permite apenas um tipo de visualiza&ccedil;&atilde;o, pois foi criado especialmente para a an&aacute;lise das ocupa&ccedil;&otilde;es (relacionadas com as atividades econ&ocirc;micas). Por&eacute;m, a visualiza&ccedil;&atilde;o pode ser feita utilizando diferentes par&acirc;metros e tipos de agrupamento.</p>
<p>Uma poss&iacute;vel visualiza&ccedil;&atilde;o mostra o n&uacute;mero m&eacute;dio de empregos por estabelecimentos para a atividade econ&ocirc;mica Restaurantes em Minas Gerais.</p>
<p><a href="/pt/build_graph/rais/4mg/i56112/all?view=b99qCp0Tc7&graph=occugrid" target="_blank" class="btn btn-success" title="<Ocupa&ccedil;&atilde;o</p>"><i class="dv-graph-occugrid m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Occugrid'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Line visualization allows analyzing the change of a variable over time. This view follows the same color pattern of the other visualizations, facilitating the identification of large groups to which each item belongs. Therefore, this visualization facilitates an understanding of the growth patterns and trends of any of the variables available in DataViva.</p>
<p>The purpose of this visualization is to allow the visualization of the data in a time series, revealing product, economic activities, occupations or localities with greater participation over time and its history of growth or decrease, either in gross or percentage.</p>
<p>Like the other visualizations, you can modify the data displayed for any of the basic variables available in DataViva (products, activities, occupations) and their intersections with localities all over Brazil at different levels (state, region, municipality).</p>
<p>One of the visualizations, for instance, is for economic activities of Minas Gerais, revealing the overall growth of the state economy and which sectors had the greatest contribution to this growth.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=60fGWGIai+&graph=line" target="_blank" class="btn btn-success" title="Line"><i class="dv-graph-line m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O Gr&aacute;fico de Linha permite analisar as mudan&ccedil;as de uma vari&aacute;vel ao longo do tempo. Esta visualiza&ccedil;&atilde;o segue o mesmo padr&atilde;o de cores das demais, facilitando a identifica&ccedil;&atilde;o de grandes grupos aos quais cada item pertence. Portanto, essa visualiza&ccedil;&atilde;o, facilita a compreens&atilde;o dos padr&otilde;es de crescimento e as tend&ecirc;ncias de qualquer vari&aacute;vel dispon&iacute;vel no DataViva.</p>
<p>Seu objetivo &eacute; permitir a visualiza&ccedil;&atilde;o dos dados em uma s&eacute;rie hist&oacute;rica, revelando produtos, atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es ou localidades com maior participa&ccedil;&atilde;o ao longo do tempo e seu hist&oacute;rico de crescimento ou redu&ccedil;&atilde;o, seja em valores brutos ou percentuais.</p>
<p>Como em outras visualiza&ccedil;&otilde;es, voc&ecirc; pode modificar o dado sendo mostrado para cada umas das vari&aacute;veis dispon&iacute;veis no DataViva (produtos, atividades, ocupa&ccedil;&otilde;es) e suas interse&ccedil;&atilde;o com qualquer localidade do Brasil, em qualquer um dos n&iacute;veis (estado, regi&atilde;o. munic&iacute;pio). </p>
<p>Uma visualiza&ccedil;&atilde;o, por exemplo, &eacute; para as atividades econ&ocirc;micas de Minas Gerais, revelando o crescimento global da economia no estado e quais setores tiveram maior contribui&ccedil;&atilde;o para esse crescimento.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=60fGWGIai+&graph=line" target="_blank" class="btn btn-success" title="Linha"><i class="dv-graph-line m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Line'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Box Plot visualization allows analyzing the change of a variables range across a series of distinct points. Each box represents the IQR, or Interquartile Range for a series of data. This range is defined by the first and third quartiles, with a bisection line repesenting the median. Whiskers extend from the IQR to show the minimum and maximum values for the data series.</p>
<p>This visualization is helpful when showing wage distribution over time, or age distribution across different education levels. As example, we can take the wage distribuition in Minas Gerais. Even having a discrepancy of data for the maximun and minimum value is possible to understand the wage distribution for most of employees.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=2RGpK4Ft2j&graph=box" target="_blank" class="btn btn-success" title="Box Plot"><i class="dv-graph-box m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O Box Plot &eacute; uma visualiza&ccedil;&atilde;o que permite analisar a mudan&ccedil;a de intervalo das vari&aacute;veis numa s&eacute;rie de pontos distintos. Cada caixa representa um interquartil de uma s&eacute;rie de dados. Esse intervalo &eacute; representado pelo primeiro e o terceiro quartil. A linha de bisse&ccedil;&atilde;o da caixa &eacute; a representa&ccedil;&atilde;o da mediana e os extremos dela s&atilde;o a representa&ccedil;&atilde;o do m&aacute;ximo e do m&iacute;nimo para esse interquartil.</p>
<p>Essa visualiza&ccedil;&atilde;o &eacute; &uacute;til para mostrar a distribui&ccedil;&atilde;o de sal&aacute;rio ao longo do tempo, ou a distribui&ccedil;&atilde;o de idade em diferentes n&iacute;veis de educa&ccedil;&atilde;o. Como exemplo, podemos pegar a distribui&ccedil;&atilde;o de sal&aacute;rio para o estado de Minas Gerais. Mesmos com a discrep&acirc;ncia de dados para o valor m&aacute;ximo e m&iacute;nimo ainda &eacute; poss&iacute;vel compreender a distribui&ccedil;&atilde;o dos sal&aacute;rios para a maior parte dos empregados.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=2RGpK4Ft2j&graph=box" target="_blank" class="btn btn-success" title="Box Plot"><i class="dv-graph-box m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o</i><i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Box Plot'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Bar Chart visualization allows analyzing values as a histogram. The y-axis represents the frequency of occurances in each bucket display on the x-axis. The buckets are calculated from two times the standard deviation above and below the mean value.</p>
<p>This visualization is helpful when showing wage distribution for a single filter, such as location or occupation. One possible visualization, show the wage distribution in Minas Gerais. It shows the total employees (the frequency represented in y axis), for which wage range (wage data represented in x axis). Therefore, is evaluated the employees number for which wage range.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=2RGpK4Ft2j&graph=bar" target="_blank" class="btn btn-success" title="Bar Chart"><i class="dv-graph-bar m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O Gr&aacute;fico de Barras &eacute; uma visualiza&ccedil;&atilde;o que permite analisar valores num histograma. Os dados s&atilde;o representados por ret&acirc;ngulos no eixo x, sendo o eixo y a representa&ccedil;&atilde;o da frequ&ecirc;ncia de ocorr&ecirc;ncia de cada um desses. O tamanho de cada ret&acirc;ngulo &eacute; calculado por duas vezes o desvio padr&atilde;o para cima e para baixo do valor m&eacute;dio. </p>
<p>Essa visualiza&ccedil;&atilde;o &eacute; &uacute;til para mostrar a distribui&ccedil;&atilde;o de sal&aacute;rio para um &uacute;nico filtro, como localiza&ccedil;&atilde;o ou ocupa&ccedil;&atilde;o. Como exemplo de visualiza&ccedil;&atilde;o, temos a distribui&ccedil;&atilde;o de sal&aacute;rios em Minas Gerais. Nela &eacute; poss&iacute;vel avaliar o total de empregados (frequ&ecirc;ncia representada no eixo y), para cada umas das faixas de renda (dado salarial representado pelo eixo x). Assim, avalia-se a quantidade de pessoas empregadas que recebem cada uma das faixas salariais.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=2RGpK4Ft2j&graph=bar" target="_blank" class="btn btn-success" title="Gr&aacute;fico de Barras"><i class="dv-graph-bar m-r-sm"></i>Abrir visualiza&ccedil;&atilde;o</i><i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Bar Chart'