 update attrs_cnae set img_author = 'SEBRAE-SP', img_link = 'https://flic.kr/p/nLMgXk'  where id = 'g';
 update attrs_cnae set img_author = 'Ministério das Relações Exteriores', img_link = 'https://flic.kr/p/ro7u6z'  where id = 'o';
 update attrs_cnae set img_author = 'Deltha Assessoria Empresas', img_link = 'https://flic.kr/p/nqVUP5'  where id = 'o84';
 update attrs_cnae set img_author = 'senado federal', img_link = 'https://flic.kr/p/q6gEoN'  where id = 'o84116';
 update attrs_cnae set img_author = 'jano 297', img_link = 'https://flic.kr/p/bW4qEL'  where id = 'c';
 update attrs_cnae set img_author = 'José María Gómez', img_link = 'https://flic.kr/p/qc5Vpj'  where id = 'g47';
 update attrs_cnae set img_author = 'Conselho Nacional de justiça', img_link = 'https://flic.kr/p/pFAoyy'  where id = 'n';
 update attrs_cnae set img_author = 'Mariana Andrade', img_link = 'https://flic.kr/p/rQ6xUH'  where id = 'f';
 update attrs_cnae set img_author = 'silvanamameluque', img_link = 'https://flic.kr/p/q4eThp'  where id = 'h';
 update attrs_cnae set img_author = 'Prefeitura de Olinda', img_link = 'https://flic.kr/p/e9RTny'  where id = 'q';
 update attrs_cnae set img_author = 'Unicesumar Oficial', img_link = 'https://flic.kr/p/9n5hbM'  where id = 'p';
 update attrs_cnae set img_author = 'alfredo_castro2014', img_link = 'https://flic.kr/p/mKZRMs'  where id = 'p85';
 update attrs_cnae set img_author = 'Aron Heleodoro', img_link = 'https://flic.kr/p/4sgTba'  where id = 'i';
 update attrs_cnae set img_author = 'Prefeitura de Santo Estevão', img_link = 'https://flic.kr/p/bPBLKa'  where id = 'q86';
 update attrs_cnae set img_author = 'Ministerio Transporte ', img_link = 'https://flic.kr/p/fsX7s8'  where id = 'h49';
 update attrs_cnae set img_author = 'Fort Atacadista', img_link = 'https://flic.kr/p/s4AGHZ'  where id = 'g46';
 update attrs_cnae set img_author = 'luismontanez', img_link = 'https://flic.kr/p/7dnqRi'  where id = 'i56';
 update attrs_cnae set img_author = 'Wagner Pacini', img_link = 'https://flic.kr/p/5ikK19'  where id = 'n81';
 update attrs_cnae set img_author = 'toroimages', img_link = 'https://flic.kr/p/4vrN3g'  where id = 'c10';
 update attrs_cnae set img_author = 'bibibarbara', img_link = 'https://flic.kr/p/otc4yC'  where id = 'a';
 update attrs_cnae set img_author = 'keiko_learning_center', img_link = 'https://flic.kr/p/4QhvP1'  where id = 'n82';
 update attrs_cnae set img_author = 'Ângelo Rigon', img_link = 'https://flic.kr/p/pELGSM'  where id = 'a01';
 update attrs_cnae set img_author = 'Bruno Shiraishi', img_link = 'https://flic.kr/p/ajnuyj'  where id = 'f41';
 update attrs_cnae set img_author = 'BOULEVARD WORLD', img_link = 'https://flic.kr/p/9GYagK'  where id = 'i56112';
 update attrs_cnae set img_author = 'David Santos-3a', img_link = 'https://flic.kr/p/5iuyVk'  where id = 'g47113';
 update attrs_cnae set img_author = 'cjsprestacoes10', img_link = 'https://flic.kr/p/8UEfr9'  where id = 's';
 update attrs_cnae set img_author = 'Kieran Mitchell', img_link = 'https://flic.kr/p/4RWiNA'  where id = 'q86101';
 update attrs_cnae set img_author = 'Gabriel de Andrade', img_link = 'https://flic.kr/p/dHg3Qz'  where id = 'f41204';
 update attrs_cnae set img_author = 'Nove Eventos', img_link = 'https://flic.kr/p/9py912'  where id = 'm';
 update attrs_cnae set img_author = 'Autosat Spa', img_link = 'https://flic.kr/p/e45iBi'  where id = 'g45';
 update attrs_cnae set img_author = 'porta bh', img_link = 'https://flic.kr/p/cdWitj'  where id = 'h49302';
 update attrs_cnae set img_author = 'Rodrigo Grissi', img_link = 'https://flic.kr/p/7tHDu4'  where id = 'k';
 update attrs_cnae set img_author = 'Prefeitura de Olinda', img_link = 'https://flic.kr/p/6uMVvU'  where id = 'f42';
 update attrs_cnae set img_author = 'Senado Federal', img_link = 'https://flic.kr/p/qmsCwq'  where id = 'j';
 update attrs_cnae set img_author = 'EMBARQ Brasil ', img_link = 'https://flic.kr/p/qmMgHc'  where id = 's94';
 update attrs_cnae set img_author = 'Clóvis Costa', img_link = 'https://flic.kr/p/8SAmE3'  where id = 'f43';
 update attrs_cnae set img_author = 'Viés Design', img_link = 'https://flic.kr/p/oWduSS'  where id = 'g47814';
 update attrs_cnae set img_author = 'Portal PBH', img_link = 'https://flic.kr/p/9qnQbo'  where id = 'n80';
 update attrs_cnae set img_author = 'Portal de Jornalismo', img_link = 'https://flic.kr/p/pyA9Gf'  where id = 'n81214';
 update attrs_cnae set img_author = 'Teca Rodrigues', img_link = 'https://flic.kr/p/q9yuKY'  where id = 'c14';
 update attrs_cnae set img_author = 'Galeria de Fotos Regional ', img_link = 'https://flic.kr/p/9NBhjo'  where id = 'g47440';
 update attrs_cnae set img_author = 'Imprensa CAIXA', img_link = 'https://flic.kr/p/uGVKfx'  where id = 'k64';
 update attrs_cnae set img_author = 'Briza Mulatinho', img_link = 'https://flic.kr/p/8AQ32A'  where id = 'n81125';
 update attrs_cnae set img_author = 'Paróquia Espírito Santo', img_link = 'https://flic.kr/p/rAiqGA'  where id = 'n80111';
 update attrs_cnae set img_author = 'UBRAFE Entidade', img_link = 'https://flic.kr/p/wKgyGg'  where id = 'n78';
 update attrs_cnae set img_author = 'José Franca SN', img_link = 'https://flic.kr/p/syHLSZ'  where id = 'h49213';
 update attrs_cnae set img_author = 'CNI', img_link = 'https://flic.kr/p/dtHMqp'  where id = 'c14126';
 update attrs_cnae set img_author = 'Евгения Пономарева', img_link = 'https://flic.kr/p/oeLDr5'  where id = 'c25';
 update attrs_cnae set img_author = 'Agência Brasília', img_link = 'https://flic.kr/p/DisNkV'  where id = 'n82202';
 update attrs_cnae set img_author = 'Jhonathan Juncal', img_link = 'https://flic.kr/p/9eSjRx'  where id = 'c29';
 update attrs_cnae set img_author = 'Paulo Pampolin', img_link = 'https://flic.kr/p/s5oW5s'  where id = 'g47890';
 update attrs_cnae set img_author = 'Parchen', img_link = 'https://flic.kr/p/Ae76ZF'  where id = 'c23';
 update attrs_cnae set img_author = 'Monique Larentis', img_link = 'https://flic.kr/p/dr8hzg'  where id = 'c22';
 update attrs_cnae set img_author = 'Portal do DER', img_link = 'https://flic.kr/p/9vzyp5'  where id = 'g45307';
 update attrs_cnae set img_author = 'Plegamatic', img_link = 'https://flic.kr/p/dv1uEK'  where id = 'h52';
 update attrs_cnae set img_author = 'qubo Servicios ', img_link = 'https://flic.kr/p/8cH3m7'  where id = 'g47717';
 update attrs_cnae set img_author = 'ISCTE-IUL ', img_link = 'https://flic.kr/p/pLKyeU'  where id = 'm69';
 update attrs_cnae set img_author = 'Fotos GOVBA', img_link = 'https://flic.kr/p/fAxuR9'  where id = 'c28';
 update attrs_cnae set img_author = 'Vera Amaral', img_link = 'https://flic.kr/p/6XvHgd'  where id = 'p85325';
 update attrs_cnae set img_author = 'Autos - Brasil', img_link = 'https://flic.kr/p/peicQP'  where id = 'o84248';
 update attrs_cnae set img_author = 'Banco do Nordeste', img_link = 'https://flic.kr/p/khkmty'  where id = 'k64221';
 update attrs_cnae set img_author = 'Sylvio Bazote', img_link = 'https://flic.kr/p/oHew5j'  where id = 'n82997';
 update attrs_cnae set img_author = 'Mari Martins', img_link = 'https://flic.kr/p/f5apQK'  where id = 'g47121';
 update attrs_cnae set img_author = 'Roger Raniele', img_link = 'https://flic.kr/p/nTgJwq'  where id = 's94308';
 update attrs_cnae set img_author = 'Ana Elisa Mucci', img_link = 'https://flic.kr/p/8YC892'  where id = 'c15';
 update attrs_cnae set img_author = 'Parchen', img_link = 'https://flic.kr/p/7dC19q'  where id = 'a01512';
 update attrs_cnae set img_author = 'Prefeitura de Olinda', img_link = 'https://flic.kr/p/7NnoV1'  where id = 'e';
 update attrs_cnae set img_author = 'Felippe Domingos', img_link = 'https://flic.kr/p/61gjh9'  where id = 'g47318';
 update attrs_cnae set img_author = 'Interfau Interfau', img_link = 'https://flic.kr/p/81p1Tv'  where id = 'i55';
 update attrs_cnae set img_author = 'Bruno Batista', img_link = 'https://flic.kr/p/o83UuH'  where id = 'o84221';
 update attrs_cnae set img_author = 'Conselho Nacional de Justiça', img_link = 'https://flic.kr/p/nrqcbH'  where id = 'j62';
 update attrs_cnae set img_author = 'Santo Ivo', img_link = 'https://flic.kr/p/uezMJR'  where id = 'p85139';
 update attrs_cnae set img_author = 'Alexandru Bălan', img_link = 'https://flic.kr/p/eaXkW3'  where id = 'i55108';
 update attrs_cnae set img_author = 'Se (Setsuko) Hanazaki', img_link = 'https://flic.kr/p/afRHPq'  where id = 'g47211';
 update attrs_cnae set img_author = 'Nario Barbosa', img_link = 'https://flic.kr/p/c483pC'  where id = 'n78205';
 update attrs_cnae set img_author = 'Zoltan Gal', img_link = 'https://flic.kr/p/6LwAq1'  where id = 'i56201';
 update attrs_cnae set img_author = 'Amelia Monteiro', img_link = 'https://flic.kr/p/fD5A8x'  where id = 'c10716';
 update attrs_cnae set img_author = 'Khoai Ann', img_link = 'https://flic.kr/p/qV1sN6'  where id = 'c13';
 update attrs_cnae set img_author = 'Exército Brasileiro', img_link = 'https://flic.kr/p/vsYfxh'  where id = 'm71';
 update attrs_cnae set img_author = 'liyushiro', img_link = 'https://flic.kr/p/oz3Lj8'  where id = 'p85996';
 update attrs_cnae set img_author = 'AEMTG', img_link = 'https://flic.kr/p/dPRMKY'  where id = 'p85317';
 update attrs_cnae set img_author = 'Obras Sociais Irma Dulce', img_link = 'https://flic.kr/p/nqqGwu'  where id = 'q86305';
 update attrs_cnae set img_author = 'viggore Móveis', img_link = 'https://flic.kr/p/drMeNr'  where id = 'c31';
 update attrs_cnae set img_author = 'Cocab Pools', img_link = 'https://flic.kr/p/jpXd17'  where id = 'c20';
 update attrs_cnae set img_author = 'Autosat Spa', img_link = 'https://flic.kr/p/e45iBi'  where id = 'g45111';
 update attrs_cnae set img_author = 'Familia Noastra', img_link = 'https://flic.kr/p/m8A4T4'  where id = 'm69206';
 update attrs_cnae set img_author = 'Mariana da Matta', img_link = 'https://flic.kr/p/dUzp62'  where id = 'c10121';
 update attrs_cnae set img_author = 'Imprensa Via Varejo', img_link = 'https://flic.kr/p/rdojf9'  where id = 'g47547';
 update attrs_cnae set img_author = 'Fotografia cnj', img_link = 'https://flic.kr/p/odE6su'  where id = 'o84230';
 update attrs_cnae set img_author = 'catacang', img_link = 'https://flic.kr/p/eZuCj4'  where id = 'b';
 update attrs_cnae set img_author = 'ELISA M.V.', img_link = 'https://flic.kr/p/a7KtoH'  where id = 'r';
 update attrs_cnae set img_author = 'Ahmed AB', img_link = 'https://flic.kr/p/7QJfv4'  where id = 'n82113';
 update attrs_cnae set img_author = 'Nordeste1 jornalismo', img_link = 'https://flic.kr/p/8r11kB'  where id = 'g47539';
 update attrs_cnae set img_author = 'Ingeniørforeningen IDA', img_link = 'https://flic.kr/p/iQq7Gm'  where id = 'c21211';
 update attrs_cnae set img_author = 'emmanuelsaussier2003', img_link = 'https://flic.kr/p/q6AFeH'  where id = 'c14118';
 update attrs_cnae set img_author = 'Greg Putrich', img_link = 'https://flic.kr/p/8655t5'  where id = 'h52117';
 update attrs_cnae set img_author = 'Partenaire Européen', img_link = 'https://flic.kr/p/8F3f5w'  where id = 'n82199';
 update attrs_cnae set img_author = 'Texarkana College', img_link = 'https://flic.kr/p/853dPW'  where id = 'k65502';
 update attrs_cnae set img_author = 'Bob Adams', img_link = 'https://flic.kr/p/q3NBdG'  where id = 'n80129';
 update attrs_cnae set img_author = 'Paradise Village Nuevo Vallarta', img_link = 'https://flic.kr/p/jMwnsa'  where id = 'r93131';
 update attrs_cnae set img_author = 'Johnson Barros', img_link = 'https://flic.kr/p/qyGkJt'  where id = 'c33147';
 update attrs_cnae set img_author = 'Infraero Aeroportos', img_link = 'https://flic.kr/p/cJds9S'  where id = 'f43134';
 update attrs_cnae set img_author = 'rlsycle', img_link = 'https://flic.kr/p/9ZvKrP'  where id = 'g45412';
 update attrs_cnae set img_author = 'UNIDO', img_link = 'https://flic.kr/p/oSvAPA'  where id = 'c24';
 update attrs_cnae set img_author = 'Sergio Alex Azevedo', img_link = 'https://flic.kr/p/hNvG3C'  where id = 's96';
 update attrs_cnae set img_author = 'Rudel Sports', img_link = 'https://flic.kr/p/dLQ9Jj'  where id = 'g47822';
 update attrs_cnae set img_author = 'Paulo Pampolin', img_link = 'https://flic.kr/p/dqWgbS'  where id = 'q86402';
 update attrs_cnae set img_author = 'Fabio Bonadeu', img_link = 'https://flic.kr/p/nM3pXc'  where id = 'n77';
 update attrs_cnae set img_author = 'skeeze', img_link = 'https://pixabay.com/photo-1285893/'  where id = 'c27';
 update attrs_cnae set img_author = 'Raskolhnikov Samsa', img_link = 'https://flic.kr/p/9U2Lv8'  where id = 'r93';
 update attrs_cnae set img_author = 'Mariana Andrade', img_link = 'https://flic.kr/p/rQ6xUH'  where id = 'm71120';
 update attrs_cnae set img_author = 'Portal PBH', img_link = 'https://flic.kr/p/dpvKYD'  where id = 'e38';
 update attrs_cnae set img_author = 'Karen Makrous Sobhie', img_link = 'https://flic.kr/p/8YhvH4'  where id = 'c31012';
 update attrs_cnae set img_author = 'Carlos Landaverde', img_link = 'https://flic.kr/p/ec3ftu'  where id = 'g45200';
 update attrs_cnae set img_author = 'Francisco Aragão', img_link = 'https://flic.kr/p/7LXH7m'  where id = 'f41107';
 update attrs_cnae set img_author = 'Francisco Aragão', img_link = 'https://flic.kr/p/oGMy6F'  where id = 'f42111';
 update attrs_cnae set img_author = 'Adriano Barros', img_link = 'https://flic.kr/p/o9BPns'  where id = 'c22293';
 update attrs_cnae set img_author = 'Life-Of-Pix', img_link = 'https://pixabay.com/photo-498438/'  where id = 'j61';
 update attrs_cnae set img_author = 'jarmoluk', img_link = 'https://pixabay.com/photo-427512/'  where id = 'o84124';
 update attrs_cnae set img_author = 'Dalton', img_link = 'https://flic.kr/p/pJH61A'  where id = 'c16';
 update attrs_cnae set img_author = 'Biblioteca de Arte / Art Library Fundação Calouste Gulbenkian', img_link = 'https://flic.kr/p/or7hQ7'  where id = 'c33';
 update attrs_cnae set img_author = 'Deni Williams', img_link = 'https://flic.kr/p/srXFUd'  where id = 'f42219';
 update attrs_cnae set img_author = 'Felipe Pival', img_link = 'https://flic.kr/p/dd4hgi'  where id = 'h53';
 update attrs_cnae set img_author = 'Nícolas Almeida', img_link = 'https://flic.kr/p/cbBAkh'  where id = 'f42995';
 update attrs_cnae set img_author = 'joseph consuelo', img_link = 'https://flic.kr/p/phjQH9'  where id = 'c17';
 update attrs_cnae set img_author = 'Juan Manuel F.M.', img_link = 'https://flic.kr/p/6xc3Ck'  where id = 'f43991';
 update attrs_cnae set img_author = 'jarmoluk', img_link = 'https://pixabay.com/photo-1080595/'  where id = 'f43304';
 update attrs_cnae set img_author = 'Lucas Brentano', img_link = 'https://flic.kr/p/9mAQMv'  where id = 'c15319';
 update attrs_cnae set img_author = 'Transaxle (alias Toprope)', img_link = 'https://flic.kr/p/pWDQ4z'  where id = 'c29492';
 update attrs_cnae set img_author = 'Esporte Clube Pinheiros', img_link = 'https://flic.kr/p/bmLUyS'  where id = 'p85121';
 update attrs_cnae set img_author = 'rafaelthediver', img_link = 'https://flic.kr/p/8Si6yV'  where id = 'c26';
 update attrs_cnae set img_author = 'stereocallo', img_link = 'https://flic.kr/p/dU8Jdj'  where id = 'c19';
 update attrs_cnae set img_author = 'Vinicius Marinho', img_link = 'https://flic.kr/p/9BBkkG'  where id = 'c32';
 update attrs_cnae set img_author = 'Oscar', img_link = 'https://flic.kr/p/bFWHua'  where id = 'g47130';
 update attrs_cnae set img_author = 'skeeze', img_link = 'https://pixabay.com/photo-1285893/'  where id = 'f43215';
 update attrs_cnae set img_author = 'Joao Vagner Brito de Medeiros', img_link = 'https://flic.kr/p/6s4peL'  where id = 'p85201';
 update attrs_cnae set img_author = 'jakza - Jaque Zattera', img_link = 'https://flic.kr/p/oMDxmb'  where id = 's94910';
 update attrs_cnae set img_author = 'stevepb', img_link = 'https://pixabay.com/photo-981400/'  where id = 'k65';
 update attrs_cnae set img_author = 'bogitw', img_link = 'https://pixabay.com/photo-817732/'  where id = 'n81117';
 update attrs_cnae set img_author = 'Tiago Calado', img_link = 'https://flic.kr/p/fQ7hVR'  where id = 'a01130';
 update attrs_cnae set img_author = 'Diego Salcido', img_link = 'https://flic.kr/p/cKLWQ9'  where id = 'g46397';
 update attrs_cnae set img_author = 'L2 Criação', img_link = 'https://flic.kr/p/bmERH6'  where id = 'l';
 update attrs_cnae set img_author = 'L2 Criação', img_link = 'https://flic.kr/p/bmERH6'  where id = 'l68';
 update attrs_cnae set img_author = 'blogdopontodeonibus', img_link = 'https://flic.kr/p/91PFv4'  where id = 'h49221';
 update attrs_cnae set img_author = 'Giancarlo Carbon www.vinantico.eu/giancarbon.htm', img_link = 'https://flic.kr/p/nKQWWJ'  where id = 'c23427';
 update attrs_cnae set img_author = 'Oscar', img_link = 'https://flic.kr/p/bFWHua'  where id = 'g47296';
 update attrs_cnae set img_author = 'Ministério do Desenvolvimento Social e Combate à Fome', img_link = 'https://flic.kr/p/pQnexk'  where id = 'q88';
 update attrs_cnae set img_author = 'Ministério do Desenvolvimento Social e Combate à Fome', img_link = 'https://flic.kr/p/pQnexk'  where id = 'q88006';
 update attrs_cnae set img_author = 'Alex Silva', img_link = 'https://flic.kr/p/axxVF5'  where id = 'c11';
 update attrs_cnae set img_author = 'Braz Fabril', img_link = 'https://flic.kr/p/4YtY4c'  where id = 'g47555';
 update attrs_cnae set img_author = 'Dave Stokes', img_link = 'https://flic.kr/p/ETxvvh'  where id = 'f42928';
 update attrs_cnae set img_author = 'Portal PBH', img_link = 'https://flic.kr/p/dpvKYD'  where id = 'e38114';
 update attrs_cnae set img_author = '*CriCri*', img_link = 'https://flic.kr/p/eh1462'  where id = 'h53105';
 update attrs_cnae set img_author = 'Adriano Lima', img_link = 'https://flic.kr/p/nuBtL5'  where id = 'e36';
 update attrs_cnae set img_author = 'Adriano Lima', img_link = 'https://flic.kr/p/nuBtL6'  where id = 'e36006';
 update attrs_cnae set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593333/'  where id = 'n78108';
 update attrs_cnae set img_author = 'cocoparisienne', img_link = 'https://pixabay.com/photo-992242/'  where id = 'c10112';
 update attrs_cnae set img_author = 'roberto dcarvalho', img_link = 'https://flic.kr/p/rAGVJz'  where id = 'g47610';
 update attrs_cnae set img_author = 'Achi Guitar', img_link = 'https://flic.kr/p/rk5oSB'  where id = 'c23303';
 update attrs_cnae set img_author = 'Elias Rovielo', img_link = 'https://flic.kr/p/q4z8vF'  where id = 'd';
 update attrs_cnae set img_author = 'Elias Rovielo', img_link = 'https://flic.kr/p/q4z8vF'  where id = 'd35';
 update attrs_cnae set img_author = 'Jéssica Flávia Oliveira', img_link = 'https://flic.kr/p/aijQJo'  where id = 'c18';
 update attrs_cnae set img_author = 'Barbara Vidal', img_link = 'https://flic.kr/p/oVatX4'  where id = 's94201';
 update attrs_cnae set img_author = 'Adriano Barros', img_link = 'https://flic.kr/p/o9BPns'  where id = 'c22226';
 update attrs_cnae set img_author = 'geralt', img_link = 'https://pixabay.com/photo-680572/'  where id = 's94995';
 update attrs_cnae set img_author = 'Alex Silva', img_link = 'https://flic.kr/p/axxVF5'  where id = 'g46354';
 update attrs_cnae set img_author = 'AWFG_Berlin', img_link = 'https://pixabay.com/photo-185756/'  where id = 'c19314';
 update attrs_cnae set img_author = 'Voggacom', img_link = 'https://pixabay.com/photo-330234/'  where id = 'a01156';
 update attrs_cnae set img_author = 'PublicDomainPictures', img_link = 'https://pixabay.com/photo-2561/'  where id = 'c10911';
 update attrs_cnae set img_author = 'Biblioteca de Arte / Art Library Fundação Calouste Gulbenkian', img_link = 'https://flic.kr/p/or7hQ7'  where id = 's95';
 update attrs_cnae set img_author = 'FirmBee', img_link = 'https://pixabay.com/photo-577758/'  where id = 'j63';
 update attrs_cnae set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593333/'  where id = 'n78302';
 update attrs_cnae set img_author = 'Unsplash', img_link = 'https://pixabay.com/photo-690523/'  where id = 'c30';
 update attrs_cnae set img_author = 'creisi', img_link = 'https://pixabay.com/photo-245745/'  where id = 'a01555';
 update attrs_cnae set img_author = 'Antranias', img_link = 'https://pixabay.com/photo-1221759/'  where id = 'a02';
 update attrs_cnae set img_author = 'talitappires', img_link = 'https://flic.kr/p/6R3n8j'  where id = 'g47725';
 update attrs_cnae set img_author = 'Ministério do Desenvolvimento Social e Combate à Fome', img_link = 'https://flic.kr/p/pQnexk'  where id = 'q87';
 update attrs_cnae set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593333/'  where id = 'm70';
 update attrs_cnae set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593333/'  where id = 'm70204';
 update attrs_cnae set img_author = 'Dave Stokes', img_link = 'https://flic.kr/p/ETxvvh'  where id = 'c25993';
 update attrs_cnae set img_author = 'nuno_lopes', img_link = 'https://pixabay.com/photo-1314550/'  where id = 's96025';
 update attrs_cnae set img_author = 'Nortis Farmacêutica', img_link = 'https://flic.kr/p/bhRtNK'  where id = 'c21';
 update attrs_cnae set img_author = 'PublicDomainPictures', img_link = 'https://pixabay.com/photo-17310/'  where id = 'j58';
 update attrs_cnae set img_author = 'DarkoStojanovic', img_link = 'https://pixabay.com/photo-563425/'  where id = 'q86909';
 update attrs_cnae set img_author = 'Unsplash', img_link = 'https://pixabay.com/photo-984262/'  where id = 'k64239';
 update attrs_cnae set img_author = 'vivi14216', img_link = 'https://pixabay.com/photo-905513/'  where id = 'c10996';
 update attrs_cnae set img_author = 'Didgeman', img_link = 'https://pixabay.com/photo-1077524/'  where id = 'b08';
 update attrs_cnae set img_author = 'Unsplash', img_link = 'https://pixabay.com/photo-1030952/'  where id = 'a01610';
 update attrs_cnae set img_author = 'StartupStockPhotos', img_link = 'https://pixabay.com/photo-593333/'  where id = 'm74';
 update attrs_cnae set img_author = 'stevepb', img_link = 'https://pixabay.com/photo-948603/'  where id = 'n82911';
 update attrs_cnae set img_author = 'FirmBee', img_link = 'https://pixabay.com/photo-624712/'  where id = 'g47512';
 update attrs_cnae set img_author = 'claude05alleva', img_link = 'https://pixabay.com/photo-334823/'  where id = 'j60';
 update attrs_cnae set img_author = 'simensad', img_link = 'https://pixabay.com/photo-747385/'  where id = 'c29107';
 update attrs_cnae set img_author = 'stevepb', img_link = 'https://pixabay.com/photo-948603/'  where id = 'k66';
 update attrs_cnae set img_author = 'condesign', img_link = 'https://pixabay.com/photo-516635/'  where id = 'g46931';
 update attrs_cnae set img_author = 'FirmBee', img_link = 'https://pixabay.com/photo-624712/'  where id = 'j62015';
 update attrs_cnae set img_author = 'StockSnap', img_link = 'https://pixabay.com/photo-923000/'  where id = 'm73';
 update attrs_cnae set img_author = 'rigotar23', img_link = 'https://pixabay.com/photo-489326/'  where id = 'g47636';
 update attrs_cnae set img_author = 'PublicDomainPictures', img_link = 'https://pixabay.com/photo-2785/'  where id = 'c10520';
 update attrs_cnae set img_author = 'bierfritze', img_link = 'https://pixabay.com/photo-943363/'  where id = 'g46494';
 update attrs_cnae set img_author = 'OpenClipartVectors', img_link = 'https://pixabay.com/photo-1300335/'  where id = 'm69117';
 update attrs_cnae set img_author = 'Bommel12', img_link = 'https://pixabay.com/photo-1115803/'  where id = 'b07';
 update attrs_cnae set img_author = 'Oliver Tobias Obergfell', img_link = 'https://flic.kr/p/frLYry'  where id = 'j62091';