UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Tree Map is a descriptive visualization which allows visualizing participation, in percentage terms, of the different variables available in DataViva. For example, this visualization allows analyzing the importance of a product in the exports of a location. Tree Maps are built with blocks that are proportional to the participation of selected categories in total, and grouped by colors representing the major groups for each variable (or another color coding selected by the color filter).</p>
<p>The logic of the Tree Map is the same used in a pie chart or other visual representation of distribution. The use of squares grouped by major groups in order of importance allows a quick view of items with greater participation in the respective large group, in which it is contained, enabling a fast and simple analysis of the percentage of participation.</p>
<p>One of the visualizations, for instance, shows the participation of each of the products in Minas Gerais export basket, revealing quickly and easily the significant participation of the product Iron Ore in the exports of the state. Several other views are possible, using the variables available in the platform such as economic activities, occupations, localities and intersections between these variables.</p>
<p><a href="/en/build_graph/secex/4mg/all/all?view=Imports/Exports&graph=tree_map" target="_blank" class="btn btn-success" title="Tree Map"><i class="dv-graph-tree_map m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>Tree Map &eacute; um aplicativo descritivo que permite visualizar a participa&ccedil;&atilde;o, em termos percentuais, das diversas vari&aacute;veis dispon&iacute;veis no DataViva. Esta visualiza&ccedil;&atilde;o possibilita analisar a import&acirc;ncia de um produto na pauta de exporta&ccedil;&otilde;es de uma localidade, por exemplo. O gr&aacute;fico do Tree Map &eacute; constru&iacute;do com blocos proporcionais &agrave; participa&ccedil;&atilde;o das categorias selecionadas no total, agrupadas ainda por cores que representam os grandes grupos para cada vari&aacute;vel.</p>
<p>A l&oacute;gica do Tree Map &eacute; a mesma utilizada em um gr&aacute;fico de pizza ou outra forma de representa&ccedil;&atilde;o visual de distribui&ccedil;&atilde;o da participa&ccedil;&atilde;o de itens no somat&oacute;rio total. A utiliza&ccedil;&atilde;o de blocos agrupados por grandes grupos e em ordem de import&acirc;ncia permite uma visualiza&ccedil;&atilde;o r&aacute;pida dos itens com maior participa&ccedil;&atilde;o e em qual grande grupo ele est&aacute; contido, possibilitando uma an&aacute;lise simples e r&aacute;pida dos percentuais de participa&ccedil;&atilde;o.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, mostra a participa&ccedil;&atilde;o de cada um dos produtos nas exporta&ccedil;&otilde;es de Minas Gerais, revelando com clareza a participa&ccedil;&atilde;o significativa do produto Min&eacute;rio de Ferro nas exporta&ccedil;&otilde;es do estado. V&aacute;rias outras perspectivas s&atilde;o poss&iacute;veis por meio dessa visualiza&ccedil;&atilde;o, utilizando as vari&aacute;veis &#8203;&#8203;dispon&iacute;veis na plataforma como atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es, localidades, al&eacute;m da interse&ccedil;&atilde;o entre essas vari&aacute;veis.</p>
<p><a href="/pt/build_graph/secex/4mg/all/all?view=Imports/Exports&graph=tree_map" target="_blank" class="btn btn-success" title="Tree Map"><i class="dv-graph-tree_map m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Tree Map'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Stacked visualization allows analyzing the growth of a variable over time. Built as an area chart in which the height of each line represents its share in total or gross, this view follows the same color pattern of the other visualizations, facilitating the identification of large groups to which each item belongs. Therefore, this visualization facilitates an understanding of the growth patterns and trends of any of the variables available in DataViva.</p>
<p>The purpose of this visualization is to allow the visualization of the data in a time series, revealing product, economic activities, occupations or localities with greater participation over time and its history of growth or decrease, either in gross or percentage.</p>
<p>One of the visualizations, for instance, is for economic activities of Minas Gerais, revealing the overall growth of the state economy and which sectors had the greatest contribution to this growth since 2002. Like the other visualizations, you can modify the data displayed for any of the basic variables available in DataViva (products, activities, occupations) and their intersections with localities all over Brazil at different levels (regions, states, mesoregions, microregions and municipalities).</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=stacked" target="_blank" class="btn btn-success" title="Stacked"><i class="dv-graph-stacked m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o Evolu&ccedil;&atilde;o permite analisar o crescimento da participa&ccedil;&atilde;o de uma vari&aacute;vel ao longo do tempo. Constru&iacute;da como um gr&aacute;fico de &aacute;rea, no qual a altura de cada linha representa sua participa&ccedil;&atilde;o no total ou seu valor bruto, esta visualiza&ccedil;&atilde;o segue o mesmo padr&atilde;o de cores dos outros aplicativos, facilitando a identifica&ccedil;&atilde;o dos grandes grupos aos quais cada item pertence. Desta forma, este aplicativo facilita a compreens&atilde;o dos padr&otilde;es e tend&ecirc;ncias de crescimento de qualquer uma das vari&aacute;veis dispon&iacute;veis no DataViva.</p>
<p>O objetivo do aplicativo Evolu&ccedil;&atilde;o &eacute; permitir a visualiza&ccedil;&atilde;o dos dados em uma s&eacute;rie hist&oacute;rica, revelando produtos, atividades econ&ocirc;micas, ocupa&ccedil;&otilde;es ou localidades com maior participa&ccedil;&atilde;o ao longo do tempo e seu hist&oacute;rico de crescimento ou redu&ccedil;&atilde;o, seja em valores brutos ou percentuais.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, permite avaliar permite avaliar o crescimento total do mercado de trabalho no estado de Minas Gerais e quais os grupos de ocupa&ccedil;&atilde;o tiveram maior contribui&ccedil;&atilde;o neste crescimento, desde 2002. Assim como outras visualiza&ccedil;&otilde;es, &eacute; poss&iacute;vel modificar os dados exibidos para qualquer uma das vari&aacute;veis &#8203;&#8203;b&aacute;sicas dispon&iacute;veis no DataViva (produtos, atividades, ocupa&ccedil;&otilde;es) e seus cruzamentos com as localidades de todo o Brasil em diferentes n&iacute;veis de agrega&ccedil;&atilde;o (regi&atilde;oes, estados, mesorregi&otilde;es, microrregi&otilde;es e munic&iacute;pios).</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=stacked" target="_blank" class="btn btn-success" title="Stacked"><i class="dv-graph-stacked m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Stacked'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Geo Map is a descriptive geographical visualization that enables an analysis of the spatial distribution of the variables available in DataViva. Using a heat scale, it shows the municipalities with the largest (in red) and lowest (blue) values, and allows navigation both to zoom in and out, as to see more information about a selected municipality. This visualization aims to reveal the geographic distribution of the data.</p>
<p>One of the visualizations, for example, shows the economic activities in Minas Gerais by municipality, showing its concentration in the Metropolitan Region of Belo Horizonte. As in other visualizations, you can change the visualization to the desired variable with the filters.</p>
<p><a href="/en/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=geo_map" target="_blank" class="btn btn-success" title="Geo Map"><i class="dv-graph-geo_map m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O Mapa &eacute; uma visualiza&ccedil;&atilde;o descritiva geogr&aacute;fica que possibilita uma an&aacute;lise da distribui&ccedil;&atilde;o espacial das vari&aacute;veis dispon&iacute;veis no DataViva. A partir de uma escala de calor, s&atilde;o mostrados os munic&iacute;pios com maiores valores (em vermelho) e menores valores (em azul), permite a navega&ccedil;&atilde;o de aproxima&ccedil;&atilde;o (zoom in) e afastamento (zoom out) para exibição de maiores informa&ccedil;&otilde;es sobre o munic&iacute;pio selecionado. Este aplicativo tem como objetivo revelar a distribui&ccedil;&atilde;o geogr&aacute;fica dos dados.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, exibe as atividades econ&ocirc;micas em Minas Gerais por munic&iacute;pio, evidenciando sua concentra&ccedil;&atilde;o na Regi&atilde;o Metropolitana de Belo Horizonte. Assim como nas outras visualizações, &eacute; poss&iacute;vel alterar a perspectiva de acordo com a vari&aacute;vel desejada.</p>
<p><a href="/pt/build_graph/rais/4mg/all/all?view=Employment%20by%20Municipality&graph=geo_map" target="_blank" class="btn btn-success" title="Geo Map"><i class="dv-graph-geo_map m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Geo Map'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Network visualization displays the original Product Space, using the same network of products created by professors Hidalgo and Hausmann based on worldwide exports. It represents the connections between products in terms of the probability of co-exportation of these, and is the basis of the theory of economic development proposed by these professors from MIT and Harvard, respectively. In DataViva one can also visualize the &quot;Industry Space&quot;, a representation of the connections of all Brazilian economic activities based on their shared occupations.</p>
<p>This visualization allows highlighting, in the Product Space or the Industry Space, all products or activities in which a region has Revealed Comparative Advantage (RCA&gt;1). Therefore, one can see where are the products or activities in which a region has comparative advantage, if these products or activities are in the central region of the network (are more complex) and what are their connections.</p>
<p>This is a prescriptive visualization that reveals interesting ways for the economic development of a region based on the Product Space theory. According to this theory, a region must move (gain comparative advantage) to products or activities located in the center of the network, starting from those products or activities in which it already has comparative advantage.</p>
<p>One visualization, for instance, on DataViva, is the Industry Space of Minas Gerais, allowing to quickly learn in what activities the state has comparative advantage and in which categories they are (from the same color pattern used on all visualizations).</p>
<p>For a better understanding and interpretation of this visualization, it is recommended to check the terms and basic concepts of the Product Space theory.</p>
<p><a href="/en/build_graph/secex/4mg/all/all?view=Product%20Space&graph=network" target="_blank" class="btn btn-success" title="Network"><i class="dv-graph-network m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>O aplicativo de Rede disponibiliza a visualiza&ccedil;&atilde;o original do Product Space, criada pelos professores Hidalgo and Hausmann, baseada nas exportações mundiais. A visualiza&ccedil;&atilde;o representa as conex&otilde;es entre os produtos em termos de suas probabilidades de co-exporta&ccedil;&atilde;o destes. No DataViva tamb&eacute;m &eacute; poss&iacute;vel visualizar o &ldquo;espa&ccedil;o de atividades&rdquo;, uma representa&ccedil;&atilde;o da rede de conex&otilde;es das atividades econ&ocirc;micas brasileiras a partir de suas ocupa&ccedil;&otilde;es comuns.</p>
<p>A visualiza&ccedil;&atilde;o permite sobrepor os produtos ou as atividades nos quais uma regi&atilde;o possui a chamada vantagem comparativa revelada (RCA&gt;1). Deste modo, pode-se perceber onde est&atilde;o localizados os produtos ou as atividades nos quais a regi&atilde;o possui vantagem comparativa, se estes produtos ou atividades est&atilde;o na regi&atilde;o central da rede (mais complexos) e quais s&atilde;o suas conex&otilde;es.</p>
<p>Este &eacute; um aplicativo prescritivo que revela caminhos mais interessantes para o desenvolvimento econ&ocirc;mico de uma regi&atilde;o com base na teoria do Product Space. De acordo com esta teoria, uma regi&atilde;o deve mover (conquistar vantagem comparativa) para produtos ou atividades localizados no centro da rede a partir daqueles produtos ou atividades nos quais j&aacute; possui vantagem comparativa.</p>
<p>Uma das visualiza&ccedil;&otilde;es presentes no DataViva, por exemplo, é o Espa&ccedil;o de Produtos para Minas Gerais. A visualiza&ccedil;&atilde;o de Rede mostra, de forma simplificada, em quais produtos o estado possui vantagem comparativa e de quais categorias eles pertencem.</p>
<p>Para melhor entendimento e interpreta&ccedil;&atilde;o dessa visualiza&ccedil;&atilde;o &eacute; recomendado consultar os conceitos b&aacute;sicos da teoria do Product Space.</p>
<p><a href="/pt/build_graph/secex/4mg/all/all?view=Product%20Space&graph=network" target="_blank" class="btn btn-success" title="Network"><i class="dv-graph-network m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Network'

UPDATE dataviva.help_subject_question
SET
answer_en = '<p>The Rings is a prescriptive visualization that allows viewing a product, industry or occupation in isolation, making it easier to navigate round its primary and secondary connections, which can be a bit difficult in the Network visualization. It also shows those products, activities or occupations in which the selected location has revealed comparative advantage (RCA&gt; 1).</p>
<p>This is important because, according to the Product Space theory, having comparative advantage in a product means that the region has the expertise to produce it and the knowledge that is shared in the production of connected products. Thus, one can visualize, quickly and easily, if the product has many connections and if these are with products that the region already has comparative advantage, which would facilitate its development, because it means that much of the productive knowledge needed is already present.</p>
<p>Similar to other visualizations, Rings uses a standard color pattern that lets one see of which big group a product, industry or occupation belongs, as well as other groups with which it is connected. Correctly understanding the concepts of the Product Space theory is fundamental to interpret this prescriptive visualization.</p>
<p>One of the visualizations, for instance, shows the connections for biologists in Minas Gerais, therefore we can analyze the occupations connected to biologists directly or not.</p>
<p><a href="/en/build_graph/rais/4mg/all/2211?view=Similar%20Occupations&graph=rings" target="_blank" class="btn btn-success" title="Rings"><i class="dv-graph-rings m-r-sm"></i>Open Visualization<i class="m-l-xl fa fa-angle-right"></i></a></p>',
answer_pt = '<p>A visualiza&ccedil;&atilde;o de An&eacute;is é prescritiva e permite analisar um produto, atividade econ&ocirc;mica ou ocupa&ccedil;&atilde;o de forma isolada, facilitando a navega&ccedil;&atilde;o por suas conex&otilde;es de primeiro e segundo grau, o que pode ser um pouco complicada na visualiza&ccedil;&atilde;o de Rede. A visualiza&ccedil;&atilde;o de An&eacute;is disponibiliza produtos, atividades ou ocupa&ccedil;&otilde;es nas quais a localidade selecionada possui vantagem comparativa revelada (RCA&gt;1).</pr>
<p>Isto &eacute; importante porque, de acordo com a teoria do Product Space, possuir vantagem comparativa em um produto, por exemplo, significa que a regi&atilde;o possui os conhecimentos necess&aacute;rios para produzi-lo, conhecimentos que s&atilde;o compartilhados na produ&ccedil;&atilde;o de produtos conectados. Deste modo, visualiza-se de forma r&aacute;pida e f&aacute;cil se o produto analisado possui muitas conex&otilde;es e se estas s&atilde;o com produtos que a regi&atilde;o j&aacute; possui vantagem comparativa, o que facilitaria seu desenvolvimento.<p/>
<p>Semelhante a outros aplicativos, a visualiza&ccedil;&atilde;o de An&eacute;is utiliza um conjunto de cores padr&atilde;o que permite verificar qual grupoum produto, ind&uacute;stria ou atividade econ&ocirc;mica pertence, bem como outros grupos com os quais ele est&aacute; conectado. &Eacute; interessante compreender corretamente os conceitos da teoria do Product Space para interpretar essa visualiza&ccedil;&atilde;o prescritiva.</p>
<p>Uma das visualiza&ccedil;&otilde;es, por exemplo, mostra as conex&otilde;es para os bi&oacute;logos em Minas Gerais, sendo poss&iacute;vel analisar as ocupa&ccedil;&otilde;es conectadas aos bi&oacute;logos de forma direta ou em segundo grau.</p>
<p><a href="/pt/build_graph/rais/4mg/all/2211?view=Similar%20Occupations&graph=rings" target="_blank" class="btn btn-success" title="Rings"><i class="dv-graph-rings m-r-sm"></i>Abrir Visualização<i class="m-l-xl fa fa-angle-right"></i></a></p>'
WHERE description_en = 'Rings'








