UPDATE `dataviva`.`help_subject_question` SET
`answer_en`='<p><b>Product&nbsp;Complexity&nbsp;(PCI)</b>: The Product Complexity Index is based on two main concepts: diversity and ubiquity. Diversity refers to the number of products that the region exports with comparative advantage. Ubiquity is the number of regions that export a given product with comparative advantage. The index is based on the idea that more complex products are produced and exported by a smaller number of regions, while requiring more productive knowledge to be manufactured. Therefore, more complex products are those produced by few regions that produce different products.</p>\n\n<p><b>Economic Complexity&nbsp;(ECI)</b>: The Economic Complexity Index measures the diversity and complexity of a locations\'s economy. It is calculated by taking the average complexity of the products a location exports with international comparative advantage, weighted by their share in the location\'s overall exports.</p>\n\n<p>If it is of interest, the formulas for the calculation of these indices can be found at: <a href=\"https://atlas.media.mit.edu/atlas/\" target=\"_blank\">https://atlas.media.mit.edu/atlas/</a></p>',
`answer_pt`='<p><b>Complexidade do Produto (PCI)</b>:O &Iacute;ndice de Complexidade do Produto est&aacute; baseado em dois conceitos principais: diversidade e ubiquidade. A diversidade diz respeito ao n&uacute;mero de produtos que a regi&atilde;o exporta com vantagem comparativa. A ubiquidade &eacute; o n&uacute;mero de regi&otilde;es que exportam dado produto com vantagem comparativa. O &iacute;ndice apoia-se na ideia de que produtos mais complexos s&atilde;o produzidos e exportados por um n&uacute;mero menor de regi&otilde;es, ao mesmo tempo em que exigem mais conhecimentos produtivos para serem fabricados. Portanto, produtos mais complexos s&atilde;o aqueles produzidos por poucas regi&otilde;es que produzem diversos produtos.</p>\n\n<p><b>Complexidade Econ&ocirc;mica (ECI)</b>:O Indicador de Complexidade Econ&ocirc;mica mede a diversidade e complexidade da economia de uma localidade. &Eacute; calculado pela m&eacute;dia ponderada da complexidade dos produtos em que a localidade possui vantagem comparativa revelada, sendo os pesos com base nas exporta&ccedil;&otilde;es totais.</p>\n\n<p>Se for de seu interesse, as f&oacute;rmulas para o c&aacute;lculo desses &iacute;ndices podem ser encontradas em: <a href=\"https://atlas.media.mit.edu/atlas/\" target=\"_blank\">https://atlas.media.mit.edu/atlas/</a></p>'
WHERE `id`='46';

UPDATE `dataviva`.`help_subject_question` SET
`answer_en`='<p>Distance is a measure of how far the current production structure of a region is in relation to a given product, signifying the difficulty of this region to achieve a comparative advantage in this product. The idea here is that each product requires a set of capabilities, which may or may not be shared in the manufacture process of other products proximity. Products closest to other products in which the region already has comparative advantage will be more easily developed - because some of the required knowledge is already present in the region. Distance is a measure that reflects the amount of new capabilities that a region needs in order to manufacture and export a product with comparative advantage, meaning that the greater the distance, the more knowledge that needs to be acquired and the longer (or more difficult) it will be to have advantage in the export of this product.</p>\n\n<p>In DataViva, distance is calculated considering both world trade (International), and just Brazilian exports (Domestic).</p>',
`answer_pt`='<p>A Dist&acirc;ncia mede o afastamento entre um dado produto em rela&ccedil;&atilde;o &agrave; estrutura produtiva atual de uma regi&atilde;o, significando a dificuldade desta regi&atilde;o em atingir uma vantagem comparativa neste produto. A ideia aqui &eacute; que cada produto exige um conjunto de conhecimentos produtivos, os quais podem ou n&atilde;o ser compartilhados na fabrica&ccedil;&atilde;o de outros produtos (proximidade). Produtos mais pr&oacute;ximos de outros produtos nos quais a regi&atilde;o j&aacute; possui vantagem comparativa ser&atilde;o mais facilmente desenvolvidos &ndash; exatamente porque alguns dos conhecimentos necess&aacute;rios j&aacute; est&atilde;o presentes na regi&atilde;o. Dist&acirc;ncia &eacute; uma medida que reflete a quantidade de novos conhecimentos produtivos que uma regi&atilde;o precisa adquirir para poder fabricar e exportar um determinado produto com vantagem comparativa, ou seja, quanto maior for a Dist&acirc;ncia, mais conhecimentos ter&atilde;o de ser adquiridos e mais longo ou dif&iacute;cil ser&aacute; o caminho para se ter vantagem na exporta&ccedil;&atilde;o deste produto.</p>\n\n<p>No DataViva, o c&aacute;lculo da Dist&acirc;ncia &eacute; feito tanto considerando o com&eacute;rcio mundial (Internacional), quanto apenas as exporta&ccedil;&otilde;es brasileiras (Dom&eacute;stico).</p>'
WHERE `id`='47';

UPDATE `dataviva`.`help_subject_question` SET 
`answer_en`='<p><b>Location Diversity</b>: The number of unique municipalities where a given variable is present.</p>\n<p><b>Industry Diversit</b>: The number of unique 6-digit CNAE industries that are present for a given variable.</p>\n<p><b>Occupation Diversity</b>: The number of unique 4-digit CBO occupations that are present for a given variable.</p>\n<p><b>Product Diversity</b>: The number of unique HS4 products that are present for a given variable.</p>\n<p><b>Export Destination Diversity</b>: The number of unique import countries that are present for a given variable.</p>\n<p><b>Effective Diversity</b>: Effective diversity is the diversity of a given variable corrected for the share that each unit represents. For instance, if a location exports two products and each of these represents a 50% share, then the effective diversity is 2. However, if these shares were 99% and 1%, then the effective diversity would be 1.058, which is close to 1, since this is a location that exports primarily one product.</p>',
`answer_pt`='<p><b>Diversidade de Localidades</b>: O n&uacute;mero de munic&iacute;pios &uacute;nicos nos quais determinada vari&aacute;vel est&aacute; presente.</p>\n<p><b>Diversidade de Atividades</b>: O n&uacute;mero de atividades &uacute;nicas de 6 d&iacute;gitos CNAE que est&atilde;o presentes para determinada vari&aacute;vel.</p>\n<p><b>Diversidade de Ocupa&ccedil;&otilde;es</b>: O n&uacute;mero de ocupa&ccedil;&otilde;es &uacute;nicas de 4 d&iacute;gitos CBO que est&atilde;o presentes para determinada vari&aacute;vel.</p>\n<p><b>Diversidade de Produtos</b>: O n&uacute;mero de produtos &uacute;nicos HS4 que est&atilde;o presentes para determinada vari&aacute;vel.</p>\n<p><b>Diversidade de Destino das Exporta&ccedil;&otilde;es</b>: O n&uacute;mero de pa&iacute;ses importadores &uacute;nicos que est&atilde;o presentes para determinada vari&aacute;vel.</p>\n<p><b>Diversidade Efetiva</b>: A diversidade efetiva &eacute; a diversidade de determinada vari&aacute;vel corrigida pela participa&ccedil;&atilde;o que cada unidade representa. Por exemplo, se uma localidade exporta dois produtos e cada um representa uma participa&ccedil;&atilde;o de 50%, ent&atilde;o a diversidade efetiva &eacute; 2. Por outro lado, se a participa&ccedil;&atilde;o for de 99% e 1%, ent&atilde;o a diversidade efetiva ser&aacute; 1,058, pr&oacute;xima a 1, uma vez que esta &eacute; uma localidade que exporta basicamente um &uacute;nico produto.</p>'
WHERE `id`='48';

DELETE FROM `dataviva`.`help_subject_question` WHERE `description_en`='Reference Articles';

INSERT INTO `dataviva`.`help_subject_question`
(`description_en`, `description_pt`, `answer_en`, `answer_pt`, `subject_id`, `active`)
VALUES
('Reference Articles',
'Artigos de Referência',
'<a href=\"http://science.sciencemag.org/content/317/5837/482\"  target=\"_blank\">The Product Space Conditions the Development of Nations</a><br/>
 <a href=\"http://link.springer.com/article/10.1007/s10887-006-9009-4\"  target=\"_blank\">What you export matters</a><br/>
 <a href=\"http://papers.ssrn.com/sol3/papers.cfm?abstract_id=939646\"  target=\"_blank\">Structural Transformation and Patterns of Comparative Advantage in the Product Space</a><br/>
 <a href=\"http://www.pnas.org/content/106/26/10570.short\"  target=\"_blank\">The building blocks of economic complexity</a><br/>',
'<a href=\"http://science.sciencemag.org/content/317/5837/482\"  target=\"_blank\">O Espaço de Produtos condiciona o desenvolvimento das nações</a><br/>
 <a href=\"http://link.springer.com/article/10.1007/s10887-006-9009-4\"  target=\"_blank\">O que você exporta é relevante</a><br/>
 <a href=\"http://papers.ssrn.com/sol3/papers.cfm?abstract_id=939646\"  target=\"_blank\">Transformação estrutural e padrões de vantagem comparativa no Espaço de Produtos</a><br/>
 <a href=\"http://www.pnas.org/content/106/26/10570.short\"  target=\"_blank\">Os elementos constitutivos da complexidade econômica</a><br/>',
'6', '1');
