CREATE TABLE `graph_title` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title_en` varchar(255) DEFAULT NULL,
  `title_pt` varchar(255) DEFAULT NULL,
  `subtitle_en` varchar(255) DEFAULT NULL,
  `subtitle_pt` varchar(255) DEFAULT NULL,
  `product` tinyint(1) DEFAULT '0',
  `partner` tinyint(1) DEFAULT '0',
  `type` varchar(45) DEFAULT NULL,
  `occupation` tinyint(1) DEFAULT '0',
  `industry` tinyint(1) DEFAULT '0',
  `establishment` tinyint(1) DEFAULT '0',
  `location` tinyint(1) DEFAULT '0',
  `hedu_course` tinyint(1) DEFAULT '0',
  `university` tinyint(1) DEFAULT '0',
  `shapes` varchar(45) DEFAULT NULL,
  `graph` varchar(45) DEFAULT NULL,
  `dataset` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=latin1;

INSERT INTO `graph_title` VALUES 
  (1, '<shapes> in <location> that export <product>', '<shapes> <location_in> <location> que exportam <product>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (2, 'Origin of <product> from <location>', 'Origem de <product> <location_from> <location>', 'Based on state production', 'Baseado nos estados produtores', '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'partner', 'tree_map', 'secex'),
  (3, '<shapes> in <location> that import <product>', '<shapes> <location_in> <location> que importam <product> ', NULL, NULL, '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'secex'),
  (4, 'Destination of <product> from <location>', 'Destino de <product> <location_from> <location> ', 'Based on state production', 'Baseado nos estados produtores', '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'partner', 'tree_map', 'secex'),
  (5, 'Exports of <location> to <partner>', 'Exportações <location_of> <location> <partner_to> <partner>', 'Based on state production', 'Baseado nos estados produtores', '0', '1', 'export', '0', '0', '0', '1', '0', '0', 'product', 'tree_map', 'secex'),
  (6, 'Imports from <partner> to <location>', 'Importações <location_of> <location> <partner_to> <partner>', 'Based on state production', 'Baseado nos estados produtores', '0', '1', 'import', '0', '0', '0', '1', '0', '0', 'product', 'tree_map', 'secex'),
  (7, '<shapes> in <location> that import from <partner>', '<shapes> <location_in> <location> que importam <partner_to> <partner>', NULL, NULL, '0', '1', 'import', '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'secex'),
  (8, '<shapes> in <location> that export to <partner>', '<shapes> <location_in> <location> que importam <partner_to> <partner>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '0', '1', 'export', '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'secex'),
  (9, 'Industries in <location>', 'Indústrias <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'industry', 'tree_map', 'rais'),
  (10, 'Industries in <location> that employ <occupation>', 'Indústrias <location_in> <location> que empregam <occupation>', NULL, NULL, '0', '0', NULL, '1', '0', '0', '1', '0', '0', 'industry', 'tree_map', 'rais'),
  (11, '<shapes> in <location> that employ <occupation>', '<shapes> <location_in> <location> que empregam <occupation>', NULL, NULL, '0', '0', NULL, '1', '0', '0', '1', '0', '0', 'location', 'tree_map', 'rais'),
  (12, 'Occupations in <location> employed in the <industry>', 'Ocupações <location_in> <location> empregadas em <industry>', NULL, NULL, '0', '0', NULL, '0', '1', '0', '1', '0', '0', 'occupation', 'tree_map', 'rais'),
  (13, '<shapes> in <location> that have the <industry>', '<shapes> <location_in> <location> que possuem <industry>', NULL, NULL, '0', '0', NULL, '0', '1', '0', '1', '0', '0', 'location', 'tree_map', 'rais'),
  (14, 'Connections for <product> in <location>', 'Conexões para <product> <location_in> <location>', 'Based on state production', NULL, '1', '0', NULL, '0', '0', '0', '1', '0', '0', 'product', 'rings', 'secex'),
  (15, 'Connections for <industry> in <location>', 'Conexões para <industry> <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '1', '0', '1', '0', '0', 'industry', 'rings', 'rais'),
  (16, 'Connections for <occupation> in <location>', 'Conexões para <occupation> <location_in> <location>', NULL, NULL, '0', '0', NULL, '1', '0', '0', '1', '0', '0', 'occupation', 'rings', 'rais'),
  (17, '<shapes> in <location> that export <product>', '<shapes> <location_in> <location> que exportam <product>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (18, 'Origin of <product> from <location>', 'Origem de <product> <location_from> <location>', 'Based on state production', 'Baseado nos estados produtores', '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'partner', 'stacked', 'secex'),
  (19, '<shapes> in <location> that import <product>', '<shapes> <location_in> <location> que importam <product> ', NULL, NULL, '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (20, 'Destination of <product> from <location>', 'Destino de <product> <location_from> <location> ', 'Based on state production', 'Baseado nos estados produtores', '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'partner', 'stacked', 'secex'),
  (21, 'Exports of <location> to <partner>', 'Exportações <location_of> <location> <partner_to> <partner>', 'Based on state production', 'Baseado nos estados produtores', '0', '1', 'export', '0', '0', '0', '1', '0', '0', 'product', 'stacked', 'secex'),
  (22, 'Imports from <partner> to <location>', 'Importações <location_of> <location> <partner_to> <partner>', 'Based on state production', 'Baseado nos estados produtores', '0', '1', 'import', '0', '0', '0', '1', '0', '0', 'product', 'stacked', 'secex'),
  (23, '<shapes> in <location> that import from <partner>', '<shapes> <location_in> <location> que importam <partner_to> <partner>', NULL, NULL, '0', '1', 'import', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (24, '<shapes> in <location> that export to <partner>', '<shapes> <location_in> <location> que importam <partner_to> <partner>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '0', '1', 'export', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (25, 'Industries in <location>', 'Indústrias <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'industry', 'stacked', 'rais'),
  (26, 'Industries in <location> that employ <occupation>', 'Indústrias <location_in> <location> que empregam <occupation>', NULL, NULL, '0', '0', NULL, '1', '0', '0', '1', '0', '0', 'industry', 'stacked', 'rais'),
  (27, '<shapes> in <location> that employ <occupation>', '<shapes> <location_in> <location> que empregam <occupation>', NULL, NULL, '0', '0', NULL, '1', '0', '0', '1', '0', '0', 'location', 'stacked', 'rais'),
  (28, 'Occupations in <location> employed in the <industry>', 'Ocupações <location_in> <location> empregadas em <industry>', NULL, NULL, '0', '0', NULL, '0', '1', '0', '1', '0', '0', 'occupation', 'stacked', 'rais'),
  (29, '<shapes> in <location> that have the <industry>', '<shapes> <location_in> <location> que possuem <industry>', NULL, NULL, '0', '0', NULL, '0', '1', '0', '1', '0', '0', 'location', 'stacked', 'rais'),
  (30, 'Health Equipments in <location> per <shapes>', 'Equipamentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'cnes_equipment'),
  (31, 'Health Establishments in <location> per <shapes>', 'Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'equipment', 'tree_map', 'cnes_equipment'),
  (32, 'Health Establishments in <location> per <shapes>', 'Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'cnes_establishment'),
  (33, 'Health Equipments in <location> per <shapes>', 'Equipamentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'cnes_equipment'),
  (34, 'Number of Health Equipments <location_in> <location> over time', 'Evolução do Número de Equipamentos de Saúde <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'equipment', 'stacked', 'cnes_equipment'),
  (35, 'Health Establishments in <location> per <shapes>', 'Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'cnes_establishment'),
  (36, 'Health Equipments in <location> per <shapes>', 'Equipamentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'bar', 'cnes_equipment'),
  (37, 'Health Equipments in <location> per <shapes>', 'Equipamentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'sus_availability_indicator', 'bar', 'cnes_equipment'),
  (38, 'Health Establishments in <location> per <shapes>', 'Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'bar', 'cnes_establishment'),
  (39, 'Health Establishments in <location> per <shapes>', 'Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'unit_type', 'tree_map', 'cnes_establishment'),
  (40, 'Health Establishments in <location> per <shapes> over time', 'Evolução do Número de Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'unit_type', 'stacked', 'cnes_establishment'),
  (41, 'Health Equipments in <location> per <shapes>', 'Principais Equipamentos de Saúde por <shapes> <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'equipment', 'bar', 'cnes_equipment'),
  (42, 'Health Equipments Distribution per Location in <location>', 'Distribuição dos Equipamentos de Saúde por Unidade Territorial <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'map', 'cnes_equipment'),
  (43, 'Health Establishments in <location> per <shapes>', 'Estabelecimentos de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'emergency_facility', 'bar', 'cnes_establishment'),
  (44, 'Health Establishments Distribution per Location in <location>', 'Distribuição dos Estabelecimentos de Saúde por Unidade Territorial <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'map', 'cnes_establishment'),
  (45, 'Total Beds in <location> per <shapes>', 'Quantidade de Leitos <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'cnes_bed'),
  (46, 'Beds in <location> per <shapes>', 'Leitos <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'bed_type', 'tree_map', 'cnes_bed'),
  (47, 'Beds Distribution per Location in <location>', 'Distribuição dos Leitos por Unidade Territorial <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'map', 'cnes_bed'),
  (48, 'Total Beds in <location> per <shapes> over time', 'Evolução da Quantidade de Leitos <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'cnes_bed'),
  (49, 'Total Beds in <location> per <shapes> over time', 'Evolução da Quantidade de Leitos <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'bed_type', 'stacked', 'cnes_bed'),
  (50, 'Health Professionals Ditribution per Location in <location>', 'Distribuição dos Profissionais de Saúde por Unidade Territorial <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'map', 'cnes_professional'),
  (51, 'Health Professionals in <location> per <shapes>', 'Profissionais de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'tree_map', 'cnes_professional'),
  (52, 'Health Professionals in <location> per <shapes> over time', 'Evolução do Número de Profissionais de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'cnes_professional'),
  (53, 'Health Professionals in <location> per <shapes> over time', 'Evolução do Número de Profissionais de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'unit_type', 'stacked', 'cnes_professional'),
  (54, 'Main <shapes> per Quantity in <location>', 'Principais <shapes> por Quantidade <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'bed_type', 'bar', 'cnes_bed'),
  (55, 'Health Professionals in <location> per <shapes>', 'Profissionais de Saúde <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'unit_type', 'tree_map', 'cnes_professional'),
  (56, 'Health Equipments in <establishment> per <shapes>', 'Equipamentos de Saúde por <shapes> - <establishment>', NULL, NULL, '0', '0', NULL, '0', '0', '1', '0', '0', '0', 'equipment', 'tree_map', 'cnes_equipment'),
  (57, 'Health Occupations in <location> per Occupation', 'Profissionais de Saúde <location_in> <location> por Ocupação', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'occupation', 'tree_map', 'cnes_professional'),
  (58, 'Number of Health Professionals in <location> per Occupation over time', 'Evolução do número de Profissionais de Saúde <location_in> <location> por Ocupação', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'occupation', 'stacked', 'cnes_professional'),
  (59, 'Number of Health Professionals in <location> per Occupation over time', 'Evolução do número de Profissionais de Saúde <location_in> <location> por Ocupação', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'occupation_group', 'stacked', 'cnes_professional'),
  (60, 'Number of Establishments of Health in <location> per Facilities', 'Número de Estabelecimentos de Saúde <location_in> <location>por Tipo de Instalações', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'facilities', 'bar', NULL),
  (61, 'Number of Health Establishments in <location> by Facilities Type', 'Número de Estabelecimentos de Saúde <location_in> <location> por Tipo de Instalações', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'facility_type', 'bar', 'cnes_establishment'),
  (62, 'Exports of <location>', 'Exportações <location_of> <location>', 'Based on state production', 'Baseado nos estados produtores', '0', '0', 'export', '0', '0', '0', '1', '0', '0', 'product', 'tree_map', 'secex'),
  (63, 'Imports from <partner>', 'Importações <location_of> <location>', 'Based on state production', 'Baseado nos estados produtores', '0', '0', 'import', '0', '0', '0', '1', '0', '0', 'product', 'tree_map', 'secex'),
  (64, 'Trade Balance of <product> in <location>', 'Balança Comercial de <product> <location_from> <location>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '1', '0', NULL, '0', '0', '0', '1', '0', '0', 'type', 'line', 'secex'),
  (65, 'Origin of <product> from <location>', 'Origem de <product> <location_from> <location>', 'Based on state production', 'Baseado nos estados produtores', '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'partner', 'line', 'secex'),
  (66, 'Destination of <product> from <location>', 'Destino de <product> <location_from> <location>', 'Based on state production', 'Baseado nos estados produtores', '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'partner', 'line', 'secex'),
  (67, 'Exports of <product> from port in <location>', 'Exportações de <product> por porto <location_in> <location>', NULL, NULL, '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'port', 'line', 'secex'),
  (68, 'Imports of <product> from port in <location>', 'Exportações de <product> por porto <location_in> <location>', '', NULL, '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'port', 'line', 'secex'),
  (69, 'Trade Balance of <location> from <partner>', 'Balança comerical <location_from> <location> <partner_to> <partner>', 'Based on state production', 'Baseado nos estados produtores', '0', '1', NULL, '0', '0', '0', '1', '0', '0', 'type', 'line', 'secex'),
  (70, 'Exports by port from <location> to <partner>', 'Exportações por porto <location_of> <location> <partner_to> <partner>', NULL, NULL, '0', '1', 'export', '0', '0', '0', '1', '0', '0', 'port', 'line', 'secex'),
  (71, 'Imports by port from <location> to <partner>', 'Importações por porto <location_of> <location> <partner_to> <partner>', NULL, NULL, '0', '1', 'import', '0', '0', '0', '1', '0', '0', 'port', 'line', 'secex'),
  (72, 'Exports by port from <location> to <partner>', 'Exportações por porto <location_of> <location> <partner_to> <partner>', NULL, NULL, '0', '1', 'export', '0', '0', '0', '1', '0', '0', 'port', 'tree_map', 'secex'),
  (73, 'Imports by port from <location> to <partner>', 'Importações por porto <location_of> <location> <partner_to> <partner>', NULL, NULL, '0', '1', 'import', '0', '0', '0', '1', '0', '0', 'port', 'tree_map', 'secex'),
  (74, 'Exports of <product> from port in <location>', 'Exportações de <product> por porto <location_in> <location>', NULL, NULL, '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'port', 'tree_map', 'secex'),
  (75, 'Imports of <product> from port in <location>', 'Exportações de <product> por porto <location_in> <location>', '', NULL, '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'port', 'tree_map', 'secex'),
  (76, 'Trade Balance of <location>', 'Balança comerical <location_from> <location>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'type', 'line', 'secex'),
  (77, 'Exports by port from <location>', 'Exportações por porto <location_of> <location>', NULL, NULL, '0', '0', 'export', '0', '0', '0', '1', '0', '0', 'port', 'line', 'secex'),
  (78, 'Imports by port from <location>', 'Importações por porto <location_of> <location>', NULL, NULL, '0', '0', 'import', '0', '0', '0', '1', '0', '0', 'port', 'line', 'secex'),
  (79, 'Exports by port from <location>', 'Exportações por porto <location_of> <location>', NULL, NULL, '0', '0', 'export', '0', '0', '0', '1', '0', '0', 'port', 'tree_map', 'secex'),
  (80, 'Imports by port from <location>', 'Importações por porto <location_of> <location>', NULL, NULL, '0', '0', 'import', '0', '0', '0', '1', '0', '0', 'port', 'tree_map', 'secex'),
  (81, 'Students Status in <hedu_course> in <location>', 'Situação dos Estudantes em <hedu_course> <location_of> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '1', '0', 'hedu_course', 'line', 'hedu'),
  (82, 'Exports of <location>', 'Exportações <location_of> <location>', NULL, NULL, '0', '0', 'export', '0', '0', '0', '1', '0', '0', 'partner', 'stacked', 'secex'),
  (83, '<shapes> in <location> that export <product>', '<shapes> <location_in> <location> que exportam <product>', NULL, NULL, '1', '0', 'export', '0', '0', '0', '1', '0', '0', 'location', 'map', 'secex'),
  (84, '<shapes> in <location> that export <product>', '<shapes> <location_in> <location> que exportam <product>', NULL, NULL, '1', '0', 'import', '0', '0', '0', '1', '0', '0', 'location', 'map', 'secex'),
  (85, '<shapes> in <location> that employ <occupation>', '<shapes> <location_in> <location> que empregam <occupation>', NULL, NULL, '0', '0', NULL, '1', '0', '0', '1', '0', '0', 'location', 'map', 'rais'),
  (86, '<shapes> in <location> that employ <industry>', '<shapes> <location_in> <location> que empregam <industry>', NULL, NULL, '0', '0', NULL, '0', '1', '0', '1', '0', '0', 'location', 'map', 'rais'),
  (87, '<shapes> in <location> that offers <hedu_course>', '<shapes> <location_in> <location> que oferecem <hedu_course>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '1', '0', 'location', 'stacked', 'hedu'),
  (88, 'Students Status at <university>', 'Situação dos Estudantes em <university>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '0', '0', '1', 'university', 'line', 'hedu'),
  (89, 'Imports of <location>', 'Importações <location_of> <location>', NULL, NULL, '0', '0', 'import', '0', '0', '0', '1', '0', '0', 'partner', 'stacked', 'secex'),
  (90, 'Exports of <location>', 'Exportações <location_of> <location>', NULL, NULL, '0', '0', 'export', '0', '0', '0', '1', '0', '0', 'product', 'stacked', 'secex'),
  (91, 'Imports of <location>', 'Importações <location_of> <location>', NULL, NULL, '0', '0', 'import', '0', '0', '0', '1', '0', '0', 'product', 'stacked', 'secex'),
  (92, 'Exports of <location> by <shapes>', 'Exportações <location_of> <location> por <shapes>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '0', '0', 'export', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (93, 'Imports of <location> by <shapes>', 'Importações <location_of> <location> por <shapes>', 'Based on the exporting municipality', 'Baseado nos municípios exportadores', '0', '0', 'import', '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'secex'),
  (94, 'Occupations in <location>', 'Ocupações <location_in> <location>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'occupation', 'stacked', 'rais'),
  (95, 'Employment in <location> by <shapes>', 'Empregos <location_in> <location> por <shapes>', NULL, NULL, '0', '0', NULL, '0', '0', '0', '1', '0', '0', 'location', 'stacked', 'rais');