CREATE TABLE graph_title (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title_en` varchar(255) DEFAULT NULL,
  `title_pt` varchar(255) DEFAULT NULL,
  `subtitle_en` varchar(255) DEFAULT NULL,
  `subtitle_pt` varchar(255) DEFAULT NULL,
  `product` tinyint(1) DEFAULT '0',
  `partner` tinyint(1) DEFAULT '0',
  `type` varchar(45) DEFAULT NULL,
  `occupation` tinyint(1) DEFAULT '0',
  `industry` tinyint(1) DEFAULT '0',
  `location` tinyint(1) DEFAULT '0',
  `shapes` varchar(45) DEFAULT NULL,
  `graph` varchar(45) DEFAULT NULL,
  `dataset` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1;

INSERT INTO `graph_title` VALUES 
  (1,'<shapes> in <location> that export <product>','<shapes> <location_in> <location> que exportam <product>','Based on the exporting municipality','Baseado nos municípios exportadores',1,0,'export',0,0,1,'location','tree_map','secex'),
  (2,'Origin of <product> from <location>','Origem de <product> <location_from> <location>','Based on state production','Baseado nos estados produtores',1,0,'import',0,0,1,'partner','tree_map','secex'),
  (3,'<shapes> in <location> that import <product>','<shapes> <location_in> <location> que importam <product> ',NULL,NULL,1,0,'import',0,0,1,'location','tree_map','secex'),
  (4,'Destination of <product> from <location>','Destino de <product> <location_from> <location> ','Based on state production','Baseado nos estados produtores',1,0,'export',0,0,1,'partner','tree_map','secex'),
  (5,'Exports of <location> to <partner>','Exportações <location_of> <location> <partner_to> <partner>','Based on state production','Baseado nos estados produtores',0,1,'export',0,0,1,'product','tree_map','secex'),
  (6,'Imports from <partner> to <location>','Importações <location_of> <location> <partner_to> <partner>','Based on state production','Baseado nos estados produtores',0,1,'import',0,0,1,'product','tree_map','secex'),
  (7,'<shapes> in <location> that import from <partner>','<shapes> <location_in> <location> que importam <partner_to> <partner>',NULL,NULL,0,1,'import',0,0,1,'location','tree_map','secex'),
  (8,'<shapes> in <location> that export to <partner>','<shapes> <location_in> <location> que importam <partner_to> <partner>','Based on the exporting municipality','Baseado nos municípios exportadores',0,1,'export',0,0,1,'location','tree_map','secex'),
  (9,'Industries in <location>','Indústrias <location_in> <location>',NULL,NULL,0,0,NULL,0,0,1,'industry','tree_map','rais'),
  (10,'Industries in <location> that employ <occupation>','Indústrias <location_in> <location> que empregam <occupation>',NULL,NULL,0,0,NULL,1,0,1,'industry','tree_map','rais'),
  (11,'<shapes> in <location> that employ <occupation>','<shapes> <location_in> <location> que empregam <occupation>',NULL,NULL,0,0,NULL,1,0,1,'location','tree_map','rais'),
  (12,'Occupations in <location> employed in the <industry>','Ocupações <location_in> <location> empregadas em <industry>',NULL,NULL,0,0,NULL,0,1,1,'occupation','tree_map','rais'),
  (13,'<shapes> in <location> that have the <industry>','<shapes> <location_in> <location> que possuem <industry>',NULL,NULL,0,0,NULL,0,1,1,'location','tree_map','rais'),
  (14,'Connections for <product> in <location>','Conexões para <product> <location_in> <location>','Based on state production',NULL,1,0,NULL,0,0,1,'product','rings','secex'),
  (15,'Connections for <industry> in <location>','Conexões para <industry> <location_in> <location>',NULL,NULL,0,0,NULL,0,1,1,'industry','rings','rais'),
  (16,'Connections for <occupation> in <location>','Conexões para <occupation> <location_in> <location>',NULL,NULL,0,0,NULL,1,0,1,'occupation','rings','rais'),
  (17,'<shapes> in <location> that export <product>','<shapes> <location_in> <location> que exportam <product>','Based on the exporting municipality',NULL,1,0,'export',0,0,1,'location','stacked','secex'),
  (18,'Origin of <product> from <location>',NULL,'Based on state production',NULL,1,0,'import',0,0,1,'partner','stacked','secex'),
  (19,'<shapes> in <location> that import <product>',NULL,'Based on the importing municipality',NULL,1,0,'import',0,0,1,'location','stacked','secex'),
  (20,'Destination of <product> from <location>',NULL,'Based on state production',NULL,1,0,'export',0,0,1,'partner','stacked','secex'),
  (21,'Exports of <location> to <partner>',NULL,'Based on sate production',NULL,0,1,'export',0,0,1,'product','stacked','secex'),
  (22,'Imports from <partner> to <location>',NULL,'Based on state production',NULL,0,1,'import',0,0,1,'product','stacked','secex'),
  (23,'<shapes> in <location> that import from <partner>',NULL,'Based on the exporting municipality',NULL,0,1,'import',0,0,1,'location','stacked','secex'),
  (24,'<shapes> in <location> that export to <partner>',NULL,'Based on the exporting municipality',NULL,0,1,'export',0,0,1,'location','stacked','secex'),
  (25,'Industries in <location>',NULL,NULL,NULL,0,0,NULL,0,0,1,'industry','stacked','rais'),
  (26,'Industries in <location> that employ <occupation>',NULL,NULL,NULL,0,0,NULL,1,0,1,'industry','stacked','rais'),
  (27,'<shapes> in <location> that employ <occupation>',NULL,NULL,NULL,0,0,NULL,1,0,1,'location','stacked','rais'),
  (28,'Occupations in <location> employed in the <industry>',NULL,NULL,NULL,0,0,NULL,0,1,1,'occupation','stacked','rais'),
  (29,'<shapes> in <location> that have the <industry>',NULL,NULL,NULL,0,0,NULL,0,1,1,'location','stacked','rais');
